/**
 * The CI that builds the shared Capacitor project.
 *
 * Both workflows live here rather than beside their adapters for a structural
 * reason: `android` and `ios` materialise into ONE project directory, so
 * whichever target is materialised first must write BOTH workflows or the
 * directory arrives half-buildable. Each adapter importing the other's renderer
 * would be a cycle; the project they both build is the honest owner of both.
 *
 * Re-materialising the other target rewrites these to identical bytes, so there
 * is no drift and no ordering to get right.
 */

import type { GameTargetContext } from '../gameTarget';
import { bundleIdFor, capacitorDirectory } from './capacitor';

export function renderAndroidWorkflow(ctx: GameTargetContext): string {
  const { game } = ctx;
  const dir = capacitorDirectory(game.slug);
  return `# Build ${game.title} as an Android APK.
#
# Generated by Builderforce. The native android/ directory is NOT in the
# repository — it is produced by \`cap add\` here, against whatever Capacitor
# version npm just resolved, so this workflow cannot rot against a snapshot.
name: ${game.title.slice(0, 40)} · Android

on:
  push:
    branches: [main]
    paths:
      - '${dir}/**'
      - '.github/workflows/${game.slug}-android.yml'
  workflow_dispatch:

jobs:
  apk:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${dir}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      # Capacitor 7's Android Gradle Plugin requires JDK 21. The runner ships
      # several JDKs; without pinning, Gradle picks whichever is default and
      # fails with an unhelpful "Unsupported class file major version".
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - uses: android-actions/setup-android@v3

      - name: Install dependencies
        run: npm install

      - name: Generate the native Android project
        run: npx cap add android

      - name: Copy the game into it
        run: npx cap sync android

      - name: Build the APK
        working-directory: ${dir}/android
        run: chmod +x ./gradlew && ./gradlew assembleDebug --no-daemon

      - name: Name the artifact after the game
        run: cp android/app/build/outputs/apk/debug/app-debug.apk ${game.slug}.apk

      - uses: actions/upload-artifact@v4
        with:
          name: ${game.slug}-android-apk
          path: ${dir}/${game.slug}.apk
          if-no-files-found: error

      - name: Summary
        run: |
          echo "### ${game.title} — Android build" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "Application id: \\\`${bundleIdFor(game.slug)}\\\`" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "Download **${game.slug}-android-apk** from the Artifacts section of this run," >> $GITHUB_STEP_SUMMARY
          echo "transfer it to an Android phone and open it. You will need to allow" >> $GITHUB_STEP_SUMMARY
          echo "installing from unknown sources the first time." >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "This APK is **debug-signed** — it installs on your own device but cannot" >> $GITHUB_STEP_SUMMARY
          echo "be uploaded to Google Play. See the README for the release path." >> $GITHUB_STEP_SUMMARY
`;
}

export function renderIosWorkflow(ctx: GameTargetContext): string {
  const { game } = ctx;
  const dir = capacitorDirectory(game.slug);
  return `# Build ${game.title} for iOS.
#
# Generated by Builderforce. Without signing secrets this builds for the
# SIMULATOR — which verifies the app compiles and runs, but cannot be installed
# on a physical iPhone. Apple requires a paid Developer Program membership to
# sign for devices; there is no way around that from CI.
#
# To get an installable .ipa, set these repository secrets:
#   IOS_CERTIFICATE_P12        base64 of your .p12 distribution certificate
#   IOS_CERTIFICATE_PASSWORD   its export password
#   IOS_PROVISIONING_PROFILE   base64 of the .mobileprovision for ${bundleIdFor(game.slug)}
name: ${game.title.slice(0, 40)} · iOS

on:
  push:
    branches: [main]
    paths:
      - '${dir}/**'
      - '.github/workflows/${game.slug}-ios.yml'
  workflow_dispatch:

jobs:
  ios:
    runs-on: macos-latest
    defaults:
      run:
        working-directory: ${dir}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Generate the native iOS project
        # \`cap add ios\` runs \`pod install\` itself; CocoaPods is preinstalled on
        # the macOS runner image.
        run: npx cap add ios

      - name: Copy the game into it
        run: npx cap sync ios

      - name: Decide whether this run can sign
        id: signing
        env:
          CERT: \${{ secrets.IOS_CERTIFICATE_P12 }}
        run: |
          if [ -n "$CERT" ]; then
            echo "signed=true" >> "$GITHUB_OUTPUT"
          else
            echo "signed=false" >> "$GITHUB_OUTPUT"
          fi

      # ── Unsigned path ─────────────────────────────────────────────────────
      - name: Build for the simulator
        if: steps.signing.outputs.signed == 'false'
        working-directory: ${dir}/ios/App
        run: |
          xcodebuild \\
            -workspace App.xcworkspace \\
            -scheme App \\
            -sdk iphonesimulator \\
            -configuration Debug \\
            -derivedDataPath build \\
            CODE_SIGNING_ALLOWED=NO \\
            build

      - name: Package the simulator app
        if: steps.signing.outputs.signed == 'false'
        working-directory: ${dir}/ios/App
        run: |
          cd build/Build/Products/Debug-iphonesimulator
          zip -r "$GITHUB_WORKSPACE/${dir}/${game.slug}-simulator.zip" App.app

      - uses: actions/upload-artifact@v4
        if: steps.signing.outputs.signed == 'false'
        with:
          name: ${game.slug}-ios-simulator
          path: ${dir}/${game.slug}-simulator.zip
          if-no-files-found: error

      # ── Signed path ───────────────────────────────────────────────────────
      - name: Install the signing identity
        if: steps.signing.outputs.signed == 'true'
        env:
          CERT: \${{ secrets.IOS_CERTIFICATE_P12 }}
          CERT_PASSWORD: \${{ secrets.IOS_CERTIFICATE_PASSWORD }}
          PROFILE: \${{ secrets.IOS_PROVISIONING_PROFILE }}
        run: |
          # A throwaway keychain, unlocked for this run only. Never the login
          # keychain: a runner is shared infrastructure and the identity must not
          # outlive the job.
          KEYCHAIN="$RUNNER_TEMP/signing.keychain-db"
          KEYCHAIN_PASSWORD="$(uuidgen)"
          security create-keychain -p "$KEYCHAIN_PASSWORD" "$KEYCHAIN"
          security set-keychain-settings -lut 21600 "$KEYCHAIN"
          security unlock-keychain -p "$KEYCHAIN_PASSWORD" "$KEYCHAIN"

          echo "$CERT" | base64 --decode > "$RUNNER_TEMP/cert.p12"
          security import "$RUNNER_TEMP/cert.p12" -P "$CERT_PASSWORD" -A \\
            -t cert -f pkcs12 -k "$KEYCHAIN"
          security set-key-partition-list -S apple-tool:,apple: -k "$KEYCHAIN_PASSWORD" "$KEYCHAIN"
          security list-keychain -d user -s "$KEYCHAIN"

          mkdir -p ~/Library/MobileDevice/Provisioning\\ Profiles
          echo "$PROFILE" | base64 --decode > ~/Library/MobileDevice/Provisioning\\ Profiles/build.mobileprovision

          rm -f "$RUNNER_TEMP/cert.p12"

      - name: Archive and export the .ipa
        if: steps.signing.outputs.signed == 'true'
        working-directory: ${dir}/ios/App
        run: |
          cat > ExportOptions.plist <<'PLIST'
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0"><dict>
            <key>method</key><string>app-store-connect</string>
            <key>signingStyle</key><string>manual</string>
            <key>destination</key><string>export</string>
          </dict></plist>
          PLIST

          xcodebuild \\
            -workspace App.xcworkspace \\
            -scheme App \\
            -sdk iphoneos \\
            -configuration Release \\
            -archivePath build/App.xcarchive \\
            archive

          xcodebuild \\
            -exportArchive \\
            -archivePath build/App.xcarchive \\
            -exportOptionsPlist ExportOptions.plist \\
            -exportPath build/ipa

      - uses: actions/upload-artifact@v4
        if: steps.signing.outputs.signed == 'true'
        with:
          name: ${game.slug}-ios-ipa
          path: ${dir}/ios/App/build/ipa/*.ipa
          if-no-files-found: error

      - name: Summary
        run: |
          echo "### ${game.title} — iOS build" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "Bundle id: \\\`${bundleIdFor(game.slug)}\\\`" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          if [ "\${{ steps.signing.outputs.signed }}" = "true" ]; then
            echo "Signed **.ipa** attached to this run. Upload it to TestFlight to install on a device." >> $GITHUB_STEP_SUMMARY
          else
            echo "Unsigned **simulator** build attached to this run." >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "This cannot be installed on an iPhone — Apple requires a paid Developer" >> $GITHUB_STEP_SUMMARY
            echo "Program membership to sign for devices. To play on an iPhone right now," >> $GITHUB_STEP_SUMMARY
            echo "use the published web app and add it to your home screen." >> $GITHUB_STEP_SUMMARY
          fi
`;
}

/** Both workflows, at their workspace-root paths. Written by either native target. */
export function capacitorWorkflowFiles(ctx: GameTargetContext): Record<string, string> {
  return {
    [`.github/workflows/${ctx.game.slug}-android.yml`]: renderAndroidWorkflow(ctx),
    [`.github/workflows/${ctx.game.slug}-ios.yml`]: renderIosWorkflow(ctx),
  };
}
