name = "builderforce-frontend"
main = ".vercel/output/static/_worker.js"
compatibility_date = "2026-03-07"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = ".vercel/output/static/_next/static"

[vars]
NEXT_PUBLIC_WORKER_URL = "https://builderforce-worker.seanhogg.workers.dev"
