/**
 * Example chat title display component showing how titles are rendered.
 * Demonstrates AC3 (concise titles 3-10 words) and FR4 (prominent display).
 */

import React from 'react';

interface ChatDialogTitleExampleProps {
  title: string;
  isAutoGenerated?: boolean;
  onEdit?: () => void;
}

export function ChatDialogTitleExample({
  title,
  isAutoGenerated = true,
  onEdit,
}: ChatDialogTitleExampleProps) {
  return (
    <div className="chat-title-example">
      <div className="title-container">
        <span className="title-text">{title}</span>
        {isAutoGenerated && (
          <span className="title-badge" aria-label="Auto-generated by system">
            ✨ auto
          </span>
        )}
      </div>
      {onEdit && (
        <button
          className="edit-title-button"
          onClick={onEdit}
          aria-label="Edit title"
        >
          ✏️
        </button>
      )}
    </div>
  );
}

/*
// Example usage:

<ChatDialogTitleExample
  title="Fix Login Bug"
  isAutoGenerated={true}
  onEdit={() => console.log('Edit clicked')}
/>

// Displays:
// Fix Login Bug [auto]    [✏️]
*/