/**
 * The DEV-SERVER run step — what actually makes a live preview exist.
 *
 * The ingress ({@link ./previewIngress}) proxies `preview.builderforce.ai/<token>/*`
 * through the run's `AgentContainerDO` to `127.0.0.1:$PREVIEW_PORT`. Until now nothing
 * ever bound that port: no step started `npm run dev`, so the passthrough always
 * answered 503 and the QR could only ever encode a PUBLISHED build. This module is the
 * missing half — the step DEFINITION, the HEALTH CHECK, and the STATE it records.
 *
 * ── WHY THE CONFIG IS DATA, NOT A DOC COMMENT ──────────────────────────────────────
 * A dev server reached through a public origin does not work out of the box:
 *   • Vite refuses an unknown `Host` header (`server.allowedHosts`) — the request 403s
 *     before it reaches your app.
 *   • The HMR client connects to `ws://<devHost>:<devPort>` by default, which does not
 *     exist from the phone's point of view; it must be told to dial the PUBLIC origin
 *     over TLS (`hmr.protocol/host/clientPort`), or every edit needs a manual reload.
 *   • Metro/Expo bake the packager host into the bundle URL, so it needs the public
 *     hostname in `REACT_NATIVE_PACKAGER_HOSTNAME` / `EXPO_PACKAGER_PROXY_URL`.
 * So {@link buildPreviewDevServerStep} EMITS those files and env vars as part of the
 * step. Whatever runs the step writes them verbatim — the tuning is shipped, not
 * described.
 *
 * ── FLAG GATE ──────────────────────────────────────────────────────────────────────
 * Inert while `PREVIEW_INGRESS_ENABLED` is unset, exactly like the rest of the
 * vertical: {@link previewStepForRun} returns null, so a launch carries no preview spec
 * and nothing changes for any existing run.
 */
import { PREVIEW_CONTAINER_PATH_PREFIX, PREVIEW_HOST } from './previewIngress';
import { mintPreviewToken, PREVIEW_TOKEN_TTL_SECONDS } from './previewToken';
import { signalPendingWork } from './cronWorkSignal';
import {
  checkPreviewCapacity,
  loadPreviewSession,
  loadProjectPreviewSession,
  openPreviewSession,
  setPreviewSessionStatus,
  projectIdForExecution,
  type PreviewCapacityVerdict,
} from './previewSessions';
import type { Db } from '../../infrastructure/database/connection';
import type { Env } from '../../env';

/**
 * The port a preview dev server binds inside the container. 5173 is Vite's own default,
 * so the common case needs no override at all and a hand-run `npm run dev` lands on the
 * port the passthrough is already pointed at.
 */
export const PREVIEW_PORT = 5173;

/** The public origin a preview is served from — what HMR must dial back through. */
export const PREVIEW_PUBLIC_ORIGIN = `https://${PREVIEW_HOST}`;

/** A file the step writes into the workspace before starting the server. */
export interface PreviewConfigFile {
  /** Repo-relative path. */
  path: string;
  contents: string;
}

/**
 * One candidate way to start a dev server. Ordered; the first whose `when` marker
 * exists in the workspace wins, and the last entry has no marker so there is always an
 * answer. Kept as DATA so the decision is reviewable here rather than buried in a shell
 * script inside the image.
 */
export interface PreviewStartCandidate {
  /** Repo-relative file whose presence selects this candidate. Absent = always matches. */
  when?: string;
  /** Additional evidence: the package.json `scripts` key this candidate needs. */
  requiresScript?: string;
  /** The command to run, detached, from the workspace root. */
  command: string;
}

export interface PreviewDevServerStep {
  port: number;
  publicOrigin: string;
  /** Written before the server starts. */
  files: PreviewConfigFile[];
  /** Merged into the dev server's environment. */
  env: Record<string, string>;
  /** Ordered start candidates — first match wins. */
  candidates: PreviewStartCandidate[];
  /** How the step decides the server is UP (the API re-runs the same probe itself). */
  health: { path: string; attempts: number; intervalMs: number; timeoutMs: number };
}

/**
 * The Vite override. Loads the project's OWN config first and merges on top of it, so a
 * project keeps its plugins/aliases and only gains the host tuning it cannot know about
 * (it has no idea it is being served through a public proxy).
 *
 * `allowedHosts` accepts the preview host explicitly; `hmr` points the browser client at
 * the public origin on 443/wss instead of the container-local port; `strictPort` makes a
 * port collision LOUD (a server silently on 5174 would health-check green from the app's
 * point of view and 503 through the passthrough).
 */
function viteConfigFile(port: number): PreviewConfigFile {
  return {
    path: 'vite.config.builderforce-preview.mjs',
    contents: `// GENERATED by BuilderForce live preview — do not edit.
// Serves this project's dev server through ${PREVIEW_PUBLIC_ORIGIN}, so a phone can load
// it. Merges over the project's own vite config; never replaces it.
import { defineConfig, mergeConfig } from 'vite';

async function projectConfig() {
  for (const candidate of ['./vite.config.js', './vite.config.mjs', './vite.config.ts']) {
    try {
      const mod = await import(candidate);
      const base = mod.default ?? mod.config ?? {};
      return typeof base === 'function' ? await base({ command: 'serve', mode: 'development' }) : base;
    } catch { /* try the next filename */ }
  }
  return {};
}

export default defineConfig(async () => mergeConfig(await projectConfig(), {
  server: {
    host: '0.0.0.0',
    port: ${port},
    strictPort: true,
    // The public preview origin terminates TLS and proxies here; Vite rejects an
    // unknown Host header without this.
    allowedHosts: ['${PREVIEW_HOST}', '.builderforce.ai', 'localhost', '127.0.0.1'],
    hmr: {
      // The HMR client runs in the PHONE's browser, so it must dial the public origin
      // on 443 over wss — not the container-local port it would infer.
      protocol: 'wss',
      host: '${PREVIEW_HOST}',
      clientPort: 443,
    },
    watch: { usePolling: true },
  },
}));
`,
  };
}

/**
 * The Metro/Expo override. Metro bakes the packager host into every bundle/asset URL it
 * hands the app, so pointing it at the public origin is the whole job; the env vars
 * below cover the Expo CLI path and this file covers a bare `metro.config.js` project.
 */
function metroConfigFile(port: number): PreviewConfigFile {
  return {
    path: 'metro.config.builderforce-preview.js',
    contents: `// GENERATED by BuilderForce live preview — do not edit.
// Points Metro at ${PREVIEW_PUBLIC_ORIGIN} so bundle/asset URLs resolve from a phone.
const path = require('path');

let config = {};
for (const candidate of ['./metro.config.js', './metro.config.cjs']) {
  try { config = require(path.resolve(process.cwd(), candidate)); break; } catch { /* next */ }
}

module.exports = {
  ...config,
  server: {
    ...(config.server || {}),
    port: ${port},
  },
};
`,
  };
}

/**
 * Build the step. Pure — no IO — so the command/config contract is unit-testable and the
 * SAME description is what gets handed to the runner, recorded on the lease, and shown
 * in diagnostics.
 */
export function buildPreviewDevServerStep(port: number = PREVIEW_PORT): PreviewDevServerStep {
  return {
    port,
    publicOrigin: PREVIEW_PUBLIC_ORIGIN,
    files: [viteConfigFile(port), metroConfigFile(port)],
    env: {
      PORT: String(port),
      HOST: '0.0.0.0',
      PREVIEW_PORT: String(port),
      PREVIEW_PUBLIC_ORIGIN: PREVIEW_PUBLIC_ORIGIN,
      // Metro / React Native / Expo read the packager host from these; without them the
      // bundle URL points at a container-local address the phone cannot resolve.
      REACT_NATIVE_PACKAGER_HOSTNAME: PREVIEW_HOST,
      EXPO_PACKAGER_PROXY_URL: PREVIEW_PUBLIC_ORIGIN,
      // Next.js dev needs to trust the proxying origin for its HMR/RSC callbacks.
      NEXT_PUBLIC_PREVIEW_ORIGIN: PREVIEW_PUBLIC_ORIGIN,
      BROWSER: 'none',
      CI: '1',
    },
    candidates: [
      // Expo first: an Expo project ALSO has a package.json `dev` script, so a generic
      // match would start the wrong server.
      { when: 'app.json', requiresScript: 'start', command: `npx expo start --port ${port} --host lan` },
      { when: 'vite.config.builderforce-preview.mjs', requiresScript: 'dev', command: `npx vite --config vite.config.builderforce-preview.mjs --port ${port} --host 0.0.0.0` },
      { when: 'next.config.js', command: `npx next dev --port ${port} --hostname 0.0.0.0` },
      { command: `npm run dev -- --port ${port} --host 0.0.0.0` },
    ],
    health: { path: '/', attempts: 20, intervalMs: 1_500, timeoutMs: 5_000 },
  };
}

/** True when the live-preview vertical is switched on for this deployment. */
export function previewEnabled(env: Env): boolean {
  return env.PREVIEW_INGRESS_ENABLED === 'true' && !!env.AGENT_CONTAINER;
}

/**
 * The preview step for a run, or null when the feature is off. This is what a launcher
 * puts on the wire: while the flag is unset every run is launched EXACTLY as before.
 */
export function previewStepForRun(env: Env): PreviewDevServerStep | null {
  return previewEnabled(env) ? buildPreviewDevServerStep() : null;
}

export interface PreviewProbe {
  ok: boolean;
  /** HTTP status the dev server answered through the passthrough, when it answered. */
  status?: number;
  detail?: string;
}

/**
 * HEALTH CHECK — is a dev server actually answering on PREVIEW_PORT?
 *
 * Probes through the SAME path a phone takes (container DO → `/__preview__/` → the dev
 * server) rather than asking the container whether it spawned a process: a process that
 * started and crashed, or bound the wrong port, is exactly the failure this must catch.
 * A 5xx from the passthrough means "no server"; anything the dev server itself answers
 * (200, 404, even a 500 from the app) proves the port is bound.
 */
export async function probePreviewDevServer(env: Env, executionId: number): Promise<PreviewProbe> {
  if (!env.AGENT_CONTAINER) return { ok: false, detail: 'container binding unavailable' };
  try {
    const stub = env.AGENT_CONTAINER.get(env.AGENT_CONTAINER.idFromName(`exec:${executionId}`));
    const res = await stub.fetch(new Request(`https://agent-container${PREVIEW_CONTAINER_PATH_PREFIX}/`, {
      method: 'GET',
      headers: { 'x-builderforce-preview-probe': '1' },
    }));
    // 502/503 are the passthrough's own "no dev server" answers (see container/server.mjs).
    const ok = res.status !== 502 && res.status !== 503;
    return { ok, status: res.status, ...(ok ? {} : { detail: `passthrough answered ${res.status}` }) };
  } catch (e) {
    return { ok: false, detail: e instanceof Error ? e.message : String(e) };
  }
}

/** What the mint endpoint reports about a run's preview. */
export interface PreviewRunState {
  status: 'live' | 'starting' | 'unavailable';
  detail?: string;
  port?: number;
}

/**
 * The authoritative state of a run's preview: the recorded lease, CONFIRMED against a
 * live probe. A lease that says `live` while the container has died must not mint a URL
 * a phone will fail to load, so the probe — not the row — has the last word.
 */
export async function resolvePreviewRunState(
  env: Env, db: Db, tenantId: number, executionId: number,
): Promise<PreviewRunState> {
  const lease = await loadPreviewSession(db, tenantId, executionId);
  if (!lease || lease.status === 'failed' || lease.status === 'stopped' || lease.status === 'idle_evicted') {
    return { status: 'unavailable', ...(lease?.detail ? { detail: lease.detail } : {}) };
  }
  const probe = await probePreviewDevServer(env, executionId);
  if (!probe.ok) {
    return lease.status === 'starting'
      ? { status: 'starting', port: lease.port, ...(probe.detail ? { detail: probe.detail } : {}) }
      : { status: 'unavailable', port: lease.port, ...(probe.detail ? { detail: probe.detail } : {}) };
  }
  if (lease.status !== 'live') {
    // The probe just proved it: promote the lease so the sweep and the budgets agree.
    await setPreviewSessionStatus(db, tenantId, executionId, 'live', null);
  }
  return { status: 'live', port: lease.port };
}

/**
 * The container-op the dev-server step reports through: `start` opens the lease and
 * hands back everything the runner needs, `ready` / `failed` close the loop, and
 * `probe` re-runs the health check on demand.
 *
 * Lives here rather than in `handleContainerOp` so the preview vertical stays one
 * module and the route delegates instead of growing a branch (the route is presentation;
 * this is the application decision).
 */
export async function handlePreviewOp(
  env: Env,
  db: Db,
  ctx: { tenantId: number; executionId: number },
  args: Record<string, unknown>,
): Promise<{ status: number; body: unknown }> {
  if (!previewEnabled(env)) {
    return { status: 200, body: { ok: false, error: 'live preview is not enabled' } };
  }
  const action = typeof args.action === 'string' ? args.action : '';
  const { tenantId, executionId } = ctx;

  if (action === 'start') {
    // Acquiring an instance is the moment the budget applies — not the mint, which only
    // hands out a URL for capacity that was already granted.
    const capacity = await checkPreviewCapacity(db, tenantId, executionId);
    if (!capacity.ok) {
      return { status: 200, body: { ok: false, error: capacityMessage(capacity), reason: capacity.reason } };
    }
    const step = buildPreviewDevServerStep();
    const projectId = await projectIdForExecution(db, tenantId, executionId);
    await openPreviewSession(db, { tenantId, executionId, projectId, port: step.port });
    // An open lease IS pending work: the frequent cron tick is KV-gated so Neon can
    // autosuspend, and without a signal the eviction sweep would only fire on the
    // 30-minute floor — which would make the 3-minute idle policy a fiction. Signalling
    // here puts the sweep back on the 5-minute tick for as long as a preview is open.
    await signalPendingWork(env);
    return { status: 200, body: { ok: true, step } };
  }

  if (action === 'ready') {
    const probe = await probePreviewDevServer(env, executionId);
    await setPreviewSessionStatus(
      db, tenantId, executionId,
      probe.ok ? 'live' : 'failed',
      probe.ok ? null : (probe.detail ?? 'dev server did not answer on the preview port'),
    );
    return { status: 200, body: { ok: probe.ok, ...(probe.detail ? { detail: probe.detail } : {}) } };
  }

  if (action === 'failed') {
    const detail = typeof args.detail === 'string' ? args.detail.slice(0, 500) : 'dev server failed to start';
    await setPreviewSessionStatus(db, tenantId, executionId, 'failed', detail);
    return { status: 200, body: { ok: true } };
  }

  if (action === 'probe') {
    return { status: 200, body: await probePreviewDevServer(env, executionId) };
  }

  return { status: 200, body: { ok: false, error: `unknown preview action '${action}'` } };
}

/** Human copy for a refused acquisition — one phrasing, used by the op and the route. */
export function capacityMessage(verdict: Exclude<PreviewCapacityVerdict, { ok: true }>): string {
  return verdict.reason === 'tenant_cap'
    ? `This workspace already has ${verdict.limit} live previews open. Close one and try again.`
    : 'Live preview is at capacity across the platform right now. Try again in a few minutes.';
}

/** A minted preview link, or the reason there isn't one. */
export type PreviewMint =
  | { available: true; url: string; expiresInSeconds: number; executionId: number; status: 'live' | 'starting' }
  | { available: false; detail?: string };

/**
 * Mint the public URL for a run's preview — the ONE implementation both mint routes
 * (by execution, and by project for the Mobile panel) share, so a URL can never be
 * handed out for a preview that isn't actually serving.
 */
export async function mintPreviewForExecution(
  env: Env, db: Db, tenantId: number, executionId: number,
): Promise<PreviewMint> {
  if (!previewEnabled(env)) return { available: false };
  const state = await resolvePreviewRunState(env, db, tenantId, executionId);
  if (state.status === 'unavailable') {
    return { available: false, ...(state.detail ? { detail: state.detail } : {}) };
  }
  const token = await mintPreviewToken(env.JWT_SECRET, executionId, Date.now() / 1000);
  return {
    available: true,
    url: `${PREVIEW_PUBLIC_ORIGIN}/${token}/`,
    expiresInSeconds: PREVIEW_TOKEN_TTL_SECONDS,
    executionId,
    status: state.status,
  };
}

/** The same mint, addressed by PROJECT — what the Mobile panel has to work with. */
export async function mintPreviewForProject(
  env: Env, db: Db, tenantId: number, projectId: number,
): Promise<PreviewMint> {
  if (!previewEnabled(env)) return { available: false };
  const lease = await loadProjectPreviewSession(db, tenantId, projectId);
  if (!lease) return { available: false };
  return mintPreviewForExecution(env, db, tenantId, lease.executionId);
}
