/**
 * Geometry generation — turning a brief into a real drawing or a real solid.
 *
 * A CAD or 3D brief was previously honoured by a parameterised primitive built in
 * the browser: the file was valid and portable, but it described a fixed plate or
 * a fixed box rather than anything the prompt asked for. This module closes that
 * gap in the only way that is honest for geometry: a model chooses the SHAPE — the
 * outline, the features, the solids and their dimensions — under a strict schema,
 * and this module evaluates that shape deterministically into DXF or STL.
 *
 * The split matters. Asking a model to emit DXF or STL text directly produces
 * files that are plausible and frequently unopenable — an unclosed polyline, a
 * facet with two vertices, a normal that points into the solid. Asking it for a
 * bounded parametric spec instead means every file this emits is generated by code
 * that can only produce closed, well-formed geometry, while the shape is still the
 * one the brief described.
 *
 * Everything below the model call is pure: spec in, geometry text out. It runs in
 * a test with no network and no key.
 */

/* ---------- the spec a model is allowed to author ---------- */

export interface CadProfileSpec {
  /** Closed outer boundary, in millimetres, counter-clockwise. */
  outline: Array<{ x: number; y: number }>;
  /** Bores and clearance holes cut from the profile. */
  holes?: Array<{ x: number; y: number; r: number }>;
  /** Open construction lines — fold lines, centrelines, cut paths. */
  lines?: Array<{ x1: number; y1: number; x2: number; y2: number }>;
  /** What the drawing is, in the model's own words. Kept for the deliverable. */
  summary?: string;
}

export type SolidSpec =
  | { type: 'box'; x: number; y: number; z: number; width: number; depth: number; height: number }
  | { type: 'cylinder'; x: number; y: number; z: number; radius: number; height: number }
  | { type: 'sphere'; x: number; y: number; z: number; radius: number };

export interface Model3dSpec {
  solids: SolidSpec[];
  summary?: string;
}

/** Tessellation density. Fine enough to read as round, coarse enough to stay small. */
const ARC_SEGMENTS = 32;
const SPHERE_BANDS = 16;
/** A model that runs away with the spec must not turn into a 40 MB export. */
const MAX_SOLIDS = 48;
const MAX_OUTLINE_POINTS = 512;

const CAD_SCHEMA = {
  type: 'object',
  additionalProperties: false,
  required: ['outline', 'summary'],
  properties: {
    outline: {
      type: 'array',
      minItems: 3,
      items: {
        type: 'object',
        additionalProperties: false,
        required: ['x', 'y'],
        properties: { x: { type: 'number' }, y: { type: 'number' } },
      },
    },
    holes: {
      type: 'array',
      items: {
        type: 'object',
        additionalProperties: false,
        required: ['x', 'y', 'r'],
        properties: { x: { type: 'number' }, y: { type: 'number' }, r: { type: 'number' } },
      },
    },
    lines: {
      type: 'array',
      items: {
        type: 'object',
        additionalProperties: false,
        required: ['x1', 'y1', 'x2', 'y2'],
        properties: { x1: { type: 'number' }, y1: { type: 'number' }, x2: { type: 'number' }, y2: { type: 'number' } },
      },
    },
    summary: { type: 'string' },
  },
} as const;

const MODEL3D_SCHEMA = {
  type: 'object',
  additionalProperties: false,
  required: ['solids', 'summary'],
  properties: {
    solids: {
      type: 'array',
      minItems: 1,
      items: {
        type: 'object',
        additionalProperties: false,
        required: ['type', 'x', 'y', 'z'],
        properties: {
          type: { type: 'string', enum: ['box', 'cylinder', 'sphere'] },
          x: { type: 'number' }, y: { type: 'number' }, z: { type: 'number' },
          width: { type: 'number' }, depth: { type: 'number' }, height: { type: 'number' },
          radius: { type: 'number' },
        },
      },
    },
    summary: { type: 'string' },
  },
} as const;

/** The response contract handed to the model, per kind. */
export const GEOMETRY_RESPONSE_SCHEMAS = {
  cad: { type: 'json_schema' as const, json_schema: { name: 'cad_profile', strict: true, schema: CAD_SCHEMA } },
  model3d: { type: 'json_schema' as const, json_schema: { name: 'solid_model', strict: true, schema: MODEL3D_SCHEMA } },
};

export const GEOMETRY_SYSTEM_PROMPTS = {
  cad: 'You are a mechanical draughtsman. Read the brief and design a REAL 2D profile for it, in millimetres, '
    + 'as a closed counter-clockwise outline plus any bores and construction lines the part needs. '
    + 'Use the dimensions the brief gives; where it gives none, choose ones a machinist would find sensible. '
    + 'The outline must not self-intersect, and every hole must lie inside it. Reply with JSON only.',
  model3d: 'You are a 3D modeller. Read the brief and build it from positioned primitives — boxes, cylinders and spheres — '
    + 'in millimetres, with the Z axis up and the model resting on Z=0. Positions are the CENTRE of each primitive. '
    + 'Use as many primitives as the shape genuinely needs and no more; make the proportions match the brief. '
    + 'Reply with JSON only.',
};

/* ---------- validation ---------- */

function finite(value: unknown): number | null {
  const number = typeof value === 'number' ? value : Number(value);
  return Number.isFinite(number) ? number : null;
}

/**
 * Read a model's answer as a profile, or reject it.
 *
 * A spec that cannot be drawn is a failure worth falling back from, not something
 * to patch up: a silently repaired outline is a part nobody designed.
 */
export function readCadSpec(value: unknown): CadProfileSpec | null {
  const raw = value as Partial<CadProfileSpec> | null;
  if (!raw || !Array.isArray(raw.outline)) return null;
  const outline = raw.outline
    .slice(0, MAX_OUTLINE_POINTS)
    .map((point) => ({ x: finite(point?.x), y: finite(point?.y) }))
    .filter((point): point is { x: number; y: number } => point.x !== null && point.y !== null);
  if (outline.length < 3) return null;
  const holes = (Array.isArray(raw.holes) ? raw.holes : [])
    .map((hole) => ({ x: finite(hole?.x), y: finite(hole?.y), r: finite(hole?.r) }))
    .filter((hole): hole is { x: number; y: number; r: number } => hole.x !== null && hole.y !== null && !!hole.r && hole.r > 0);
  const lines = (Array.isArray(raw.lines) ? raw.lines : [])
    .map((line) => ({ x1: finite(line?.x1), y1: finite(line?.y1), x2: finite(line?.x2), y2: finite(line?.y2) }))
    .filter((line): line is { x1: number; y1: number; x2: number; y2: number } =>
      line.x1 !== null && line.y1 !== null && line.x2 !== null && line.y2 !== null);
  return { outline, holes, lines, ...(typeof raw.summary === 'string' ? { summary: raw.summary } : {}) };
}

export function readModel3dSpec(value: unknown): Model3dSpec | null {
  const raw = value as Partial<Model3dSpec> | null;
  if (!raw || !Array.isArray(raw.solids)) return null;
  const solids: SolidSpec[] = [];
  for (const candidate of raw.solids.slice(0, MAX_SOLIDS)) {
    const solid = candidate as Record<string, unknown> | null;
    const [x, y, z] = [finite(solid?.x) ?? 0, finite(solid?.y) ?? 0, finite(solid?.z) ?? 0];
    if (solid?.type === 'box') {
      const [width, depth, height] = [finite(solid.width), finite(solid.depth), finite(solid.height)];
      if (width && depth && height && width > 0 && depth > 0 && height > 0) {
        solids.push({ type: 'box', x, y, z, width, depth, height });
      }
    } else if (solid?.type === 'cylinder') {
      const [radius, height] = [finite(solid.radius), finite(solid.height)];
      if (radius && height && radius > 0 && height > 0) solids.push({ type: 'cylinder', x, y, z, radius, height });
    } else if (solid?.type === 'sphere') {
      const radius = finite(solid.radius);
      if (radius && radius > 0) solids.push({ type: 'sphere', x, y, z, radius });
    }
  }
  if (!solids.length) return null;
  return { solids, ...(typeof raw.summary === 'string' ? { summary: raw.summary } : {}) };
}

/* ---------- evaluation ---------- */

function round(value: number): number {
  return Math.round(value * 1000) / 1000;
}

/**
 * Emit a DXF for a profile.
 *
 * ENTITIES-only, which is the subset every reader accepts and the subset the
 * canvas draws back — a header full of unused tables would only be text nobody
 * reads. The outline is written as a CLOSED polyline so the part is a region and
 * not a stray path.
 */
export function dxfFromProfile(spec: CadProfileSpec): string {
  const tokens: string[] = ['0', 'SECTION', '2', 'ENTITIES'];
  tokens.push('0', 'LWPOLYLINE', '8', 'PROFILE', '90', String(spec.outline.length), '70', '1');
  for (const point of spec.outline) tokens.push('10', String(round(point.x)), '20', String(round(point.y)));
  for (const hole of spec.holes ?? []) {
    tokens.push('0', 'CIRCLE', '8', 'HOLES', '10', String(round(hole.x)), '20', String(round(hole.y)), '40', String(round(hole.r)));
  }
  for (const line of spec.lines ?? []) {
    tokens.push('0', 'LINE', '8', 'CONSTRUCTION',
      '10', String(round(line.x1)), '20', String(round(line.y1)),
      '11', String(round(line.x2)), '21', String(round(line.y2)));
  }
  tokens.push('0', 'ENDSEC', '0', 'EOF', '');
  return tokens.join('\n');
}

type Vertex = readonly [number, number, number];

function facet(a: Vertex, b: Vertex, c: Vertex): string | null {
  const u = [b[0] - a[0], b[1] - a[1], b[2] - a[2]] as const;
  const v = [c[0] - a[0], c[1] - a[1], c[2] - a[2]] as const;
  const cross = [
    u[1] * v[2] - u[2] * v[1],
    u[2] * v[0] - u[0] * v[2],
    u[0] * v[1] - u[1] * v[0],
  ] as const;
  const length = Math.hypot(cross[0], cross[1], cross[2]);
  // A degenerate triangle has no normal and no area; writing it would make the
  // solid non-manifold for the sake of a face nobody can see.
  if (!Number.isFinite(length) || length < 1e-9) return null;
  const normal = cross.map((component) => round(component / length)).join(' ');
  const vertex = (point: Vertex) => `vertex ${round(point[0])} ${round(point[1])} ${round(point[2])}`;
  return `facet normal ${normal}\nouter loop\n${vertex(a)}\n${vertex(b)}\n${vertex(c)}\nendloop\nendfacet`;
}

function quad(a: Vertex, b: Vertex, c: Vertex, d: Vertex): (string | null)[] {
  return [facet(a, b, c), facet(a, c, d)];
}

/** Tessellate one primitive into outward-facing triangles. */
export function tessellateSolid(solid: SolidSpec): (string | null)[] {
  if (solid.type === 'box') {
    const [hw, hd, hh] = [solid.width / 2, solid.depth / 2, solid.height / 2];
    const corner = (sx: number, sy: number, sz: number): Vertex =>
      [solid.x + sx * hw, solid.y + sy * hd, solid.z + sz * hh];
    return [
      ...quad(corner(-1, -1, -1), corner(-1, 1, -1), corner(1, 1, -1), corner(1, -1, -1)),
      ...quad(corner(-1, -1, 1), corner(1, -1, 1), corner(1, 1, 1), corner(-1, 1, 1)),
      ...quad(corner(-1, -1, -1), corner(1, -1, -1), corner(1, -1, 1), corner(-1, -1, 1)),
      ...quad(corner(1, -1, -1), corner(1, 1, -1), corner(1, 1, 1), corner(1, -1, 1)),
      ...quad(corner(1, 1, -1), corner(-1, 1, -1), corner(-1, 1, 1), corner(1, 1, 1)),
      ...quad(corner(-1, 1, -1), corner(-1, -1, -1), corner(-1, -1, 1), corner(-1, 1, 1)),
    ];
  }
  if (solid.type === 'cylinder') {
    const bottom = solid.z - solid.height / 2;
    const top = solid.z + solid.height / 2;
    const ring = (level: number) => Array.from({ length: ARC_SEGMENTS }, (_, step): Vertex => {
      const angle = (step / ARC_SEGMENTS) * Math.PI * 2;
      return [solid.x + Math.cos(angle) * solid.radius, solid.y + Math.sin(angle) * solid.radius, level];
    });
    const lower = ring(bottom);
    const upper = ring(top);
    const faces: (string | null)[] = [];
    for (let step = 0; step < ARC_SEGMENTS; step += 1) {
      const next = (step + 1) % ARC_SEGMENTS;
      faces.push(...quad(lower[step]!, lower[next]!, upper[next]!, upper[step]!));
      faces.push(facet([solid.x, solid.y, bottom], lower[next]!, lower[step]!));
      faces.push(facet([solid.x, solid.y, top], upper[step]!, upper[next]!));
    }
    return faces;
  }
  // A UV sphere: the poles collapse to single points, and the degenerate slivers
  // that produces are dropped by `facet` rather than written out as bad faces.
  const point = (band: number, step: number): Vertex => {
    const phi = (band / SPHERE_BANDS) * Math.PI;
    const theta = (step / ARC_SEGMENTS) * Math.PI * 2;
    return [
      solid.x + Math.sin(phi) * Math.cos(theta) * solid.radius,
      solid.y + Math.sin(phi) * Math.sin(theta) * solid.radius,
      solid.z + Math.cos(phi) * solid.radius,
    ];
  };
  const faces: (string | null)[] = [];
  for (let band = 0; band < SPHERE_BANDS; band += 1) {
    for (let step = 0; step < ARC_SEGMENTS; step += 1) {
      const next = (step + 1) % ARC_SEGMENTS;
      faces.push(...quad(point(band, step), point(band, next), point(band + 1, next), point(band + 1, step)));
    }
  }
  return faces;
}

/** Emit an ASCII STL for a solid model. */
export function stlFromSolids(name: string, spec: Model3dSpec): string {
  const safeName = name.replace(/[^\w-]+/g, '_').slice(0, 60) || 'model';
  const facets = spec.solids.flatMap(tessellateSolid).filter((face): face is string => face !== null);
  return `solid ${safeName}\n${facets.join('\n')}\nendsolid ${safeName}`;
}

/** How many triangles a spec actually produced — the honest validation number. */
export function facetCount(spec: Model3dSpec): number {
  return spec.solids.flatMap(tessellateSolid).filter(Boolean).length;
}
