ALTER TABLE coderclaw_instances
  ADD COLUMN IF NOT EXISTS machine_name VARCHAR(255),
  ADD COLUMN IF NOT EXISTS machine_ip VARCHAR(64),
  ADD COLUMN IF NOT EXISTS root_install_directory TEXT,
  ADD COLUMN IF NOT EXISTS workspace_directory TEXT,
  ADD COLUMN IF NOT EXISTS gateway_port INTEGER,
  ADD COLUMN IF NOT EXISTS relay_port INTEGER,
  ADD COLUMN IF NOT EXISTS tunnel_url VARCHAR(500),
  ADD COLUMN IF NOT EXISTS tunnel_status VARCHAR(64),
  ADD COLUMN IF NOT EXISTS network_metadata TEXT,
  ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP NOT NULL DEFAULT NOW();
