-- WebAuthn / passkeys — a second authentication factor that is also a first one.
--
-- ── WHY THIS AND NOT MORE MFA ───────────────────────────────────────────────
-- The platform already has TOTP MFA (0010) and OAuth + magic link (0034). What
-- none of those give you is a credential that CANNOT be phished: a TOTP code can
-- be read aloud to an attacker on the phone, a magic link can be forwarded, and
-- an OAuth password can be typed into a lookalike domain. A WebAuthn assertion is
-- signed over the origin the browser actually connected to, so a credential minted
-- for this platform is inert on any other host — the phishing class does not
-- apply, rather than being mitigated.
--
-- It is also the LOGIN, not only the second step. A discoverable credential (a
-- passkey) carries the user handle, so the browser can offer an account before the
-- server knows who is asking. That is why `credential_id` is unique platform-wide
-- rather than per-user: an assertion arrives naming only the credential, and it has
-- to resolve to exactly one account for a usernameless sign-in to be possible.
--
-- This table is per-USER and carries no `tenant_id`, exactly like
-- `user_mfa_recovery_codes`. A person's authenticator is theirs across every
-- workspace they belong to; scoping a passkey to a tenant would mean re-enrolling
-- the same hardware key per workspace, which is not what a passkey is.
--
-- ── WHAT IS STORED, AND WHAT DELIBERATELY IS NOT ────────────────────────────
-- The public key only. There is no shared secret here to leak — unlike
-- `users.mfa_secret_enc`, which is sealed precisely because possession of it is
-- possession of the factor. A WebAuthn public key is public by construction, so
-- it is stored in the clear and the row needs no encryption envelope. The private
-- half never leaves the authenticator.
--
-- `sign_count` is the authenticator's own monotonic counter. Many platform
-- authenticators (every synced passkey, in practice) report 0 forever, so a
-- regression is NOT treated as fatal — it is recorded and surfaced. Refusing on a
-- regression would lock out the majority of real users to catch a cloned hardware
-- key that a synced credential cannot be anyway. See PasskeyService for the rule.
--
-- `backed_up` records whether the credential is synced to a cloud keychain. It
-- matters to an administrator deciding whether a passkey alone is sufficient: a
-- device-bound key is lost with the device, a synced one is not.

CREATE TABLE IF NOT EXISTS webauthn_credentials (
  id                serial PRIMARY KEY,
  user_id           varchar(36) NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  -- base64url of the raw credential id. Unique platform-wide: a credential id is
  -- generated by the authenticator and must resolve to exactly one account, which
  -- is what makes a usernameless (discoverable) login possible at all.
  credential_id     varchar(512) NOT NULL,
  -- base64url of the COSE_Key. Public by construction; see the header.
  public_key        text NOT NULL,
  -- COSE algorithm identifier: -7 (ES256) or -257 (RS256).
  algorithm         integer NOT NULL,
  sign_count        bigint NOT NULL DEFAULT 0,
  -- Authenticator model identifier, when the authenticator discloses one.
  aaguid            varchar(64),
  -- Hints the browser uses to prompt correctly next time: usb, nfc, ble, internal, hybrid.
  transports        varchar(120),
  backup_eligible   boolean NOT NULL DEFAULT false,
  backed_up         boolean NOT NULL DEFAULT false,
  -- What the person calls this key. Theirs to set; defaulted from the aaguid.
  name              varchar(120) NOT NULL DEFAULT 'Passkey',
  -- Recorded, never enforced. A regression is evidence, not a verdict — see header.
  last_sign_count_regressed_at timestamp,
  last_used_at      timestamp,
  created_at        timestamp NOT NULL DEFAULT now(),
  updated_at        timestamp NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_webauthn_credentials_credential
  ON webauthn_credentials (credential_id);
CREATE INDEX IF NOT EXISTS idx_webauthn_credentials_user
  ON webauthn_credentials (user_id, created_at);

-- The challenge half of this feature needs NO new table. `webauthn_challenges`
-- already exists — migration 0428 created it with the PRD 20 governance domain
-- (id, tenant_id, user_ref, purpose, challenge, rp_id, consumed_at, expires_at,
-- ip_address), declared in schema/governance.ts and registered to the Security
-- seat, and it was built for exactly this: its own comment says consumption has to
-- be a transactional UPDATE because a replayed challenge is an authentication
-- bypass. It had no writer until now. A second challenge table would have been the
-- `finops_soc_controls` collision again, so this migration adds only the
-- credential store and PasskeyService writes the existing challenge rows.
