// Keep this list aligned with api/src/application/llm/aiUseCases.ts.
export const AI_USE_CASES = [
  'ide.chat',
  'ide.code_complete',
  'training.dataset_generate',
  'training.dataset_evaluate',
  'agent.inference',
  'coder.code',
  'coder.review',
  'coder.test',
  'coder.debug',
  'coder.refactor',
  'coder.document',
  'coder.architect',
  'coach.chat',
  'coach.insight',
  'coach.classify',
  'studio.compose',
  'studio.script',
  'studio.brief',
  'pitch_deck.generate',
  'investor.update',
  'ask.general',
  'tool.classify_email',
  'tool.categorize_expense',
  'tool.contract_analyze',
  'tool.competitor_scan',
  'tool.feature_score',
  'tool.market_research',
  'tool.health_score',
  'tool.journey_insight',
  'vision.describe',
  'ocr.extract',
  'embed.text',
  'match',
  'match_tailor',
  'match_insights',
  'resume_roast',
  'skill_extract',
  'job_parser',
  'autofill',
  'article_writer',
  'studio_script',
  'studio_edit_script',
  'studio_misc',
  'linkedin_post',
  'interview_questions',
  'interview_analyze',
  'chat',
  'career',
  'discovery',
  'dashboard_summary',
] as const;

export type AIUseCase = (typeof AI_USE_CASES)[number];

export function isAIUseCase(value: string): value is AIUseCase {
  return (AI_USE_CASES as readonly string[]).includes(value);
}
