export const browserCoreExamples = [
  "builderforce browser status",
  "builderforce browser start",
  "builderforce browser stop",
  "builderforce browser tabs",
  "builderforce browser open https://example.com",
  "builderforce browser focus abcd1234",
  "builderforce browser close abcd1234",
  "builderforce browser screenshot",
  "builderforce browser screenshot --full-page",
  "builderforce browser screenshot --ref 12",
  "builderforce browser snapshot",
  "builderforce browser snapshot --format aria --limit 200",
  "builderforce browser snapshot --efficient",
  "builderforce browser snapshot --labels",
];

export const browserActionExamples = [
  "builderforce browser navigate https://example.com",
  "builderforce browser resize 1280 720",
  "builderforce browser click 12 --double",
  'builderforce browser type 23 "hello" --submit',
  "builderforce browser press Enter",
  "builderforce browser hover 44",
  "builderforce browser drag 10 11",
  "builderforce browser select 9 OptionA OptionB",
  "builderforce browser upload /tmp/builderforce/uploads/file.pdf",
  'builderforce browser fill --fields \'[{"ref":"1","value":"Ada"}]\'',
  "builderforce browser dialog --accept",
  'builderforce browser wait --text "Done"',
  "builderforce browser evaluate --fn '(el) => el.textContent' --ref 7",
  "builderforce browser console --level error",
  "builderforce browser pdf",
];
