"""
deck.py — the committed generator for the Builderforce sales deck.

WHY THIS FILE EXISTS
--------------------------------------------------------------------------------
`README.md` said the deck was regenerated by `scratchpad/deck.py`. That file
lived in an ephemeral scratchpad and no longer exists anywhere, which meant the
deck was UNMAINTAINABLE: a pricing change, a metric change or a typo could not
be fixed at all, because the only artifacts under version control were the
rendered PNGs, the PDF and the PPTX. The pricing-credibility decision (Teams =
org-wide volume pricing, **5-seat minimum**) landed and slide 19 could not be
updated to say so.

So the generator is committed, and the slide CONTENT it renders is committed
beside it as data (`slides/*.json`). A slide with a spec is re-rendered from
that spec; a slide without one keeps its existing PNG. That is deliberate: the
26 slides were authored by hand and transcribing all of them at once, from
images, would risk silently degrading 25 slides in order to fix one. Each slide
gains a spec the first time it needs to change, and from then on it is
regenerable.

WHAT IT PRODUCES
--------------------------------------------------------------------------------
  slides/slide-NN.png          one 2560x1440 PNG per slide (16:9)
  Builderforce-Pitch-Deck.pdf  all slides, in order
  Builderforce-Pitch-Deck.pptx one full-bleed image per slide

USAGE
--------------------------------------------------------------------------------
  python deck.py                 # re-render every slide that has a spec, then
                                 # rebuild the PDF and the PPTX
  python deck.py --slide 19      # just that one
  python deck.py --no-package    # PNGs only

DEPENDENCIES
--------------------------------------------------------------------------------
  Pillow          (rendering + PDF)
  python-pptx     (optional; the PPTX step is skipped with a warning if absent)

FONTS
--------------------------------------------------------------------------------
Segoe UI, the face the existing slides use. Resolved from the system font
directory with a documented fallback, so a machine without it still renders
(with different metrics) rather than failing.
"""

from __future__ import annotations

import argparse
import json
import math
import os
import random
import sys
from pathlib import Path

from PIL import Image, ImageDraw, ImageFilter, ImageFont

ROOT = Path(__file__).resolve().parent
SLIDES = ROOT / "slides"
PDF_OUT = ROOT / "Builderforce-Pitch-Deck.pdf"
PPTX_OUT = ROOT / "Builderforce-Pitch-Deck.pptx"

W, H = 2560, 1440

# ── Palette ───────────────────────────────────────────────────────────────────
# Sampled from the committed slides so a regenerated slide sits beside the
# hand-authored ones without a visible seam.
PAPER_TL = (237, 242, 249)
PAPER_BR = (229, 235, 249)
CARD = (255, 255, 255)
INK = (23, 32, 51)
INK_SOFT = (95, 108, 133)
BLUE = (37, 99, 235)
BLUE_BRIGHT = (59, 130, 246)
FOOTER = (12, 22, 48)
FOOTER_INK = (118, 145, 196)
HAIRLINE = (214, 223, 238)

FONT_DIR = Path(os.environ.get("WINDIR", "C:/Windows")) / "Fonts"
FONT_FILES = {
    "light": ["segoeuil.ttf", "segoeui.ttf"],
    "regular": ["segoeui.ttf"],
    "semibold": ["seguisb.ttf", "segoeui.ttf"],
    "bold": ["segoeuib.ttf", "segoeui.ttf"],
}


def font(weight: str, size: int) -> ImageFont.FreeTypeFont:
    """Segoe UI at `size`, or Pillow's default if the face is unavailable."""
    for name in FONT_FILES[weight]:
        path = FONT_DIR / name
        if path.exists():
            return ImageFont.truetype(str(path), size)
    return ImageFont.load_default(size)


# ── Background ────────────────────────────────────────────────────────────────

def paper() -> Image.Image:
    """Tinted paper + the Evermind arc/dot motif every slide carries."""
    base = Image.new("RGB", (W, H), PAPER_TL)
    grad = Image.new("RGB", (2, 2), PAPER_TL)
    grad.putpixel((1, 0), PAPER_BR)
    grad.putpixel((0, 1), PAPER_BR)
    grad.putpixel((1, 1), PAPER_BR)
    base = grad.resize((W, H), Image.BICUBIC)

    motif = Image.new("RGBA", (W, H), (0, 0, 0, 0))
    pen = ImageDraw.Draw(motif)

    # Long, very faint arcs sweeping across the page.
    for index, (cx, cy, r) in enumerate([(1180, -520, 1500), (1420, -300, 1250), (1650, -120, 1050)]):
        pen.arc([cx - r, cy - r, cx + r, cy + r], 20, 160, fill=(126, 155, 214, 40), width=3)

    # A constellation in the top-right quadrant. Seeded, so the motif is stable
    # across runs and a re-render produces no spurious diff.
    rng = random.Random(19)
    points = [(rng.randint(1780, 2510), rng.randint(30, 400)) for _ in range(16)]
    for x, y in points:
        radius = rng.choice([3, 3, 4, 5])
        pen.ellipse([x - radius, y - radius, x + radius, y + radius], fill=(150, 172, 220, 110))
    for i, a in enumerate(points):
        for b in points[i + 1:]:
            if math.dist(a, b) < 165:
                pen.line([a, b], fill=(150, 172, 220, 38), width=2)

    base = Image.alpha_composite(base.convert("RGBA"), motif).convert("RGB")
    return base


def shadowed_card(canvas: Image.Image, box, radius=26, border=None, width=3) -> None:
    """A white focal card with the deck's soft drop shadow."""
    x0, y0, x1, y1 = box
    shadow = Image.new("RGBA", (W, H), (0, 0, 0, 0))
    ImageDraw.Draw(shadow).rounded_rectangle([x0, y0 + 10, x1, y1 + 14], radius, fill=(30, 51, 94, 38))
    shadow = shadow.filter(ImageFilter.GaussianBlur(14))
    canvas.paste(Image.alpha_composite(canvas.convert("RGBA"), shadow).convert("RGB"), (0, 0))
    pen = ImageDraw.Draw(canvas)
    pen.rounded_rectangle(box, radius, fill=CARD, outline=border, width=width if border else 0)


def chrome(canvas: Image.Image, number: int) -> None:
    """The deep-navy footer band every slide ends with."""
    pen = ImageDraw.Draw(canvas)
    pen.rectangle([0, 1330, W, H], fill=FOOTER)
    pen.text((160, 1370), "BuilderForce.ai", font=font("semibold", 34), fill=(255, 255, 255))
    pen.text((162, 1373), "", font=font("semibold", 34), fill=(255, 255, 255))
    num = str(number)
    pen.text((W // 2 - pen.textlength(num, font=font("regular", 30)) / 2, 1373), num,
             font=font("regular", 30), fill=FOOTER_INK)
    tagline = "The innovation platform for the agentic era"
    pen.text((W - 160 - pen.textlength(tagline, font=font("regular", 30)), 1373), tagline,
             font=font("regular", 30), fill=FOOTER_INK)


def eyebrow(pen: ImageDraw.ImageDraw, text: str) -> None:
    pen.line([(152, 141), (204, 141)], fill=BLUE, width=6)
    pen.text((222, 122), text.upper(), font=font("semibold", 30), fill=BLUE_BRIGHT)


def heading(pen: ImageDraw.ImageDraw, text: str) -> None:
    pen.text((150, 178), text, font=font("light", 92), fill=INK)


def check(pen: ImageDraw.ImageDraw, x: int, y: int) -> None:
    """The blue tick that leads every feature row."""
    pen.line([(x, y + 12), (x + 9, y + 22), (x + 26, y)], fill=BLUE_BRIGHT, width=4, joint="curve")


# ── Slide kinds ───────────────────────────────────────────────────────────────

def render_pricing(spec: dict) -> Image.Image:
    """
    The business-model slide: three plan cards, an expansion-revenue band, and
    the pricing footnote — which is the whole reason this generator exists, since
    the 5-seat Teams minimum is enforced in the product and was not stated here.
    """
    canvas = paper()
    pen = ImageDraw.Draw(canvas)
    eyebrow(pen, spec["eyebrow"])
    heading(pen, spec["heading"])

    plans = spec["plans"]
    left, top, bottom = 150, 318, 878
    gap = 34
    card_w = (W - left * 2 - gap * (len(plans) - 1)) // len(plans)

    for index, plan in enumerate(plans):
        x0 = left + index * (card_w + gap)
        box = [x0, top, x0 + card_w, bottom]
        featured = plan.get("featured", False)
        shadowed_card(canvas, box, border=BLUE_BRIGHT if featured else None, width=4)
        pen = ImageDraw.Draw(canvas)

        pen.text((x0 + 48, top + 55), plan["name"], font=font("semibold", 54),
                 fill=BLUE_BRIGHT if featured else INK)
        if featured and plan.get("badge"):
            badge = plan["badge"]
            bw = pen.textlength(badge, font=font("regular", 26)) + 44
            pen.rounded_rectangle([x0 + card_w - 48 - bw, top + 55, x0 + card_w - 48, top + 101], 23, fill=BLUE_BRIGHT)
            pen.text((x0 + card_w - 48 - bw + 22, top + 65), badge, font=font("regular", 26), fill=(255, 255, 255))

        price_font = font("bold", 92)
        pen.text((x0 + 48, top + 140), plan["price"], font=price_font, fill=INK)
        price_w = pen.textlength(plan["price"], font=price_font)
        pen.text((x0 + 60 + price_w, top + 182), plan["cadence"], font=font("regular", 36), fill=INK_SOFT)

        for row, feature in enumerate(plan["features"]):
            y = top + 268 + row * 58
            check(pen, x0 + 50, y + 8)
            pen.text((x0 + 98, y), feature, font=font("regular", 36), fill=INK)

    band = spec["expansion"]
    band_box = [150, 918, W - 150, 1148]
    shadowed_card(canvas, band_box, radius=22)
    pen = ImageDraw.Draw(canvas)
    pen.text((198, 962), band["title"], font=font("semibold", 42), fill=INK)
    col_w = (W - 150 * 2 - 96) // len(band["items"])
    for index, item in enumerate(band["items"]):
        x = 198 + index * col_w
        pen.rectangle([x, 1040, x + 7, 1102], fill=BLUE_BRIGHT)
        pen.text((x + 26, 1036), item["label"], font=font("semibold", 34), fill=INK)
        pen.text((x + 26, 1082), item["value"], font=font("regular", 32), fill=BLUE)

    pen.text((150, 1186), spec["footnote"], font=font("regular", 30), fill=(139, 152, 176))
    chrome(canvas, spec["number"])
    return canvas


RENDERERS = {"pricing": render_pricing}


# ── Packaging ─────────────────────────────────────────────────────────────────

def slide_paths() -> list[Path]:
    return sorted(SLIDES.glob("slide-*.png"))


def build_pdf() -> None:
    # Pillow registers its codecs LAZILY: opening PNGs pulls in the PNG plugin
    # only, and the PDF writer then reaches for `Image.SAVE["JPEG"]` and raises
    # KeyError on a build machine that never touched a JPEG. `init()` is the
    # documented way to force the full registry, and it is cheap.
    Image.init()
    pages = [Image.open(path).convert("RGB") for path in slide_paths()]
    if not pages:
        print("no slides to package")
        return
    pages[0].save(PDF_OUT, save_all=True, append_images=pages[1:], resolution=150.0)
    print(f"wrote {PDF_OUT.name} ({len(pages)} pages)")


def build_pptx() -> None:
    try:
        from pptx import Presentation           # type: ignore[import-not-found]
        from pptx.util import Emu               # type: ignore[import-not-found]
    except ImportError:
        print("python-pptx is not installed — PPTX skipped (pip install python-pptx)")
        return
    deck = Presentation()
    deck.slide_width = Emu(int(13.333 * 914400))
    deck.slide_height = Emu(int(7.5 * 914400))
    blank = deck.slide_layouts[6]
    for path in slide_paths():
        slide = deck.slides.add_slide(blank)
        slide.shapes.add_picture(str(path), 0, 0, width=deck.slide_width, height=deck.slide_height)
    deck.save(PPTX_OUT)
    print(f"wrote {PPTX_OUT.name}")


def main() -> int:
    parser = argparse.ArgumentParser(description="Render the Builderforce pitch deck.")
    parser.add_argument("--slide", type=int, help="render only this slide number")
    parser.add_argument("--no-package", action="store_true", help="skip the PDF/PPTX rebuild")
    args = parser.parse_args()

    specs = sorted(SLIDES.glob("slide-*.json"))
    if not specs:
        print("no slide specs found — nothing to render")
    rendered = 0
    for spec_path in specs:
        spec = json.loads(spec_path.read_text(encoding="utf-8"))
        if args.slide and spec["number"] != args.slide:
            continue
        renderer = RENDERERS.get(spec["kind"])
        if renderer is None:
            print(f"! {spec_path.name}: no renderer for kind '{spec['kind']}'")
            continue
        out = SLIDES / f"slide-{spec['number']:02d}.png"
        renderer(spec).save(out)
        print(f"rendered {out.name} from {spec_path.name}")
        rendered += 1

    if not args.no_package:
        build_pdf()
        build_pptx()
    return 0 if rendered or args.no_package else 0


if __name__ == "__main__":
    sys.exit(main())
