/**
 * The `aws-lambda` hosting adapter — the same handlers, running in the
 * customer's own AWS account behind a Lambda Function URL.
 *
 * ── WHY AWS AT ALL ──────────────────────────────────────────────────────────
 * "It runs on our platform" is not an acceptable answer to a procurement
 * question. A business that has to demonstrate the system runs in ITS cloud —
 * for data residency, for an existing enterprise agreement, for a security
 * review that only knows how to audit one provider — could previously only be
 * told no. The hosting port already existed for exactly this; this is the
 * adapter it was shaped for.
 *
 * ── WHY A FUNCTION URL AND NOT API GATEWAY ──────────────────────────────────
 * A Function URL is one resource, needs no separate stage, no usage plan and no
 * second thing to misconfigure, and it hands the request through in the same
 * payload format API Gateway v2 uses — so the entrypoint below would not change
 * if a customer later fronts it with a gateway of their own.
 *
 * ── WHY AuthType: NONE ──────────────────────────────────────────────────────
 * IAM auth on the URL would be strictly worse than useless here: Twilio, Stripe
 * and Shopify cannot sign a SigV4 request, so the ONLY callers it would exclude
 * are the ones the system exists to serve. Authentication for these endpoints is
 * per-handler signature verification, which the engine performs and which no
 * amount of transport auth would replace. That is why `verify` has no default.
 */

import { BUILDERFORCE_OIDC_AUDIENCE } from '../../ide/githubOidc';
import {
  backendNameFor,
  ENGINE_FILE,
  renderHandlerEngineSource,
  requiredBackendSecrets,
} from './handlerEngineSource';
import {
  cloudSetupSteps,
  renderCollectSiteSource,
  renderNodePackageJson,
  renderReportUrlStep,
  renderStaticSource,
} from './nodeBackend';
import type { BackendHostingStrategy, MaterializeContext, MaterializeResult } from '../hostingStrategy';

export const AWS_DIR = 'aws/';
export const AWS_DEPLOY_WORKFLOW_PATH = '.github/workflows/builderforce-aws-deploy.yml';

/** CloudFormation parameter name for one backend secret. */
const parameterName = (secret: string): string =>
  secret.toLowerCase().replace(/(^|_)([a-z0-9])/g, (_m, _sep, ch: string) => ch.toUpperCase());

/**
 * The Lambda entrypoint.
 *
 * The URL is rebuilt from the `Host` header rather than taken from anything
 * AWS-shaped, because Twilio signs the URL it called byte for byte: a signature
 * computed against `https://<function-url>/sms` and verified against
 * `/2015-03-31/functions/.../invocations` fails 100% of real traffic and looks
 * exactly like a wrong auth token.
 */
function renderLambdaEntry(ctx: MaterializeContext): string {
  return `/**
 * ${ctx.projectName} — AWS Lambda entrypoint (Function URL / API Gateway v2).
 *
 * GENERATED by Builderforce. The behaviour lives in ./engine.js, shared verbatim
 * with the Cloudflare, GCP and Azure targets; this file only translates between
 * Lambda's event shape and a standard \`Request\`/\`Response\`.
 */

import { handleRequest } from './engine.js';
import { serveStatic } from './static.mjs';

/** Response bodies of these types are returned as text; everything else base64. */
const TEXTUAL = /^(text\\/|application\\/(json|xml|javascript|x-www-form-urlencoded)|image\\/svg)/i;

function toRequest(event) {
  const http = event.requestContext?.http ?? {};
  const method = (http.method ?? event.httpMethod ?? 'GET').toUpperCase();
  const headers = new Headers();
  for (const [key, value] of Object.entries(event.headers ?? {})) {
    if (typeof value === 'string') headers.set(key, value);
  }

  // The host Twilio/Stripe actually called. A proxy in front of this must
  // forward it, or every signature check below fails.
  const host = headers.get('x-forwarded-host') ?? headers.get('host') ?? 'localhost';
  const proto = headers.get('x-forwarded-proto') ?? 'https';
  const path = event.rawPath ?? event.path ?? '/';
  const query = event.rawQueryString ? \`?\${event.rawQueryString}\` : '';

  const hasBody = method !== 'GET' && method !== 'HEAD' && event.body != null;
  const body = hasBody
    ? (event.isBase64Encoded ? Buffer.from(event.body, 'base64') : event.body)
    : undefined;

  return new Request(\`\${proto}://\${host}\${path}\${query}\`, { method, headers, body });
}

async function toResult(response) {
  const headers = {};
  for (const [key, value] of response.headers.entries()) headers[key] = value;
  const contentType = headers['content-type'] ?? '';
  const buffer = Buffer.from(await response.arrayBuffer());
  const textual = TEXTUAL.test(contentType);
  return {
    statusCode: response.status,
    headers,
    body: textual ? buffer.toString('utf8') : buffer.toString('base64'),
    isBase64Encoded: !textual,
  };
}

export async function handler(event) {
  const request = toRequest(event);
  // Handlers first, then the site: a handler route is explicit and a static file
  // is the fallback, so a page can never shadow an endpoint a provider calls.
  const response = (await handleRequest(request, process.env))
    ?? (await serveStatic(new URL(request.url).pathname));
  if (!response) return { statusCode: 404, headers: { 'content-type': 'text/plain' }, body: 'Not found' };
  return toResult(response);
}
`;
}

/** The SAM template: one function, one URL, one environment variable per secret. */
function renderSamTemplate(ctx: MaterializeContext, stackName: string): string {
  const secrets = requiredBackendSecrets(ctx);
  const parameters = secrets.length
    ? secrets
        .map(
          (s) => `  ${parameterName(s)}:
    Type: String
    Default: ''
    NoEcho: true
    Description: ${s} — pushed from the repository secret of the same name.`,
        )
        .join('\n')
    : '  # (this backend needs no secrets)';

  const environment = secrets.length
    ? `      Environment:
        Variables:
${secrets.map((s) => `          ${s}: !Ref ${parameterName(s)}`).join('\n')}`
    : '';

  return `# Generated by Builderforce from this project's handlers.
#
# This stack is YOURS: it deploys into your own AWS account, bills to your
# account, and logs to your CloudWatch. Re-generating from the canvas rewrites
# src/engine.js and this file — everything else you add is preserved.
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: ${ctx.projectName} — backend handlers and site.

Parameters:
${parameters}

Resources:
  BackendFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: ${stackName}
      Runtime: nodejs20.x
      Handler: src/lambda.handler
      CodeUri: .
      MemorySize: 512
      # Under the 30s Function URL ceiling. A handler that calls a model and a
      # connector in sequence needs room; a handler that needs more than this is
      # a handler that should be answering asynchronously.
      Timeout: 29
${environment}
      FunctionUrlConfig:
        # NONE, deliberately — see the note at the top of the adapter. Twilio,
        # Stripe and Shopify cannot sign SigV4, so IAM auth here would exclude
        # only the callers this exists to serve. Every handler verifies its own
        # provider signature instead.
        AuthType: NONE

Outputs:
  BackendUrl:
    Description: Point your provider webhooks here.
    Value: !GetAtt BackendFunctionUrl.FunctionUrl
`;
}

function renderDeployWorkflow(ctx: MaterializeContext, stackName: string): string {
  const secrets = requiredBackendSecrets(ctx);

  // Overrides are assembled in the shell rather than templated into YAML so an
  // unset repository secret is SKIPPED. Passing it as an empty string would
  // overwrite a value the customer had set directly in the console.
  const overrides = secrets.length
    ? `
      - name: Build parameter overrides
        id: params
        env:
${secrets.map((n) => `          ${n}: \${{ secrets.${n} }}`).join('\n')}
        run: |
          set -euo pipefail
          OVERRIDES=""
          for NAME in ${secrets.join(' ')}; do
            VALUE="\${!NAME:-}"
            if [ -z "$VALUE" ]; then
              echo "::warning::Repository secret $NAME is not set — leaving the deployed value unchanged."
              continue
            fi
            PARAM=$(node -e "process.stdout.write(process.argv[1].toLowerCase().replace(/(^|_)([a-z0-9])/g,(m,s,c)=>c.toUpperCase()))" "$NAME")
            OVERRIDES="$OVERRIDES $PARAM=$VALUE"
          done
          echo "overrides=$OVERRIDES" >> "$GITHUB_OUTPUT"
`
    : '';

  return `# Managed by Builderforce — deploys this project's backend and site to YOUR
# AWS account on every push to main.
#
# Authentication, in order of preference:
#   AWS_ROLE_ARN                              — an IAM role trusting GitHub's OIDC
#                                               provider. No long-lived key in your
#                                               repository; use this if you can.
#   AWS_ACCESS_KEY_ID / AWS_SECRET_ACCESS_KEY — the fallback.
# Either way set AWS_REGION.
#
# Backend secrets, pushed into the function as environment variables:
${secrets.map((n) => `#   ${n}`).join('\n') || '#   (none)'}
name: Deploy backend to AWS

on:
  push:
    branches: [main]
    paths:
      - 'aws/**'
      - '.github/workflows/builderforce-aws-deploy.yml'
  workflow_dispatch:

# Two deploys of the same branch must never overlap — CloudFormation rejects a
# second update while the first is in progress, and the failure looks like a
# broken template rather than a race.
concurrency:
  group: builderforce-aws-\${{ github.ref }}
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      # Mints the short-lived OIDC token used BOTH to assume the AWS role and to
      # report the deployed URL back to Builderforce.
      id-token: write
    # Lifted into env because the \`secrets\` context is NOT available in a step's
    # \`if\` — the env context is, so this is how "use the role if there is one"
    # is expressed at all.
    env:
      AWS_ROLE_ARN: \${{ secrets.AWS_ROLE_ARN }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      # The pages live in the repo, not in this directory — collected here so one
      # address serves the site and the handlers.
      - name: Collect the site
        run: node aws/collect-site.mjs

      - name: Authenticate to AWS (OIDC role)
        if: env.AWS_ROLE_ARN != ''
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: \${{ secrets.AWS_ROLE_ARN }}
          aws-region: \${{ secrets.AWS_REGION }}

      - name: Authenticate to AWS (access key)
        if: env.AWS_ROLE_ARN == ''
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: \${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: \${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: \${{ secrets.AWS_REGION }}
${overrides}
      - name: Deploy
        working-directory: aws
        run: |
          set -euo pipefail
          sam deploy \\
            --stack-name ${stackName} \\
            --resolve-s3 \\
            --no-confirm-changeset \\
            --no-fail-on-empty-changeset \\
            --capabilities CAPABILITY_IAM \\
            --region "\${{ secrets.AWS_REGION }}"${secrets.length ? ' \\\n            --parameter-overrides ${{ steps.params.outputs.overrides }}' : ''}

${renderReportUrlStep({
    apiOrigin: ctx.apiOrigin,
    audience: BUILDERFORCE_OIDC_AUDIENCE,
    routes: ctx.handlers.map((h) => ({ method: h.method, route: h.route })),
    urlExpression: `URL=$(aws cloudformation describe-stacks \\
  --stack-name ${stackName} \\
  --region "\${{ secrets.AWS_REGION }}" \\
  --query "Stacks[0].Outputs[?OutputKey=='BackendUrl'].OutputValue" \\
  --output text 2>/dev/null || true)`,
  })}`;
}

export const awsLambdaStrategy: BackendHostingStrategy = {
  key: 'aws-lambda',
  label: 'Your own AWS account (Lambda + Function URL)',
  summary:
    'The same handlers and your site, deployed by a generated Action into your own AWS account as a Lambda behind a Function URL. Your region, your logs, your bill.',
  zeroSetup: false,

  materialize(ctx: MaterializeContext): MaterializeResult {
    const stackName = backendNameFor(ctx);
    return {
      files: {
        [`${AWS_DIR}template.yaml`]: renderSamTemplate(ctx, stackName),
        [`${AWS_DIR}package.json`]: renderNodePackageJson(stackName),
        [`${AWS_DIR}src/${ENGINE_FILE}`]: renderHandlerEngineSource(ctx),
        [`${AWS_DIR}src/static.mjs`]: renderStaticSource(),
        [`${AWS_DIR}src/lambda.mjs`]: renderLambdaEntry(ctx),
        [`${AWS_DIR}collect-site.mjs`]: renderCollectSiteSource('aws'),
        [AWS_DEPLOY_WORKFLOW_PATH]: renderDeployWorkflow(ctx, stackName),
      },
      setupSteps: cloudSetupSteps(ctx, {
        cloud: 'AWS',
        dir: AWS_DIR,
        credentials: ['AWS_REGION', 'AWS_ROLE_ARN (or AWS_ACCESS_KEY_ID + AWS_SECRET_ACCESS_KEY)'],
        credentialUrl: 'https://console.aws.amazon.com/iam/home#/roles',
        credentialDetail:
          'The generated Action deploys with CloudFormation, so it needs permission to create a Lambda, a Function URL and the stack itself. An IAM role that trusts GitHub\'s OIDC provider is the better credential — it stores no long-lived key in your repository — and an access key pair works if you cannot set one up.',
      }),
      // Unknown until the first deploy prints it; the Action reports it back.
      webhookBaseUrl: null,
    };
  },
};
