/**
 * The `azure-functions` hosting adapter — the same handlers, running in the
 * customer's own Azure subscription on a Function App.
 *
 * ── WHY routePrefix IS EMPTIED ──────────────────────────────────────────────
 * Azure Functions serves every HTTP function under `/api` by default. A project
 * whose handlers claim `/sms` and `/voice` would answer on `/api/sms` and
 * `/api/voice`, which means the URL a provider was told to call 404s and the
 * cause is a default nobody typed. `host.json` sets `routePrefix` to empty so
 * the deployed routes are the routes in the spec — the same ones every other
 * target serves.
 *
 * ── WHY authLevel IS anonymous ──────────────────────────────────────────────
 * A function key would exclude only the callers this exists to serve: Twilio,
 * Stripe and Shopify sign their requests their own way and cannot append an
 * Azure key. Authentication is per-handler signature verification, performed by
 * the engine, which is why `verify` has no default.
 */

import { BUILDERFORCE_OIDC_AUDIENCE } from '../../ide/githubOidc';
import {
  backendNameFor,
  ENGINE_FILE,
  renderHandlerEngineSource,
  requiredBackendSecrets,
} from './handlerEngineSource';
import {
  cloudSetupSteps,
  renderCollectSiteSource,
  renderNodePackageJson,
  renderReportUrlStep,
  renderStaticSource,
} from './nodeBackend';
import type { BackendHostingStrategy, MaterializeContext, MaterializeResult } from '../hostingStrategy';

export const AZURE_DIR = 'azure/';
export const AZURE_DEPLOY_WORKFLOW_PATH = '.github/workflows/builderforce-azure-deploy.yml';

function renderFunctionEntry(ctx: MaterializeContext): string {
  return `/**
 * ${ctx.projectName} — Azure Functions entrypoint (Node v4 programming model).
 *
 * GENERATED by Builderforce. The behaviour lives in ../engine.js, shared verbatim
 * with the Cloudflare, AWS and GCP targets; this file only translates between
 * Azure's HttpRequest and a standard \`Request\`/\`Response\`.
 */

import { app } from '@azure/functions';
import { handleRequest } from '../engine.js';
import { serveStatic } from '../static.mjs';

async function toRequest(request) {
  const method = request.method.toUpperCase();
  const body = method === 'GET' || method === 'HEAD' ? undefined : await request.text();
  // \`request.url\` is the address the caller used, including the public host —
  // which is what Twilio signed, so it must be passed through unmodified.
  return new Request(request.url, { method, headers: request.headers, body });
}

async function toResult(response) {
  const headers = {};
  for (const [key, value] of response.headers.entries()) headers[key] = value;
  return {
    status: response.status,
    headers,
    body: Buffer.from(await response.arrayBuffer()),
  };
}

app.http('backend', {
  // Every method a handler spec can claim, plus OPTIONS so a browser preflight
  // reaches the engine's CORS answer instead of Azure's 404.
  methods: ['GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'HEAD', 'OPTIONS'],
  authLevel: 'anonymous',
  // One function for every path — the engine already owns routing, and a
  // per-handler function would be a second router to keep in step with it.
  route: '{*path}',
  handler: async (request, context) => {
    try {
      const req = await toRequest(request);
      // Handlers first, then the site: a handler route is explicit and a static
      // file is the fallback, so a page can never shadow an endpoint a provider
      // calls.
      const response = (await handleRequest(req, process.env))
        ?? (await serveStatic(new URL(req.url).pathname));
      if (!response) return { status: 404, body: 'Not found' };
      return toResult(response);
    } catch (error) {
      // A thrown request must still answer: an unhandled rejection makes Twilio
      // retry and Stripe re-deliver, which is worse than one clear 500.
      context.error('request failed', error);
      return { status: 500, body: 'Internal error' };
    }
  },
});
`;
}

function renderHostJson(): string {
  return `{
  "version": "2.0",
  "logging": {
    "applicationInsights": {
      "samplingSettings": { "isEnabled": true, "excludedTypes": "Request" }
    }
  },
  "extensionBundle": {
    "id": "Microsoft.Azure.Functions.ExtensionBundle",
    "version": "[4.*, 5.0.0)"
  },
  "extensions": {
    "http": {
      "routePrefix": ""
    }
  }
}
`;
}

function renderDeployWorkflow(ctx: MaterializeContext): string {
  const secrets = requiredBackendSecrets(ctx);

  // Assembled in the shell so an unset repository secret is SKIPPED rather than
  // pushed empty. `az` takes settings as repeated NAME=VALUE arguments, so each
  // is appended to an array rather than joined into one delimited string.
  const appSettings = secrets.length
    ? `
      - name: Push the backend secrets as app settings
        env:
${secrets.map((n) => `          ${n}: \${{ secrets.${n} }}`).join('\n')}
        run: |
          set -euo pipefail
          ARGS=()
          for NAME in ${secrets.join(' ')}; do
            VALUE="\${!NAME:-}"
            if [ -z "$VALUE" ]; then
              echo "::warning::Repository secret $NAME is not set — leaving the deployed value unchanged."
              continue
            fi
            ARGS+=("$NAME=$VALUE")
          done
          if [ \${#ARGS[@]} -gt 0 ]; then
            az functionapp config appsettings set \\
              --name "\${{ secrets.AZURE_FUNCTIONAPP_NAME }}" \\
              --resource-group "\${{ secrets.AZURE_RESOURCE_GROUP }}" \\
              --settings "\${ARGS[@]}" \\
              --output none
          fi
`
    : '';

  return `# Managed by Builderforce — deploys this project's backend and site to YOUR
# Azure subscription on every push to main.
#
# Set these repository secrets (Settings → Secrets and variables → Actions):
#   AZURE_CREDENTIALS         — output of \`az ad sp create-for-rbac --sdk-auth\`
#   AZURE_FUNCTIONAPP_NAME    — an existing Function App (Node 20, Linux)
#   AZURE_RESOURCE_GROUP      — the group it lives in
#
# The Function App has to exist first: unlike Lambda and Cloud Run, Azure has no
# "deploy creates the host" path that does not also need a storage account and a
# plan, and inventing those on your behalf is not a decision a generated workflow
# should make about your subscription.
#
# Backend secrets, pushed onto the app as application settings:
${secrets.map((n) => `#   ${n}`).join('\n') || '#   (none)'}
name: Deploy backend to Azure

on:
  push:
    branches: [main]
    paths:
      - 'azure/**'
      - '.github/workflows/builderforce-azure-deploy.yml'
  workflow_dispatch:

# Two deploys of the same branch must never overlap — the second would race the
# first's swap and could leave the app serving a half-replaced package.
concurrency:
  group: builderforce-azure-\${{ github.ref }}
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      # Mints the short-lived OIDC token used to report the deployed URL back to
      # Builderforce. No secret of ours is stored in this repo.
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      # The pages live in the repo, not in this directory — collected here so one
      # address serves the site and the handlers.
      - name: Collect the site
        run: node azure/collect-site.mjs

      # The ONLY dependency in any generated backend: the Node v4 programming
      # model is a real package and there is no dependency-free way to register
      # a function with it.
      - name: Install
        working-directory: azure
        run: |
          if [ -f package-lock.json ]; then npm ci; else npm install; fi

      - uses: azure/login@v2
        with:
          creds: \${{ secrets.AZURE_CREDENTIALS }}
${appSettings}
      - name: Deploy
        uses: Azure/functions-action@v1
        with:
          app-name: \${{ secrets.AZURE_FUNCTIONAPP_NAME }}
          package: azure

${renderReportUrlStep({
    apiOrigin: ctx.apiOrigin,
    audience: BUILDERFORCE_OIDC_AUDIENCE,
    routes: ctx.handlers.map((h) => ({ method: h.method, route: h.route })),
    urlExpression: `HOST=$(az functionapp show \\
  --name "\${{ secrets.AZURE_FUNCTIONAPP_NAME }}" \\
  --resource-group "\${{ secrets.AZURE_RESOURCE_GROUP }}" \\
  --query defaultHostName --output tsv 2>/dev/null || true)
URL="\${HOST:+https://$HOST}"`,
  })}`;
}

export const azureFunctionsStrategy: BackendHostingStrategy = {
  key: 'azure-functions',
  label: 'Your own Azure subscription (Function App)',
  summary:
    'The same handlers and your site, deployed by a generated Action into your own Azure subscription as a Function App. Your region, your logs, your bill.',
  zeroSetup: false,

  materialize(ctx: MaterializeContext): MaterializeResult {
    const appName = backendNameFor(ctx);
    return {
      files: {
        [`${AZURE_DIR}host.json`]: renderHostJson(),
        [`${AZURE_DIR}package.json`]: renderNodePackageJson(appName, {
          main: 'src/functions/backend.mjs',
          dependencies: { '@azure/functions': '^4.5.0' },
        }),
        [`${AZURE_DIR}${ENGINE_FILE}`]: renderHandlerEngineSource(ctx),
        [`${AZURE_DIR}static.mjs`]: renderStaticSource(),
        [`${AZURE_DIR}src/functions/backend.mjs`]: renderFunctionEntry(ctx),
        [`${AZURE_DIR}collect-site.mjs`]: renderCollectSiteSource('azure'),
        [AZURE_DEPLOY_WORKFLOW_PATH]: renderDeployWorkflow(ctx),
      },
      setupSteps: cloudSetupSteps(ctx, {
        cloud: 'Azure',
        dir: AZURE_DIR,
        credentials: ['AZURE_CREDENTIALS', 'AZURE_FUNCTIONAPP_NAME', 'AZURE_RESOURCE_GROUP'],
        credentialUrl: 'https://portal.azure.com/#create/Microsoft.FunctionApp',
        credentialDetail:
          'The generated Action deploys with the Azure CLI, so it needs a service principal scoped to the resource group — `az ad sp create-for-rbac --sdk-auth` produces the JSON that goes into AZURE_CREDENTIALS.',
        extra: [
          {
            key: 'azure-function-app',
            label: 'Create the Function App first (Node 20, Linux)',
            detail:
              'Azure has no deploy path that creates the host without also creating a storage account and a hosting plan, and choosing those on your behalf is not a decision a generated workflow should make about your subscription. Create the app, then put its name and resource group in the repository secrets.',
            url: 'https://portal.azure.com/#create/Microsoft.FunctionApp',
            blocking: true,
          },
        ],
      }),
      // Unknown until the first deploy prints it; the Action reports it back.
      webhookBaseUrl: null,
    };
  },
};
