/**
 * The `gcp-cloudrun` hosting adapter — the same handlers, running in the
 * customer's own Google Cloud project on Cloud Run.
 *
 * ── WHY CLOUD RUN AND NOT CLOUD FUNCTIONS ───────────────────────────────────
 * Cloud Run takes a container and gives back a URL, and the container is a
 * three-line Dockerfile over a plain Node server. Cloud Functions would need the
 * functions-framework as a dependency and a per-function entrypoint contract,
 * which buys nothing here: the engine is already a single request handler. It
 * also means the same image runs unchanged on any container host the customer
 * moves to later, which is the whole reason someone picks their own cloud.
 *
 * ── WHY THE URL IS REBUILT FROM FORWARDED HEADERS ───────────────────────────
 * Cloud Run terminates TLS and hands the container a plain HTTP request, so
 * `req.url` has no scheme and no public host. Twilio signs the URL it called
 * byte for byte, so a signature verified against `http://localhost:8080/sms`
 * fails every real request while looking exactly like a wrong auth token.
 */

import { BUILDERFORCE_OIDC_AUDIENCE } from '../../ide/githubOidc';
import {
  backendNameFor,
  ENGINE_FILE,
  renderHandlerEngineSource,
  requiredBackendSecrets,
} from './handlerEngineSource';
import {
  cloudSetupSteps,
  renderCollectSiteSource,
  renderNodePackageJson,
  renderReportUrlStep,
  renderStaticSource,
} from './nodeBackend';
import type { BackendHostingStrategy, MaterializeContext, MaterializeResult } from '../hostingStrategy';

export const GCP_DIR = 'gcp/';
export const GCP_DEPLOY_WORKFLOW_PATH = '.github/workflows/builderforce-gcp-deploy.yml';

function renderServer(ctx: MaterializeContext): string {
  return `/**
 * ${ctx.projectName} — Cloud Run entrypoint.
 *
 * GENERATED by Builderforce. The behaviour lives in ./engine.js, shared verbatim
 * with the Cloudflare, AWS and Azure targets; this file only translates between
 * Node's HTTP server and a standard \`Request\`/\`Response\`.
 */

import { createServer } from 'node:http';
import { Readable } from 'node:stream';
import { handleRequest } from './engine.js';
import { serveStatic } from './static.mjs';

const PORT = Number(process.env.PORT ?? 8080);

/** Collect the body before constructing the Request: the engine reads it as text
 *  and a streamed body would need duplex support the runtime does not promise. */
async function readBody(req) {
  if (req.method === 'GET' || req.method === 'HEAD') return undefined;
  const chunks = [];
  for await (const chunk of req) chunks.push(chunk);
  return chunks.length ? Buffer.concat(chunks) : undefined;
}

function toRequest(req, body) {
  const headers = new Headers();
  for (const [key, value] of Object.entries(req.headers)) {
    if (Array.isArray(value)) value.forEach((v) => headers.append(key, v));
    else if (typeof value === 'string') headers.set(key, value);
  }
  // The address the caller actually used — see the note at the top of the adapter.
  const proto = headers.get('x-forwarded-proto') ?? 'https';
  const host = headers.get('x-forwarded-host') ?? headers.get('host') ?? \`localhost:\${PORT}\`;
  return new Request(\`\${proto}://\${host}\${req.url}\`, { method: req.method, headers, body });
}

createServer(async (req, res) => {
  try {
    const body = await readBody(req);
    const request = toRequest(req, body);
    // Handlers first, then the site: a handler route is explicit and a static
    // file is the fallback, so a page can never shadow an endpoint a provider
    // calls.
    const response = (await handleRequest(request, process.env))
      ?? (await serveStatic(new URL(request.url).pathname));

    if (!response) {
      res.writeHead(404, { 'content-type': 'text/plain; charset=utf-8' });
      res.end('Not found');
      return;
    }

    const headers = {};
    for (const [key, value] of response.headers.entries()) headers[key] = value;
    res.writeHead(response.status, headers);
    if (response.body) Readable.fromWeb(response.body).pipe(res);
    else res.end();
  } catch (error) {
    // A thrown request must still answer: a 502 from a crashed process makes
    // Twilio retry and Stripe re-deliver, which is worse than one clear 500.
    console.error('request failed', error);
    res.writeHead(500, { 'content-type': 'text/plain; charset=utf-8' });
    res.end('Internal error');
  }
}).listen(PORT, () => console.log(\`listening on \${PORT}\`));
`;
}

function renderDockerfile(): string {
  return `# Generated by Builderforce.
#
# No install step and no build step: the backend has zero dependencies, so there
# is nothing for \`npm ci\` to fail at on a build machine — the single most common
# way a generated deploy breaks.
FROM node:20-slim

WORKDIR /app
COPY . .

ENV NODE_ENV=production
# Cloud Run injects PORT; this is only the local default.
ENV PORT=8080
EXPOSE 8080

CMD ["node", "src/server.mjs"]
`;
}

function renderDeployWorkflow(ctx: MaterializeContext, serviceName: string): string {
  const secrets = requiredBackendSecrets(ctx);

  // Assembled in the shell so an unset repository secret is SKIPPED rather than
  // pushed empty, and with the `^##^` delimiter because a secret may legitimately
  // contain a comma — the default separator — and would otherwise be split into
  // two half-variables.
  const envVars = secrets.length
    ? `
      - name: Build the environment variable list
        id: vars
        env:
${secrets.map((n) => `          ${n}: \${{ secrets.${n} }}`).join('\n')}
        run: |
          set -euo pipefail
          PAIRS=""
          for NAME in ${secrets.join(' ')}; do
            VALUE="\${!NAME:-}"
            if [ -z "$VALUE" ]; then
              echo "::warning::Repository secret $NAME is not set — leaving the deployed value unchanged."
              continue
            fi
            PAIRS="\${PAIRS:+$PAIRS##}$NAME=$VALUE"
          done
          if [ -n "$PAIRS" ]; then
            echo "flag=--update-env-vars=^##^$PAIRS" >> "$GITHUB_OUTPUT"
          else
            echo "flag=" >> "$GITHUB_OUTPUT"
          fi
`
    : '';

  return `# Managed by Builderforce — deploys this project's backend and site to YOUR
# Google Cloud project on every push to main.
#
# Set these repository secrets (Settings → Secrets and variables → Actions):
#   GCP_PROJECT_ID                — the project to deploy into
#   GCP_REGION                    — e.g. europe-west1
#   GCP_WORKLOAD_IDENTITY_PROVIDER — projects/…/workloadIdentityPools/…/providers/…
#   GCP_SERVICE_ACCOUNT           — the service account the provider may impersonate
#
# Workload Identity Federation rather than a service-account JSON key: the key
# would be a long-lived credential to your whole project sitting in a repository
# secret, and Google has been recommending against exactly that for years.
#
# Backend secrets, pushed onto the service as environment variables:
${secrets.map((n) => `#   ${n}`).join('\n') || '#   (none)'}
name: Deploy backend to Google Cloud

on:
  push:
    branches: [main]
    paths:
      - 'gcp/**'
      - '.github/workflows/builderforce-gcp-deploy.yml'
  workflow_dispatch:

# Cloud Run rejects a second revision while the first is still rolling out.
concurrency:
  group: builderforce-gcp-\${{ github.ref }}
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      # Mints the short-lived OIDC token used BOTH to federate into Google Cloud
      # and to report the deployed URL back to Builderforce.
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      # The pages live in the repo, not in this directory — collected here so one
      # address serves the site and the handlers.
      - name: Collect the site
        run: node gcp/collect-site.mjs

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: \${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: \${{ secrets.GCP_SERVICE_ACCOUNT }}

      - uses: google-github-actions/setup-gcloud@v2
${envVars}
      - name: Deploy
        run: |
          set -euo pipefail
          gcloud run deploy ${serviceName} \\
            --source gcp \\
            --project "\${{ secrets.GCP_PROJECT_ID }}" \\
            --region "\${{ secrets.GCP_REGION }}" \\
            --platform managed \\
            --allow-unauthenticated \\
            --quiet${secrets.length ? ' \\\n            "${{ steps.vars.outputs.flag }}"' : ''}

${renderReportUrlStep({
    apiOrigin: ctx.apiOrigin,
    audience: BUILDERFORCE_OIDC_AUDIENCE,
    routes: ctx.handlers.map((h) => ({ method: h.method, route: h.route })),
    urlExpression: `URL=$(gcloud run services describe ${serviceName} \\
  --project "\${{ secrets.GCP_PROJECT_ID }}" \\
  --region "\${{ secrets.GCP_REGION }}" \\
  --platform managed \\
  --format 'value(status.url)' 2>/dev/null || true)`,
  })}`;
}

export const gcpCloudRunStrategy: BackendHostingStrategy = {
  key: 'gcp-cloudrun',
  label: 'Your own Google Cloud project (Cloud Run)',
  summary:
    'The same handlers and your site, deployed by a generated Action into your own Google Cloud project as a Cloud Run service. Your region, your logs, your bill.',
  zeroSetup: false,

  materialize(ctx: MaterializeContext): MaterializeResult {
    const serviceName = backendNameFor(ctx);
    return {
      files: {
        [`${GCP_DIR}Dockerfile`]: renderDockerfile(),
        [`${GCP_DIR}package.json`]: renderNodePackageJson(serviceName, {
          scripts: { start: 'node src/server.mjs' },
        }),
        [`${GCP_DIR}src/${ENGINE_FILE}`]: renderHandlerEngineSource(ctx),
        [`${GCP_DIR}src/static.mjs`]: renderStaticSource(),
        [`${GCP_DIR}src/server.mjs`]: renderServer(ctx),
        [`${GCP_DIR}collect-site.mjs`]: renderCollectSiteSource('gcp'),
        [GCP_DEPLOY_WORKFLOW_PATH]: renderDeployWorkflow(ctx, serviceName),
      },
      setupSteps: cloudSetupSteps(ctx, {
        cloud: 'Google Cloud',
        dir: GCP_DIR,
        credentials: ['GCP_PROJECT_ID', 'GCP_REGION', 'GCP_WORKLOAD_IDENTITY_PROVIDER', 'GCP_SERVICE_ACCOUNT'],
        credentialUrl: 'https://console.cloud.google.com/iam-admin/workload-identity-pools',
        credentialDetail:
          'The generated Action federates into your project with Workload Identity rather than a downloaded service-account key — the key would be a long-lived credential to your whole project living in a repository secret. Create a pool and provider that trusts this repository, and a service account with the Cloud Run Admin, Cloud Build Editor, Artifact Registry Writer and Service Account User roles.',
        extra: [
          {
            key: 'gcp-apis',
            label: 'Enable the Cloud Run, Cloud Build and Artifact Registry APIs',
            detail:
              'A first deploy into a fresh project fails on the API rather than on your code, with an error that names a service you have not heard of yet. Enabling all three up front makes the first run the same as every later one.',
            url: 'https://console.cloud.google.com/apis/library',
            blocking: true,
          },
        ],
      }),
      // Unknown until the first deploy prints it; the Action reports it back.
      webhookBaseUrl: null,
    };
  },
};
