/**
 * The `github-worker` hosting adapter — the same handlers, as REAL CODE, in the
 * customer's own repo and Cloudflare account.
 *
 * ── WHY COMPILE RATHER THAN HAND OVER A TEMPLATE ────────────────────────────
 * The declarative strategy has a vocabulary ceiling. The escape hatch has to be
 * "here is a backend that does exactly what your live handlers already do, now
 * edit it" — not "here is a starter, reimplement your system in it". So the
 * handler specs are LOWERED into readable JavaScript with the same semantics as
 * `handlerRuntime.ts`. Switching strategies is then a migration, not a rewrite,
 * and a customer can diff the generated code against behaviour they already
 * tested.
 *
 * That lowering is NOT written here: it is
 * {@link renderHandlerEngineSource}, shared with the AWS, GCP and Azure
 * adapters. This file is only the part that is genuinely Cloudflare — the
 * `fetch` entrypoint, `wrangler.toml`, and an Action that deploys with the
 * customer's own API token.
 *
 * ── WHY NO FRAMEWORK ────────────────────────────────────────────────────────
 * The generated Worker has zero dependencies. `npm ci` on a runner is the single
 * most common way a generated deploy fails, and a dependency-free
 * `export default { fetch }` cannot fail that way.
 */

import { BUILDERFORCE_OIDC_AUDIENCE } from '../../ide/githubOidc';
import {
  BACKEND_HEALTH_PATH,
  backendNameFor,
  ENGINE_FILE,
  renderHandlerEngineSource,
  requiredBackendSecrets,
} from './handlerEngineSource';
import {
  missingSecretSteps,
  type BackendHostingStrategy,
  type MaterializeContext,
  type MaterializeResult,
  type SetupStep,
} from '../hostingStrategy';

/** Where the generated backend lives in the canvas — a subdirectory so it never
 *  collides with the Vite front end the same project may also hold. */
export const WORKER_DIR = 'worker/';
export const WORKER_DEPLOY_WORKFLOW_PATH = '.github/workflows/builderforce-worker-deploy.yml';

/**
 * Path the generated Worker answers its own readiness on.
 *
 * Re-exported from the shared engine rather than redeclared: the platform probes
 * this path, and a second copy of the string would silently stop matching the
 * one the generated code actually serves.
 */
export const WORKER_HEALTH_PATH = BACKEND_HEALTH_PATH;

const json = (v: unknown): string => JSON.stringify(v, null, 2);

// ---------------------------------------------------------------------------
// Generated files
// ---------------------------------------------------------------------------

function renderWranglerToml(ctx: MaterializeContext, workerName: string): string {
  return `# Generated by Builderforce from this project's handlers.
#
# This Worker is YOURS: it deploys to your own Cloudflare account, runs on your
# own logs and quotas, and can be edited freely. Re-generating from the canvas
# rewrites src/engine.js and this file — everything else you add is preserved.
name = "${workerName}"
main = "src/index.js"
compatibility_date = "2026-01-01"

# Secrets are NEVER committed. Set each one with:
#   npx wrangler secret put <NAME>
# …or let the deploy workflow push them from GitHub repository secrets.
#
# Required:
${requiredBackendSecrets(ctx).map((n) => `#   ${n}`).join('\n') || '#   (none)'}
`;
}

function renderPackageJson(workerName: string): string {
  return json({
    name: workerName,
    private: true,
    type: 'module',
    scripts: {
      deploy: 'wrangler deploy',
      dev: 'wrangler dev',
    },
    devDependencies: {
      wrangler: '^3.90.0',
    },
  });
}

/**
 * The Worker entrypoint.
 *
 * Everything it does is delegate: the engine answers a `Request` with a
 * `Response`, or with null when no handler claims the path — which is the only
 * decision left for a runtime that serves nothing but handlers.
 */
function renderWorkerEntry(ctx: MaterializeContext): string {
  return `/**
 * ${ctx.projectName} — Cloudflare Worker entrypoint.
 *
 * The behaviour lives in ./engine.js, which is shared verbatim with the AWS,
 * GCP and Azure targets. This file exists only to hand Cloudflare's \`fetch\`
 * signature to it, so moving clouds later changes THIS file and nothing else.
 */

import { handleRequest } from './engine.js';

export default {
  async fetch(request, env) {
    const response = await handleRequest(request, env);
    return response ?? new Response('Not found', { status: 404 });
  },
};
`;
}

/**
 * The deploy workflow. Unlike the static-site deploy (which authenticates to US
 * with OIDC), this one deploys to the CUSTOMER's Cloudflare account, so it needs
 * their token — there is no way around a stored credential when the destination
 * is a third party's account. It is read from a repository secret and never
 * echoed; `wrangler deploy` is the only consumer.
 */
function renderDeployWorkflow(ctx: MaterializeContext): string {
  const secrets = requiredBackendSecrets(ctx);
  const pushSecrets = secrets.length
    ? `
      # Push each backend secret into the Worker. A secret that is absent from the
      # repository is SKIPPED rather than pushed empty — an empty auth token fails
      # closed at request time with a clear error, which is far easier to diagnose
      # than a Worker that silently authenticates as nobody.
      - name: Sync Worker secrets
        working-directory: worker
        env:
          CLOUDFLARE_API_TOKEN: \${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: \${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
${secrets.map((n) => `          ${n}: \${{ secrets.${n} }}`).join('\n')}
        run: |
          set -euo pipefail
          for NAME in ${secrets.join(' ')}; do
            VALUE="\${!NAME:-}"
            if [ -z "$VALUE" ]; then
              echo "::warning::Repository secret $NAME is not set — skipping."
              continue
            fi
            printf '%s' "$VALUE" | npx wrangler secret put "$NAME"
          done
`
    : '';

  return `# Managed by Builderforce — deploys this project's backend Worker to YOUR
# Cloudflare account on every push to main.
#
# Set these repository secrets (Settings → Secrets and variables → Actions):
#   CLOUDFLARE_API_TOKEN   — an "Edit Cloudflare Workers" token
#   CLOUDFLARE_ACCOUNT_ID  — your account id
${requiredBackendSecrets(ctx).map((n) => `#   ${n}`).join('\n')}
name: Deploy backend Worker

on:
  push:
    branches: [main]
    paths:
      - 'worker/**'
      - '.github/workflows/builderforce-worker-deploy.yml'
  workflow_dispatch:

# Two deploys of the same branch must never overlap — the second would race the
# first's upload and could leave a half-replaced Worker live.
concurrency:
  group: builderforce-worker-\${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      # Mints the short-lived OIDC token used to report the deployed URL back to
      # Builderforce. No secret of ours is stored in this repo.
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install
        working-directory: worker
        run: |
          if [ -f package-lock.json ]; then npm ci; else npm install; fi
${pushSecrets}
      - name: Deploy
        working-directory: worker
        env:
          CLOUDFLARE_API_TOKEN: \${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: \${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        run: npx wrangler deploy 2>&1 | tee deploy.log

      # Report the address back so Builderforce shows YOUR Worker's URL as the
      # place to point provider webhooks at, instead of the platform ingress this
      # strategy no longer serves. Authenticated by a short-lived, audience-scoped
      # OIDC token — the repository claim is unforgeable and the repo↔project
      # binding is the authorization, exactly as in the static deploy path.
      - name: Report the deployed URL
        working-directory: worker
        env:
          BUILDERFORCE_API: ${ctx.apiOrigin}
        run: |
          set -euo pipefail
          URL=$(grep -oE 'https://[a-z0-9.-]+\\.workers\\.dev' deploy.log | tail -1 || true)

          echo "### Backend deployed\${URL:+ — $URL}" >> "$GITHUB_STEP_SUMMARY"
          if [ -z "\${URL:-}" ]; then
            echo "::warning::Could not read the deployed URL from the wrangler output."
            exit 0
          fi

${ctx.handlers.map((h) => `          echo "  ${h.method} \${URL}${h.route === '/' ? '' : h.route}" >> "$GITHUB_STEP_SUMMARY"`).join('\n') || '          true'}

          TOKEN=$(curl -sSf \\
            -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \\
            "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=${BUILDERFORCE_OIDC_AUDIENCE}" \\
            | node -e "let s='';process.stdin.on('data',d=>s+=d).on('end',()=>console.log(JSON.parse(s).value))")

          # Reporting is best-effort: the Worker is already live, and failing the
          # job here would make a successful deploy look broken.
          curl -sS -X POST "$BUILDERFORCE_API/api/deploy/worker" \\
            -H "Authorization: Bearer $TOKEN" \\
            -H "Content-Type: application/json" \\
            -d "{\\"url\\":\\"$URL\\"}" \\
            || echo "::warning::Could not report the deployed URL to Builderforce."
`;
}

export const githubWorkerStrategy: BackendHostingStrategy = {
  key: 'github-worker',
  label: 'Your own Cloudflare Worker (via GitHub)',
  summary:
    'The same handlers compiled to a real Worker in your repo, deployed by a generated Action to your own Cloudflare account. No vocabulary limits, your logs, your scale.',
  zeroSetup: false,

  materialize(ctx: MaterializeContext): MaterializeResult {
    const workerName = backendNameFor(ctx);
    const secrets = requiredBackendSecrets(ctx);

    const setupSteps: SetupStep[] = [
      ...missingSecretSteps(ctx),
      {
        key: 'cf-token',
        label: 'Add CLOUDFLARE_API_TOKEN and CLOUDFLARE_ACCOUNT_ID as repository secrets',
        detail:
          'The generated Action deploys to YOUR Cloudflare account, so it needs a token you own. Create an "Edit Cloudflare Workers" token, then add both values under Settings → Secrets and variables → Actions.',
        url: 'https://dash.cloudflare.com/profile/api-tokens',
        blocking: true,
      },
      ...(secrets.length
        ? [{
            key: 'worker-secrets',
            label: 'Add the backend secrets as repository secrets',
            detail: `The deploy workflow pushes these into the Worker: ${secrets.join(', ')}. Any that are absent are skipped with a warning rather than pushed empty.`,
            blocking: false,
          }]
        : []),
      {
        key: 'push',
        label: 'Push the generated worker/ directory',
        detail:
          'Commit the generated files to the project repo. The Action runs on push to main and prints the deployed URL — point your provider webhooks at that, not at the Builderforce ingress.',
        blocking: true,
      },
    ];

    return {
      files: {
        [`${WORKER_DIR}wrangler.toml`]: renderWranglerToml(ctx, workerName),
        [`${WORKER_DIR}package.json`]: renderPackageJson(workerName),
        [`${WORKER_DIR}src/${ENGINE_FILE}`]: renderHandlerEngineSource(ctx),
        [`${WORKER_DIR}src/index.js`]: renderWorkerEntry(ctx),
        [WORKER_DEPLOY_WORKFLOW_PATH]: renderDeployWorkflow(ctx),
      },
      setupSteps,
      // Unknown until the first deploy prints it; the Action writes it to the job
      // summary and the project's backend row records it when reported.
      webhookBaseUrl: null,
    };
  },
};
