/**
 * The parts every NODE-hosted backend target needs, written once.
 *
 * AWS Lambda, Cloud Run and Azure Functions differ in exactly three things: how
 * an HTTP request reaches the process, what deploys it, and where environment
 * values come from. Everything else — the handler engine, serving the project's
 * own site next to its API, collecting those site files at deploy time, the
 * "your secrets are missing" advice — is identical, and lives here.
 *
 * ── WHY THESE TARGETS SERVE THE SITE TOO ────────────────────────────────────
 * "Deploy it to AWS" does not mean "deploy the webhooks to AWS and leave the
 * pages on Builderforce". A proof that lives at two addresses, one of which is
 * still ours, is not the thing a customer with a procurement requirement asked
 * for. So each generated bundle serves the project's static files from `public/`
 * and falls through to them whenever no handler claims the path: one URL, whole
 * system, in their account.
 *
 * The site files are NOT copied into the canvas — they are already in the repo.
 * `collect-site.mjs` gathers them at deploy time, so there is exactly one copy
 * of every page and no chance of the deployed one going stale.
 */

import { requiredBackendSecrets } from './handlerEngineSource';
import { missingSecretSteps, type MaterializeContext, type SetupStep } from '../hostingStrategy';

/** Directories that are backend bundles or tooling, never site content. */
const NON_SITE_DIRS = ['worker', 'aws', 'gcp', 'azure', 'handlers', 'node_modules', '.git', '.github'];

/**
 * `static.mjs` — serve the collected site.
 *
 * Path traversal is checked by RESOLVING the candidate and asserting it is still
 * under `public/`, not by pattern-matching the request. `%2e%2e%2f` and a
 * symlinked directory both survive a substring check and neither survives this.
 */
export function renderStaticSource(): string {
  return `/**
 * Static file serving for the project's own site.
 *
 * GENERATED by Builderforce. The files come from \`public/\`, which
 * \`collect-site.mjs\` fills at deploy time from the repo — so the pages you
 * edit in the canvas are the pages this serves, with no second copy to go stale.
 */

import { readFile, stat } from 'node:fs/promises';
import { join, resolve, extname, sep } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = resolve(fileURLToPath(new URL('.', import.meta.url)), 'public');

const TYPES = {
  '.html': 'text/html; charset=utf-8',
  '.css': 'text/css; charset=utf-8',
  '.js': 'text/javascript; charset=utf-8',
  '.mjs': 'text/javascript; charset=utf-8',
  '.json': 'application/json; charset=utf-8',
  '.svg': 'image/svg+xml',
  '.png': 'image/png',
  '.jpg': 'image/jpeg',
  '.jpeg': 'image/jpeg',
  '.gif': 'image/gif',
  '.webp': 'image/webp',
  '.avif': 'image/avif',
  '.ico': 'image/x-icon',
  '.woff': 'font/woff',
  '.woff2': 'font/woff2',
  '.txt': 'text/plain; charset=utf-8',
  '.xml': 'application/xml; charset=utf-8',
  '.pdf': 'application/pdf',
};

async function readIfFile(path) {
  try {
    const info = await stat(path);
    if (!info.isFile()) return null;
    return await readFile(path);
  } catch {
    return null;
  }
}

/**
 * Resolve one request path to a file under \`public/\`, or null.
 *
 * The resolved path is checked against the root AFTER resolution: a decoded
 * \`..\` segment and a symlink both look harmless in the raw pathname and both
 * escape it, so the only honest check is on where the path actually landed.
 */
export async function serveStatic(pathname) {
  let decoded;
  try {
    decoded = decodeURIComponent(pathname);
  } catch {
    return null;
  }

  const candidates = decoded.endsWith('/')
    ? [join(decoded, 'index.html')]
    : [decoded, \`\${decoded}.html\`, join(decoded, 'index.html')];

  for (const candidate of candidates) {
    const target = resolve(ROOT, \`.\${candidate.startsWith('/') ? candidate : \`/\${candidate}\`}\`);
    // Inside the root, or the root itself. \`startsWith(ROOT)\` alone would also
    // admit a sibling directory whose name merely begins with it.
    if (target !== ROOT && !target.startsWith(ROOT + sep)) continue;
    const body = await readIfFile(target);
    if (!body) continue;
    return new Response(body, {
      headers: {
        'Content-Type': TYPES[extname(target).toLowerCase()] ?? 'application/octet-stream',
        // Short and revalidated: a proof is edited while someone is looking at it,
        // and a long cache on the page you just changed is indistinguishable from
        // a deploy that did not work.
        'Cache-Control': 'public, max-age=60, must-revalidate',
      },
    });
  }
  return null;
}
`;
}

/**
 * `collect-site.mjs` — gather the repo's site files into the bundle's `public/`.
 *
 * Run from the repo root by the deploy workflow, immediately before the upload,
 * so the deployed pages are whatever is on the branch rather than whatever was
 * generated when the strategy last ran.
 */
export function renderCollectSiteSource(bundleDir: string): string {
  return `/**
 * Collect this project's site files into ${bundleDir}/public.
 *
 * GENERATED by Builderforce. Run from the repository root:
 *   node ${bundleDir}/collect-site.mjs
 *
 * Everything in the repo is site content EXCEPT the backend bundles, the handler
 * specs and the usual tooling directories. That default is deliberate: a project
 * built on the canvas is a site plus handlers, and a copy list that had to be
 * maintained by hand would silently stop deploying the page you added last.
 */

import { cp, mkdir, readdir, rm } from 'node:fs/promises';
import { join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const BUNDLE = resolve(fileURLToPath(new URL('.', import.meta.url)));
const REPO = resolve(BUNDLE, '..');
const PUBLIC = join(BUNDLE, 'public');

const SKIP = new Set(${JSON.stringify(NON_SITE_DIRS)});

await rm(PUBLIC, { recursive: true, force: true });
await mkdir(PUBLIC, { recursive: true });

let copied = 0;
for (const entry of await readdir(REPO, { withFileTypes: true })) {
  if (entry.name.startsWith('.') || SKIP.has(entry.name)) continue;
  await cp(join(REPO, entry.name), join(PUBLIC, entry.name), { recursive: true });
  copied++;
}

console.log(\`collect-site: copied \${copied} entr\${copied === 1 ? 'y' : 'ies'} into \${PUBLIC}\`);
if (copied === 0) {
  // Not a failure: a backend-only project is a legitimate thing to deploy. But
  // a silent empty public/ is how "my site returns 404" becomes a mystery.
  console.warn('collect-site: no site files found — this deployment serves handlers only.');
}
`;
}

/** `package.json` for a dependency-free Node bundle. */
export function renderNodePackageJson(name: string, extra: Record<string, unknown> = {}): string {
  return JSON.stringify(
    {
      name,
      private: true,
      type: 'module',
      engines: { node: '>=20' },
      ...extra,
    },
    null,
    2,
  );
}

/**
 * The setup steps every cloud target shares: the secrets the handlers need, the
 * credential the workflow deploys with, and the push that starts it.
 *
 * Written once because the THREE clouds disagree about the name of the
 * credential and about nothing else, and three hand-written copies of this list
 * is three places for the secret list to fall out of step with the handlers.
 */
export function cloudSetupSteps(
  ctx: MaterializeContext,
  args: {
    /** Human name of the cloud, for prose. */
    cloud: string;
    /** Directory the bundle was generated into, e.g. `aws/`. */
    dir: string;
    /** Repository secrets the deploy workflow authenticates with. */
    credentials: readonly string[];
    /** Where the customer creates those credentials. */
    credentialUrl: string;
    /** What the credential is, in one clause. */
    credentialDetail: string;
    /** Steps unique to this cloud, inserted before the push step. */
    extra?: readonly SetupStep[];
  },
): SetupStep[] {
  const secrets = requiredBackendSecrets(ctx);
  return [
    ...missingSecretSteps(ctx),
    {
      key: 'cloud-credentials',
      label: `Add ${args.credentials.join(', ')} as repository secrets`,
      detail: `${args.credentialDetail} Add ${args.credentials.length === 1 ? 'it' : 'them'} under Settings → Secrets and variables → Actions. The workflow deploys to YOUR ${args.cloud} account, so the credential has to be one you own — nothing of Builderforce's is stored in your repo.`,
      url: args.credentialUrl,
      blocking: true,
    },
    ...(secrets.length
      ? [{
          key: 'cloud-secrets',
          label: 'Add the backend secrets as repository secrets',
          detail: `The deploy workflow pushes these into the running backend: ${secrets.join(', ')}. Any that are absent are skipped with a warning rather than pushed empty — an empty auth token fails closed with a clear error, which beats a backend that silently authenticates as nobody.`,
          blocking: false,
        }]
      : []),
    ...(args.extra ?? []),
    {
      key: 'push',
      label: `Push the generated ${args.dir} directory`,
      detail: `Commit the generated files to the project repo. The Action runs on push to main, deploys to ${args.cloud}, and reports the address back — point your provider webhooks at that URL, not at the Builderforce ingress. Your site is deployed alongside the handlers, so the same address serves both.`,
      blocking: true,
    },
  ];
}

/**
 * The step that reports a deployed URL back to Builderforce, as workflow YAML.
 *
 * Shared because getting it wrong is silent: without the report the platform
 * keeps showing the Builderforce ingress as the webhook address, which for a
 * self-hosted strategy is the WRONG URL, and nothing anywhere says so.
 *
 * `urlExpression` is a shell snippet that must leave the address in `$URL`.
 */
export function renderReportUrlStep(args: {
  apiOrigin: string;
  audience: string;
  urlExpression: string;
  routes: readonly { method: string; route: string }[];
  workingDirectory?: string;
}): string {
  const indent = '          ';
  return `      - name: Report the deployed URL
${args.workingDirectory ? `        working-directory: ${args.workingDirectory}\n` : ''}        env:
          BUILDERFORCE_API: ${args.apiOrigin}
        run: |
          set -euo pipefail
${args.urlExpression
    .split('\n')
    .map((line) => `${indent}${line}`)
    .join('\n')}

          # A trailing slash makes every route below it a double slash, which is a
          # different path to every provider that will call it.
          URL="\${URL%/}"
          echo "### Backend deployed\${URL:+ — $URL}" >> "$GITHUB_STEP_SUMMARY"
          if [ -z "\${URL:-}" ]; then
            echo "::warning::Could not read the deployed URL from the deploy output."
            exit 0
          fi

${args.routes.map((h) => `${indent}echo "  ${h.method} \${URL}${h.route === '/' ? '' : h.route}" >> "$GITHUB_STEP_SUMMARY"`).join('\n') || `${indent}true`}

          TOKEN=$(curl -sSf \\
            -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \\
            "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=${args.audience}" \\
            | node -e "let s='';process.stdin.on('data',d=>s+=d).on('end',()=>console.log(JSON.parse(s).value))")

          # Best-effort: the backend is already live, and failing the job here
          # would make a successful deploy look broken.
          curl -sS -X POST "$BUILDERFORCE_API/api/deploy/worker" \\
            -H "Authorization: Bearer $TOKEN" \\
            -H "Content-Type: application/json" \\
            -d "{\\"url\\":\\"$URL\\"}" \\
            || echo "::warning::Could not report the deployed URL to Builderforce."
`;
}
