import React, { useEffect, useMemo, useRef, useState } from 'react';
import {
  DEFAULT_CHAT_ACTIVITY_LABELS,
  activityIcon,
  activityTone,
  chatActivityText,
  type ChatActivityLabels,
  DEFAULT_MODEL_IDENTITY,
  displayModelName,
  parseDirectedRecipient,
  parseMessageAuthor,
  parseMessageProvenance,
  type BrainMessage,
  type BrainTraceEvent,
  type MessageProvenance,
  type ModelIdentityContext,
} from '@seanhogg/builderforce-brain-embedded';
import { Markdown } from './Markdown';
import { Avatar } from './ParticipantBadge';
import { parseAskUser, stripAskUser, QuestionCard, askUserAnchorId, DEFAULT_ASK_USER_LABELS } from './askUser';
import { buildSettledTimeline, formatDuration, formatPayload, streamingNode, type TimelineNode } from './timelineModel';

export interface BrainTimelineLabels {
  /** Shown on the live thinking node while a turn streams. */
  thinking: string;
  /** "Thought for {duration}" — must contain the literal `{duration}` token. */
  thoughtFor: string;
  you: string;
  assistant: string;
  input: string;
  output: string;
  error: string;
  loading: string;
  empty: string;
  copy: string;
  copied: string;
  /** Per-message "send this again" action — re-asks the model with the same text,
   *  from a user turn or an assistant one. */
  replay: string;
  /** Thumbs up / down on an assistant reply. */
  rateUp: string;
  rateDown: string;
  apply: string;
  createFile: string;
  /** Heading for the change preview shown on an edit_file / write_file tool step. */
  preview: string;
  /** <QuestionCard> copy (ask_user) — carried here so a host passes ONE label bundle. */
  askSubmit: string;
  askAnswered: string;
  /** Provenance chip: the badge shown when the tenant's OWN connected frontier
   *  account served the turn. */
  accountOwn: string;
  /** Provenance chip: the badge for a turn served by the shared model pool. */
  accountShared: string;
  /** Provenance chip: the badge for a shared-pool turn when the tenant HAS a
   *  connected account that wasn't used — the case worth flagging. */
  accountByoUnused: string;
  /** Provenance chip tooltip: shown on the "🧠 Evermind vN" badge when the
   *  project's own self-learning model generated this reply. */
  ranOnEvermind: string;
  /** Evermind recall step title — must contain `{count}` and `{version}`. */
  recallTitle: string;
  /** Tooltip on the recall step explaining what it means. */
  recallHint: string;
  /** Evermind learn step — the turn was contributed back. Must contain `{version}`. */
  learnTitle: string;
  /** Tooltip on the learn step. */
  learnHint: string;
  /** Evermind SKIPPED-learn step — the turn did NOT contribute, and why. Must contain
   *  `{reason}` (filled from {@link learnSkipReason}). */
  learnSkippedTitle: string;
  /** Tooltip on the skipped-learn step. */
  learnSkippedHint: string;
  /** Human phrase per skip reason, substituted into {@link learnSkippedTitle}. */
  learnSkipReason: { 'not-attached': string; 'not-seeded': string; frozen: string };
  /** Per-Evermind CONTRIBUTED line for a multi-target fan-out. Must contain `{name}`,
   *  `{projectId}`, `{version}`. */
  learnTargetContributed: string;
  /** Per-Evermind SKIPPED line for a multi-target fan-out. Must contain `{name}`,
   *  `{projectId}`, `{reason}` (filled from {@link learnSkipReason}). */
  learnTargetSkipped: string;
  /** Evermind reconcile step — the turn updated learned memories. Must contain
   *  `{count}` and `{version}`. */
  reconcileTitle: string;
  /** Tooltip on the reconcile step. */
  reconcileHint: string;
  /**
   * RUN-ACTIVITY line templates (run milestones + agent dispatch). Templates, not
   * sentences: the server records only the FACTS, and each surface composes the line in
   * its own language — which is the only way these can be localized at all, since the
   * server has no idea who will read the chat. See `chatActivity.ts` for the contract.
   */
  activity: ChatActivityLabels;
}

export const DEFAULT_TIMELINE_LABELS: BrainTimelineLabels = {
  thinking: 'Thinking…',
  thoughtFor: 'Thought for {duration}',
  you: 'You',
  assistant: 'BuilderForce',
  input: 'Input',
  output: 'Output',
  error: 'Error',
  loading: 'Loading…',
  empty: 'Ask BuilderForce to build or change something.',
  copy: 'Copy',
  copied: 'Copied',
  replay: 'Send again',
  rateUp: 'Good response',
  rateDown: 'Bad response',
  apply: 'Apply',
  createFile: 'Create file',
  preview: 'Preview',
  askSubmit: DEFAULT_ASK_USER_LABELS.askSubmit,
  askAnswered: DEFAULT_ASK_USER_LABELS.askAnswered,
  accountOwn: 'Your account',
  accountShared: 'Shared pool',
  accountByoUnused: "Your connected account wasn't used",
  ranOnEvermind: "Generated by this project's Evermind model",
  recallTitle: 'Recalled {count} memories from Evermind v{version}',
  recallHint: "This project's self-learning Evermind recalled these prior learnings and grounded the answer on them.",
  learnTitle: 'Contributed this turn to Evermind v{version}',
  learnHint: 'This turn was contributed back to the project Evermind — it will be merged into the learned model.',
  learnSkippedTitle: 'Not learned this turn — {reason}',
  learnSkippedHint: "This turn wasn't contributed to the project Evermind. “Learning — Connected” reflects the selected project's model, not whether this chat feeds it.",
  learnSkipReason: {
    'not-attached': 'this chat isn’t attached to a project',
    'not-seeded': 'this project has no Evermind model yet',
    frozen: 'this project’s Evermind is frozen (read-only)',
  },
  learnTargetContributed: 'Contributed to {name} (project #{projectId} v{version})',
  learnTargetSkipped: 'Skipped {name} (project #{projectId}) — {reason}',
  reconcileTitle: 'Reconciled {count} learned memories in Evermind v{version}',
  reconcileHint: 'The answer restated these recalled learnings, so it updates them (write-through cognition).',
  activity: DEFAULT_CHAT_ACTIVITY_LABELS,
};

/**
 * The per-reply provenance chip: what served this turn, and whose account paid for it.
 * A positive confirmation on EVERY assistant turn that the tenant is (or is not) on
 * their own connected frontier account — so "why didn't it use my paid Claude?" is
 * answered inline instead of only surfacing on an empty reply. The `shared_byo_unused`
 * state is styled as a warning because it's the one the user most wants to catch (a
 * connected account that silently wasn't used).
 *
 * WHAT it names depends on who is reading: a turn our routed pool served is named after
 * the PRODUCT ("Builderforce Free" / "Builderforce PRO") unless the viewer owns the
 * choice — see `modelIdentity.ts`. The upstream id stays on the message metadata either
 * way, so diagnostics and usage attribution are unaffected.
 *
 * The account is optional: when the gateway didn't report one the chip still names what
 * ran and simply omits the badge — attribution without a claim we can't back.
 */
function ProvenanceChip({
  prov,
  labels,
  identity,
}: {
  prov: MessageProvenance;
  labels: BrainTimelineLabels;
  identity: ModelIdentityContext;
}) {
  const unused = prov.account === 'shared_byo_unused';
  const badge = prov.account === 'own'
    ? labels.accountOwn
    : unused
      ? labels.accountByoUnused
      : prov.account === 'shared'
        ? labels.accountShared
        : null;
  const variant = prov.account === 'own'
    ? 'bf-tl__prov--own'
    : unused
      ? 'bf-tl__prov--unused'
      : 'bf-tl__prov--shared';
  // Masked viewers get the product name in the tooltip too — a vendor suffix would
  // give away exactly what the name is there to abstract.
  const name = displayModelName(prov.model, identity, { account: prov.account });
  const modelTitle = prov.vendor && name === prov.model ? `${name} · ${prov.vendor}` : name;
  return (
    <div className={`bf-tl__prov ${variant}`}>
      <span className="bf-tl__prov-model" title={modelTitle}>{name}</span>
      {badge && <span className="bf-tl__prov-badge">{badge}</span>}
      {prov.evermind ? (
        <span className="bf-tl__prov-evermind" title={labels.ranOnEvermind}>{`🧠 Evermind v${prov.evermind.version}`}</span>
      ) : null}
    </div>
  );
}

/** +1 up, -1 down, 0 = cleared. Mirrors the `llm_action_ratings.rating` domain. */
export type MessageRating = 1 | -1 | 0;

export interface BrainTimelineProps {
  messages: BrainMessage[];
  trace: BrainTraceEvent[];
  streamingText: string;
  isRunning: boolean;
  loading?: boolean;
  labels?: Partial<BrainTimelineLabels>;
  /** Who is reading — decides whether a reply's provenance chip may name the upstream
   *  model or shows the routing product instead. Omitted ⇒ masked (fail closed). */
  modelIdentity?: ModelIdentityContext;
  /** Override the assistant display name (defaults to labels.assistant). */
  assistantName?: string;
  /** Replaces the built-in empty state entirely. */
  emptyState?: React.ReactNode;
  /** Render a message's text. Defaults to the shared <Markdown>. The web app
   *  passes its richer ChatMessageBubble here so no feature is lost. */
  renderMessage?: (msg: BrainMessage, ctx: { role: 'user' | 'assistant'; text: string }) => React.ReactNode;
  /** Render the live streaming assistant bubble. Defaults to <Markdown>. */
  renderStreaming?: (text: string) => React.ReactNode;
  /** Host-specific EXTRAS on an assistant message (feedback, export, suggestions).
   *  Copy and "send again" are built in — see {@link MessageActions} — so a host never
   *  re-implements them. */
  renderAssistantActions?: (msg: BrainMessage) => React.ReactNode;
  /** Re-send a message's text as the next turn. When omitted the "send again" action
   *  hides itself, so a read-only transcript offers only copy. */
  onReplayMessage?: (msg: BrainMessage, role: 'user' | 'assistant') => void;
  /**
   * Rate an assistant reply. Wiring it renders the thumbs; omitting it hides them,
   * so a read-only transcript (or a surface with no signed-in rater) offers none.
   * The host is responsible for filing the rating against the model that served the
   * turn — see `llm_action_ratings` / `POST /api/llm/ratings`.
   */
  onRateMessage?: (msg: BrainMessage, rating: MessageRating) => void;
  /** The rating THIS viewer has already given, keyed by message id. */
  ratings?: Record<number, 1 | -1>;
  onInternalLink?: (href: string) => void;
  onApplyCode?: (code: string) => void;
  onCreateFile?: (path: string, content: string) => void;
  /** Post the user's answer to an agent's `ask_user` question as their next turn.
   *  When set, an assistant message carrying an ask-user block renders a clickable
   *  <QuestionCard>; without it the block degrades to plain text. */
  onAnswerQuestion?: (answer: string) => void;
  /** Auto-scroll to the newest node while near the bottom (default true). */
  autoScroll?: boolean;
}

function dotIcon(kind: TimelineNode['kind'], isError?: boolean): string {
  if (isError) return '✗';
  switch (kind) {
    case 'user':
      return '›';
    case 'assistant':
      return '✦';
    case 'thinking':
      return '∴';
    case 'tool':
      return '⚙';
    case 'error':
      return '✗';
    case 'recall':
    case 'learn':
    case 'reconcile':
      return '🧠';
    default:
      return '•';
  }
}

/**
 * Copy `text` to the clipboard, flashing a "Copied" confirmation.
 *
 * THE clipboard button of this package — the tool step's Input / Output / preview
 * panels wear it as a labelled chip, a message wears it as an icon. One
 * implementation, because two would drift on the confirmation timing alone.
 */
function CopyButton({ text, labels, icon = false }: { text: string; labels: BrainTimelineLabels; icon?: boolean }) {
  const [copied, setCopied] = useState(false);
  return (
    <button
      type="button"
      className={icon ? 'bf-tl__act' : 'bf-tl__copy'}
      title={copied ? labels.copied : labels.copy}
      aria-label={copied ? labels.copied : labels.copy}
      data-state={copied ? 'done' : undefined}
      onClick={(e) => {
        e.stopPropagation();
        void navigator.clipboard?.writeText(text).then(
          () => {
            setCopied(true);
            setTimeout(() => setCopied(false), 1500);
          },
          () => {},
        );
      }}
    >
      {icon ? <span aria-hidden>{copied ? '✓' : '⧉'}</span> : copied ? labels.copied : labels.copy}
    </button>
  );
}

/**
 * The action row every message carries: copy it, send it again, and — on an
 * assistant reply — say whether it was any good.
 *
 * It lives HERE rather than in each host's own action bar because all three surfaces
 * (the web Brain panel, the Canvas dock, the VS Code webview) mount this same
 * timeline — a host-side implementation would have had to be written three times and
 * would have reached only whichever surface remembered to render it. Hosts still add
 * their OWN extras through `renderAssistantActions`; those compose after these.
 *
 * "Send again" is deliberately offered on BOTH roles: replaying a user turn re-asks
 * the question, and replaying an assistant turn feeds its answer back as the next
 * prompt — which is how you ask the model to build on what it just said.
 *
 * The THUMBS moved here for the same reason, and because of what they are now for:
 * every press is filed against the model that served the turn and the MCP tool it
 * ran, so it teaches the learned router which model is good at which kind of work
 * (`llm_action_ratings`, migration 0468). While they lived in the web app's own
 * action bar, the Canvas and the editor — a large share of all model calls — could
 * not contribute a single rating.
 */
function MessageActions({
  message,
  role,
  text,
  labels,
  onReplay,
  onRate,
  rating,
}: {
  message: BrainMessage;
  role: 'user' | 'assistant';
  text: string;
  labels: BrainTimelineLabels;
  onReplay?: (msg: BrainMessage, role: 'user' | 'assistant') => void;
  onRate?: (msg: BrainMessage, rating: MessageRating) => void;
  rating?: MessageRating;
}) {
  if (!text.trim()) return null;
  // Pressing the thumb you already gave clears it — "no opinion" is the absence of
  // a rating, so it deletes the row rather than storing a third state.
  const rate = (next: 1 | -1) => (event: React.MouseEvent) => {
    event.stopPropagation();
    onRate?.(message, rating === next ? 0 : next);
  };
  return (
    <>
      <CopyButton text={text} labels={labels} icon />
      {onReplay && (
        <button
          type="button"
          className="bf-tl__act"
          title={labels.replay}
          aria-label={labels.replay}
          onClick={(e) => { e.stopPropagation(); onReplay(message, role); }}
        >
          <span aria-hidden>↻</span>
        </button>
      )}
      {onRate && role === 'assistant' && (
        <>
          <button
            type="button"
            className="bf-tl__act"
            title={labels.rateUp}
            aria-label={labels.rateUp}
            aria-pressed={rating === 1}
            data-state={rating === 1 ? 'done' : undefined}
            onClick={rate(1)}
          >
            <span aria-hidden>👍</span>
          </button>
          <button
            type="button"
            className="bf-tl__act"
            title={labels.rateDown}
            aria-label={labels.rateDown}
            aria-pressed={rating === -1}
            data-state={rating === -1 ? 'done' : undefined}
            onClick={rate(-1)}
          >
            <span aria-hidden>👎</span>
          </button>
        </>
      )}
    </>
  );
}

type ToolPreview =
  | { kind: 'edit'; path: string; oldText: string; newText: string }
  | { kind: 'write'; path: string; content: string };

/** An edit_file / write_file tool call carries the change itself in its args, so we
 *  can render a readable preview (a before/after diff for edits, the new content for
 *  writes) instead of only the raw JSON — detected structurally so it works regardless
 *  of the tool's display label. */
function toolPreview(args: unknown): ToolPreview | null {
  if (!args || typeof args !== 'object') return null;
  const a = args as Record<string, unknown>;
  const path = typeof a.path === 'string' ? a.path : '';
  if (typeof a.old_string === 'string' && typeof a.new_string === 'string') {
    return { kind: 'edit', path, oldText: a.old_string, newText: a.new_string };
  }
  if (path && typeof a.content === 'string') {
    return { kind: 'write', path, content: a.content };
  }
  return null;
}

function DiffLines({ text, sign }: { text: string; sign: '+' | '-' }) {
  const cls = sign === '+' ? 'bf-tl__diff-add' : 'bf-tl__diff-del';
  return (
    <>
      {text.split('\n').map((line, i) => (
        <div key={i} className={`bf-tl__diff-line ${cls}`}>
          <span className="bf-tl__diff-sign" aria-hidden>{sign}</span>
          <span className="bf-tl__diff-text">{line || ' '}</span>
        </div>
      ))}
    </>
  );
}

function ToolStep({
  node,
  labels,
}: {
  node: Extract<TimelineNode, { kind: 'tool' }>;
  labels: BrainTimelineLabels;
}) {
  const argsText = formatPayload(node.args);
  const resultText = formatPayload(node.result);
  const preview = toolPreview(node.args);
  return (
    <details className={`bf-tl__tool${node.isError ? ' bf-tl__tool--error' : ''}`}>
      <summary className="bf-tl__tool-head">
        <span className="bf-tl__tool-status" aria-hidden>
          {node.isError ? '✗' : '✓'}
        </span>
        <span className="bf-tl__tool-name">{node.label}</span>
        {node.durationMs != null && <span className="bf-tl__tool-dur">{formatDuration(node.durationMs)}</span>}
        <span className="bf-tl__tool-caret" aria-hidden>
          ▸
        </span>
      </summary>
      <div className="bf-tl__tool-body">
        {preview && (
          <div className="bf-tl__io">
            <div className="bf-tl__io-label">
              <span>{labels.preview}{preview.path ? ` · ${preview.path}` : ''}</span>
              <CopyButton
                text={preview.kind === 'edit' ? preview.newText : preview.content}
                labels={labels}
              />
            </div>
            {preview.kind === 'edit' ? (
              <div className="bf-tl__diff">
                <DiffLines text={preview.oldText} sign="-" />
                <DiffLines text={preview.newText} sign="+" />
              </div>
            ) : (
              <pre className="bf-tl__io-pre">
                <code>{preview.content}</code>
              </pre>
            )}
          </div>
        )}
        {argsText && (
          <div className="bf-tl__io">
            <div className="bf-tl__io-label">
              <span>{labels.input}</span>
              <CopyButton text={argsText} labels={labels} />
            </div>
            <pre className="bf-tl__io-pre">
              <code>{argsText}</code>
            </pre>
          </div>
        )}
        {resultText && (
          <div className="bf-tl__io">
            <div className="bf-tl__io-label">
              <span>{labels.output}</span>
              <CopyButton text={resultText} labels={labels} />
            </div>
            <pre className="bf-tl__io-pre">
              <code>{resultText}</code>
            </pre>
          </div>
        )}
      </div>
    </details>
  );
}

/**
 * The unified Brain chat transcript: a vertical lineage of gutter dots (joined by
 * a connecting line) where each step is one node — a user turn (with image
 * bubbles), a "thinking" marker, an assistant reply, a collapsible tool call with
 * Input/Output, or an error. Presentational and theme-driven (CSS variables), so
 * it renders identically in the web app and a VS Code webview.
 */
function BrainTimelineInner({
  messages,
  trace,
  streamingText,
  isRunning,
  loading,
  labels: labelOverrides,
  modelIdentity = DEFAULT_MODEL_IDENTITY,
  assistantName,
  emptyState,
  renderMessage,
  renderStreaming,
  renderAssistantActions,
  onReplayMessage,
  onRateMessage,
  ratings,
  onInternalLink,
  onApplyCode,
  onCreateFile,
  onAnswerQuestion,
  autoScroll = true,
}: BrainTimelineProps) {
  // Stable across renders so the memoized <Markdown> children below keep their
  // identity and don't re-parse when only streaming text ticks over.
  const labels = useMemo(() => ({ ...DEFAULT_TIMELINE_LABELS, ...labelOverrides }), [labelOverrides]);
  const assistant = assistantName ?? labels.assistant;
  // The settled nodes (the expensive map + sort) depend only on the durable messages
  // and trace, so they're memoized apart from the streaming text — which ticks on every
  // token and would otherwise re-map + re-sort the whole conversation each time.
  const settled = useMemo(() => buildSettledTimeline(messages, trace), [messages, trace]);
  const nodes = useMemo(() => {
    const streaming = streamingNode(streamingText, isRunning);
    return streaming ? [...settled, streaming] : settled;
  }, [settled, streamingText, isRunning]);

  const scrollRef = useRef<HTMLDivElement>(null);
  const contentRef = useRef<HTMLOListElement>(null);
  const pinnedRef = useRef(true);
  // Track whether the user is pinned to the bottom so streaming doesn't yank them.
  const onScroll = () => {
    const el = scrollRef.current;
    if (!el) return;
    pinnedRef.current = el.scrollHeight - el.scrollTop - el.clientHeight < 80;
  };
  // Stay pinned to the newest node through EVERY height change — not just when the
  // node list changes, but as late-loading images, code blocks, and streaming markdown
  // reflow after render (the reason a plain `nodes`-keyed effect lands short of bottom).
  useEffect(() => {
    if (!autoScroll) return;
    const scroller = scrollRef.current;
    const content = contentRef.current;
    if (!scroller || !content) return;
    const stick = () => {
      if (pinnedRef.current) scroller.scrollTop = scroller.scrollHeight;
    };
    stick();
    const ro = new ResizeObserver(stick);
    ro.observe(content);
    return () => ro.disconnect();
  }, [autoScroll]);

  const renderMsg = (msg: BrainMessage, role: 'user' | 'assistant', text: string) =>
    renderMessage ? (
      renderMessage(msg, { role, text })
    ) : (
      <Markdown
        content={text}
        onInternalLink={onInternalLink}
        onApplyCode={role === 'assistant' ? onApplyCode : undefined}
        onCreateFile={role === 'assistant' ? onCreateFile : undefined}
        labels={labels}
      />
    );

  const isEmpty = nodes.length === 0 && !loading;

  return (
    <div className="bf-tl-scroll" ref={scrollRef} onScroll={onScroll}>
      {loading && <div className="bf-tl-status">{labels.loading}</div>}
      {isEmpty &&
        (emptyState ?? <div className="bf-tl-empty">{labels.empty}</div>)}
      <ol className="bf-tl" ref={contentRef}>
        {nodes.map((node) => {
          if (node.kind === 'user') {
            // A message addressed to a participant (not the BRAIN) shows a "→ Name"
            // badge so the transcript makes clear who it was spoken to.
            const to = parseDirectedRecipient(node.message);
            const author = parseMessageAuthor(node.message);
            return (
              <li key={node.key} className="bf-tl__item bf-tl__item--user">
                <span className="bf-tl__gutter">
                  <span className="bf-tl__dot">{author ? <Avatar name={author.name} kind={author.kind} size={16} /> : dotIcon('user')}</span>
                </span>
                <div className="bf-tl__body">
                  <div className="bf-tl__role" style={to ? { display: 'flex', alignItems: 'center', gap: 5, flexWrap: 'wrap' } : undefined}>
                    <span>{author ? author.name : labels.you}</span>
                    {to && (
                      <span style={{ display: 'inline-flex', alignItems: 'center', gap: 4, opacity: 0.9 }}>
                        <span aria-hidden style={{ opacity: 0.6 }}>→</span>
                        <Avatar name={to.name} kind={to.kind} size={15} />
                        <span>{to.name}</span>
                      </span>
                    )}
                  </div>
                  {node.images.length > 0 && (
                    <div className="bf-tl__images">
                      {node.images.map((im, i) => (
                        <img key={i} src={im.url} alt={im.name ?? ''} className="bf-tl__image" />
                      ))}
                    </div>
                  )}
                  {node.text && <div className="bf-tl__bubble bf-tl__bubble--user">{renderMsg(node.message, 'user', node.text)}</div>}
                  <div className="bf-tl__actions bf-tl__actions--hover">
                    <MessageActions message={node.message} role="user" text={node.text} labels={labels} onReplay={onReplayMessage} />
                  </div>
                </div>
              </li>
            );
          }
          if (node.kind === 'assistant') {
            // An assistant turn produced by an invited agent (not the BRAIN) is
            // attributed to it — show the agent's avatar + name in place of the
            // default assistant label so multi-party replies read clearly.
            const author = parseMessageAuthor(node.message);
            // An `ask_user` question rides in the assistant text as a fenced ask-user
            // block. Lift it out to a clickable <QuestionCard> (whichever body renderer
            // the host uses) and render only the surrounding prose through renderMsg, so
            // the model's options are answerable in one click instead of by free-typing.
            const card = onAnswerQuestion ? parseAskUser(node.text) : null;
            const bodyText = card ? stripAskUser(node.text) : node.text;
            // Which model + account produced this turn (persisted on the message by
            // both the streaming Brain path and an agent's addressed reply). Shown as
            // a small chip so the user can always see whether their own connected
            // account ran it — not only when a turn comes back empty.
            const prov = parseMessageProvenance(node.message);
            return (
              <li key={node.key} className="bf-tl__item bf-tl__item--assistant">
                <span className="bf-tl__gutter">
                  <span className="bf-tl__dot">{author ? <Avatar name={author.name} kind={author.kind} size={16} /> : dotIcon('assistant')}</span>
                </span>
                <div className="bf-tl__body">
                  <div className="bf-tl__role">{author ? author.name : assistant}</div>
                  {bodyText && <div className="bf-tl__bubble">{renderMsg(node.message, 'assistant', bodyText)}</div>}
                  {card && onAnswerQuestion && (
                    <QuestionCard
                      payload={card}
                      labels={{ askSubmit: labels.askSubmit, askAnswered: labels.askAnswered }}
                      onAnswer={onAnswerQuestion}
                      anchorId={askUserAnchorId(node.message.id)}
                    />
                  )}
                  <div className="bf-tl__actions">
                    <MessageActions
                      message={node.message}
                      role="assistant"
                      text={bodyText}
                      labels={labels}
                      onReplay={onReplayMessage}
                      onRate={onRateMessage}
                      rating={ratings?.[node.message.id]}
                    />
                    {renderAssistantActions?.(node.message)}
                  </div>
                  {prov && <ProvenanceChip prov={prov} labels={labels} identity={modelIdentity} />}
                </div>
              </li>
            );
          }
          if (node.kind === 'thinking') {
            const label = labels.thoughtFor.replace('{duration}', formatDuration(node.durationMs));
            return (
              <li key={node.key} className="bf-tl__item bf-tl__item--thinking">
                <span className="bf-tl__gutter">
                  <span className="bf-tl__dot bf-tl__dot--muted">{dotIcon('thinking')}</span>
                </span>
                <div className="bf-tl__body">
                  <span className="bf-tl__thinking">{label}</span>
                </div>
              </li>
            );
          }
          if (node.kind === 'tool') {
            return (
              <li key={node.key} className="bf-tl__item bf-tl__item--tool">
                <span className="bf-tl__gutter">
                  <span className={`bf-tl__dot${node.isError ? ' bf-tl__dot--error' : ''}`}>{dotIcon('tool', node.isError)}</span>
                </span>
                <div className="bf-tl__body">
                  <ToolStep node={node} labels={labels} />
                </div>
              </li>
            );
          }
          if (node.kind === 'error') {
            return (
              <li key={node.key} className="bf-tl__item bf-tl__item--error">
                <span className="bf-tl__gutter">
                  <span className="bf-tl__dot bf-tl__dot--error">{dotIcon('error')}</span>
                </span>
                <div className="bf-tl__body">
                  <div className="bf-tl__role bf-tl__role--error">{labels.error}</div>
                  <div className="bf-tl__bubble bf-tl__bubble--error">{node.message}</div>
                </div>
              </li>
            );
          }
          if (node.kind === 'recall') {
            const title = labels.recallTitle
              .replace('{count}', String(node.count))
              .replace('{version}', String(node.version));
            return (
              <li key={node.key} className="bf-tl__item bf-tl__item--memory">
                <span className="bf-tl__gutter">
                  <span className="bf-tl__dot bf-tl__dot--muted">{dotIcon('recall')}</span>
                </span>
                <div className="bf-tl__body">
                  <details className="bf-tl__tool bf-tl__memory">
                    <summary className="bf-tl__tool-head" title={labels.recallHint}>
                      <span className="bf-tl__tool-name">{title}</span>
                      <span className="bf-tl__tool-caret" aria-hidden>▸</span>
                    </summary>
                    <div className="bf-tl__tool-body">
                      <ol className="bf-tl__memory-list">
                        {node.items.map((it) => (
                          <li key={it.id} className="bf-tl__memory-item">
                            <span className="bf-tl__memory-score" aria-hidden>{Math.round(it.score * 100)}%</span>
                            <span className="bf-tl__memory-text">{it.text}</span>
                          </li>
                        ))}
                      </ol>
                    </div>
                  </details>
                </div>
              </li>
            );
          }
          if (node.kind === 'learn') {
            // Multi-target: a project can fan out to MANY Everminds (its own head + its IDE
            // builds). Name EACH by id + version so a fan-out is triageable — the same detail
            // the native chat chip shows. Falls back to the single-line phrasing below when
            // the server sent no per-target breakdown (older turns / summary only).
            if (node.targets && node.targets.length > 0) {
              const lines = node.targets
                .map((tg) => {
                  if (tg.learned) {
                    return labels.learnTargetContributed
                      .replace('{name}', tg.name).replace('{projectId}', String(tg.projectId)).replace('{version}', String(tg.version));
                  }
                  const reasonLabel = tg.reason && tg.reason !== 'too-short'
                    ? labels.learnSkipReason[tg.reason as 'not-attached' | 'not-seeded' | 'frozen']
                    : null;
                  return reasonLabel
                    ? labels.learnTargetSkipped.replace('{name}', tg.name).replace('{projectId}', String(tg.projectId)).replace('{reason}', reasonLabel)
                    : null;
                })
                .filter((s): s is string => !!s);
              if (lines.length === 0) return null;
              return (
                <li key={node.key} className="bf-tl__item bf-tl__item--memory">
                  <span className="bf-tl__gutter">
                    <span className="bf-tl__dot bf-tl__dot--muted">{dotIcon('learn')}</span>
                  </span>
                  <div className="bf-tl__body">
                    <span className="bf-tl__memory-line">{lines.join('; ')}</span>
                  </div>
                </li>
              );
            }
            // Skipped: the turn did NOT feed the Evermind for a project-level reason —
            // render an explained muted line so the absence is never a silent mystery.
            const title = node.skipped
              ? labels.learnSkippedTitle.replace('{reason}', labels.learnSkipReason[node.skipped])
              : labels.learnTitle.replace('{version}', String(node.version));
            const hint = node.skipped ? labels.learnSkippedHint : labels.learnHint;
            return (
              <li key={node.key} className="bf-tl__item bf-tl__item--memory">
                <span className="bf-tl__gutter">
                  <span className="bf-tl__dot bf-tl__dot--muted">{dotIcon('learn')}</span>
                </span>
                <div className="bf-tl__body">
                  <span className="bf-tl__memory-line" title={hint}>{title}</span>
                </div>
              </li>
            );
          }
          if (node.kind === 'activity') {
            // The RUNTIME narrating itself — deliberately NOT an assistant bubble. Composed
            // here from the structured metadata so it reads in the viewer's language; a
            // pre-structured row falls back to the sentence the server stored.
            const text = chatActivityText(node.activity, labels.activity) || node.fallbackText;
            const tone = activityTone(node.activity);
            return (
              <li key={node.key} className={`bf-tl__item bf-tl__item--activity bf-tl__item--activity-${tone}`}>
                <span className="bf-tl__gutter">
                  <span className="bf-tl__dot bf-tl__dot--activity" aria-hidden>{activityIcon(node.activity)}</span>
                </span>
                <div className="bf-tl__body">
                  <span className="bf-tl__activity-line">{text}</span>
                  {node.activity.kind === 'milestone' && node.activity.note && (
                    <span className="bf-tl__activity-note">{node.activity.note}</span>
                  )}
                </div>
              </li>
            );
          }
          if (node.kind === 'reconcile') {
            const title = labels.reconcileTitle
              .replace('{count}', String(node.count))
              .replace('{version}', String(node.version));
            return (
              <li key={node.key} className="bf-tl__item bf-tl__item--memory">
                <span className="bf-tl__gutter">
                  <span className="bf-tl__dot bf-tl__dot--muted">{dotIcon('reconcile')}</span>
                </span>
                <div className="bf-tl__body">
                  <span className="bf-tl__memory-line" title={labels.reconcileHint}>{title}</span>
                </div>
              </li>
            );
          }
          // streaming
          return (
            <li key={node.key} className="bf-tl__item bf-tl__item--assistant bf-tl__item--streaming">
              <span className="bf-tl__gutter">
                <span className="bf-tl__dot bf-tl__dot--pulse">{dotIcon('assistant')}</span>
              </span>
              <div className="bf-tl__body">
                <div className="bf-tl__role">{assistant}</div>
                <div className="bf-tl__bubble">
                  {renderStreaming ? renderStreaming(node.text) : <Markdown content={node.text} onInternalLink={onInternalLink} labels={labels} />}
                </div>
              </div>
            </li>
          );
        })}
        {isRunning && !streamingText.trim() && (
          <li className="bf-tl__item bf-tl__item--thinking" aria-live="polite">
            <span className="bf-tl__gutter">
              <span className="bf-tl__dot bf-tl__dot--pulse">{dotIcon('thinking')}</span>
            </span>
            <div className="bf-tl__body">
              <span className="bf-tl__thinking bf-tl__thinking--live">{labels.thinking}</span>
            </div>
          </li>
        )}
      </ol>
    </div>
  );
}

/**
 * Memoized so an unrelated re-render of the host (e.g. every keystroke in the
 * composer, which lives in the same component tree) does not re-render the whole
 * transcript and re-parse every message's markdown. Callers must pass referentially
 * stable props (memoize `labels` and any `on*` callbacks) for this to take effect.
 */
export const BrainTimeline = React.memo(BrainTimelineInner);
