import React, { useEffect, useMemo, useRef, useState } from 'react';
import { parseDirectedRecipient, parseMessageAuthor, parseMessageProvenance, type BrainMessage, type BrainTraceEvent, type MessageProvenance } from '@seanhogg/builderforce-brain-embedded';
import { Markdown } from './Markdown';
import { Avatar } from './ParticipantBadge';
import { parseAskUser, stripAskUser, QuestionCard, DEFAULT_ASK_USER_LABELS } from './askUser';
import { buildSettledTimeline, formatDuration, formatPayload, streamingNode, type TimelineNode } from './timelineModel';

export interface BrainTimelineLabels {
  /** Shown on the live thinking node while a turn streams. */
  thinking: string;
  /** "Thought for {duration}" — must contain the literal `{duration}` token. */
  thoughtFor: string;
  you: string;
  assistant: string;
  input: string;
  output: string;
  error: string;
  loading: string;
  empty: string;
  copy: string;
  copied: string;
  apply: string;
  createFile: string;
  /** Heading for the change preview shown on an edit_file / write_file tool step. */
  preview: string;
  /** <QuestionCard> copy (ask_user) — carried here so a host passes ONE label bundle. */
  askSubmit: string;
  askAnswered: string;
  /** Provenance chip: the badge shown when the tenant's OWN connected frontier
   *  account served the turn. */
  accountOwn: string;
  /** Provenance chip: the badge for a turn served by the shared model pool. */
  accountShared: string;
  /** Provenance chip: the badge for a shared-pool turn when the tenant HAS a
   *  connected account that wasn't used — the case worth flagging. */
  accountByoUnused: string;
  /** Provenance chip tooltip: shown on the "🧠 Evermind vN" badge when the
   *  project's own self-learning model generated this reply. */
  ranOnEvermind: string;
  /** Evermind recall step title — must contain `{count}` and `{version}`. */
  recallTitle: string;
  /** Tooltip on the recall step explaining what it means. */
  recallHint: string;
  /** Evermind learn step — the turn was contributed back. Must contain `{version}`. */
  learnTitle: string;
  /** Tooltip on the learn step. */
  learnHint: string;
  /** Evermind SKIPPED-learn step — the turn did NOT contribute, and why. Must contain
   *  `{reason}` (filled from {@link learnSkipReason}). */
  learnSkippedTitle: string;
  /** Tooltip on the skipped-learn step. */
  learnSkippedHint: string;
  /** Human phrase per skip reason, substituted into {@link learnSkippedTitle}. */
  learnSkipReason: { 'not-attached': string; 'not-seeded': string; frozen: string };
  /** Evermind reconcile step — the turn updated learned memories. Must contain
   *  `{count}` and `{version}`. */
  reconcileTitle: string;
  /** Tooltip on the reconcile step. */
  reconcileHint: string;
}

export const DEFAULT_TIMELINE_LABELS: BrainTimelineLabels = {
  thinking: 'Thinking…',
  thoughtFor: 'Thought for {duration}',
  you: 'You',
  assistant: 'BuilderForce',
  input: 'Input',
  output: 'Output',
  error: 'Error',
  loading: 'Loading…',
  empty: 'Ask BuilderForce to build or change something.',
  copy: 'Copy',
  copied: 'Copied',
  apply: 'Apply',
  createFile: 'Create file',
  preview: 'Preview',
  askSubmit: DEFAULT_ASK_USER_LABELS.askSubmit,
  askAnswered: DEFAULT_ASK_USER_LABELS.askAnswered,
  accountOwn: 'Your account',
  accountShared: 'Shared pool',
  accountByoUnused: "Your connected account wasn't used",
  ranOnEvermind: "Generated by this project's Evermind model",
  recallTitle: 'Recalled {count} memories from Evermind v{version}',
  recallHint: "This project's self-learning Evermind recalled these prior learnings and grounded the answer on them.",
  learnTitle: 'Contributed this turn to Evermind v{version}',
  learnHint: 'This turn was contributed back to the project Evermind — it will be merged into the learned model.',
  learnSkippedTitle: 'Not learned this turn — {reason}',
  learnSkippedHint: "This turn wasn't contributed to the project Evermind. “Learning — Connected” reflects the selected project's model, not whether this chat feeds it.",
  learnSkipReason: {
    'not-attached': 'this chat isn’t attached to a project',
    'not-seeded': 'this project has no Evermind model yet',
    frozen: 'this project’s Evermind is frozen (read-only)',
  },
  reconcileTitle: 'Reconciled {count} learned memories in Evermind v{version}',
  reconcileHint: 'The answer restated these recalled learnings, so it updates them (write-through cognition).',
};

/**
 * The per-reply provenance chip: which model actually served this turn, and whose
 * account paid for it. A positive confirmation on EVERY assistant turn that the
 * tenant is (or is not) on their own connected frontier account — so "why didn't it
 * use my paid Claude?" is answered inline instead of only surfacing on an empty
 * reply. The `shared_byo_unused` state is styled as a warning because it's the one
 * the user most wants to catch (a connected account that silently wasn't used).
 */
function ProvenanceChip({ prov, labels }: { prov: MessageProvenance; labels: BrainTimelineLabels }) {
  const unused = prov.account === 'shared_byo_unused';
  const badge = prov.account === 'own' ? labels.accountOwn : unused ? labels.accountByoUnused : labels.accountShared;
  const variant = prov.account === 'own' ? 'bf-tl__prov--own' : unused ? 'bf-tl__prov--unused' : 'bf-tl__prov--shared';
  const modelTitle = prov.vendor ? `${prov.model} · ${prov.vendor}` : prov.model;
  return (
    <div className={`bf-tl__prov ${variant}`}>
      <span className="bf-tl__prov-model" title={modelTitle}>{prov.model}</span>
      <span className="bf-tl__prov-badge">{badge}</span>
      {prov.evermind ? (
        <span className="bf-tl__prov-evermind" title={labels.ranOnEvermind}>{`🧠 Evermind v${prov.evermind.version}`}</span>
      ) : null}
    </div>
  );
}

export interface BrainTimelineProps {
  messages: BrainMessage[];
  trace: BrainTraceEvent[];
  streamingText: string;
  isRunning: boolean;
  loading?: boolean;
  labels?: Partial<BrainTimelineLabels>;
  /** Override the assistant display name (defaults to labels.assistant). */
  assistantName?: string;
  /** Replaces the built-in empty state entirely. */
  emptyState?: React.ReactNode;
  /** Render a message's text. Defaults to the shared <Markdown>. The web app
   *  passes its richer ChatMessageBubble here so no feature is lost. */
  renderMessage?: (msg: BrainMessage, ctx: { role: 'user' | 'assistant'; text: string }) => React.ReactNode;
  /** Render the live streaming assistant bubble. Defaults to <Markdown>. */
  renderStreaming?: (text: string) => React.ReactNode;
  /** Per-assistant-message action row (copy / feedback / suggestions). */
  renderAssistantActions?: (msg: BrainMessage) => React.ReactNode;
  onInternalLink?: (href: string) => void;
  onApplyCode?: (code: string) => void;
  onCreateFile?: (path: string, content: string) => void;
  /** Post the user's answer to an agent's `ask_user` question as their next turn.
   *  When set, an assistant message carrying an ask-user block renders a clickable
   *  <QuestionCard>; without it the block degrades to plain text. */
  onAnswerQuestion?: (answer: string) => void;
  /** Auto-scroll to the newest node while near the bottom (default true). */
  autoScroll?: boolean;
}

function dotIcon(kind: TimelineNode['kind'], isError?: boolean): string {
  if (isError) return '✗';
  switch (kind) {
    case 'user':
      return '›';
    case 'assistant':
      return '✦';
    case 'thinking':
      return '∴';
    case 'tool':
      return '⚙';
    case 'error':
      return '✗';
    case 'recall':
    case 'learn':
    case 'reconcile':
      return '🧠';
    default:
      return '•';
  }
}

/** Copy `text` to the clipboard, flashing a "Copied" confirmation. Shared by every
 *  copyable panel on a tool step (Input / Output / preview). */
function CopyButton({ text, labels }: { text: string; labels: BrainTimelineLabels }) {
  const [copied, setCopied] = useState(false);
  return (
    <button
      type="button"
      className="bf-tl__copy"
      title={labels.copy}
      onClick={(e) => {
        e.stopPropagation();
        void navigator.clipboard?.writeText(text).then(
          () => {
            setCopied(true);
            setTimeout(() => setCopied(false), 1500);
          },
          () => {},
        );
      }}
    >
      {copied ? labels.copied : labels.copy}
    </button>
  );
}

type ToolPreview =
  | { kind: 'edit'; path: string; oldText: string; newText: string }
  | { kind: 'write'; path: string; content: string };

/** An edit_file / write_file tool call carries the change itself in its args, so we
 *  can render a readable preview (a before/after diff for edits, the new content for
 *  writes) instead of only the raw JSON — detected structurally so it works regardless
 *  of the tool's display label. */
function toolPreview(args: unknown): ToolPreview | null {
  if (!args || typeof args !== 'object') return null;
  const a = args as Record<string, unknown>;
  const path = typeof a.path === 'string' ? a.path : '';
  if (typeof a.old_string === 'string' && typeof a.new_string === 'string') {
    return { kind: 'edit', path, oldText: a.old_string, newText: a.new_string };
  }
  if (path && typeof a.content === 'string') {
    return { kind: 'write', path, content: a.content };
  }
  return null;
}

function DiffLines({ text, sign }: { text: string; sign: '+' | '-' }) {
  const cls = sign === '+' ? 'bf-tl__diff-add' : 'bf-tl__diff-del';
  return (
    <>
      {text.split('\n').map((line, i) => (
        <div key={i} className={`bf-tl__diff-line ${cls}`}>
          <span className="bf-tl__diff-sign" aria-hidden>{sign}</span>
          <span className="bf-tl__diff-text">{line || ' '}</span>
        </div>
      ))}
    </>
  );
}

function ToolStep({
  node,
  labels,
}: {
  node: Extract<TimelineNode, { kind: 'tool' }>;
  labels: BrainTimelineLabels;
}) {
  const argsText = formatPayload(node.args);
  const resultText = formatPayload(node.result);
  const preview = toolPreview(node.args);
  return (
    <details className={`bf-tl__tool${node.isError ? ' bf-tl__tool--error' : ''}`}>
      <summary className="bf-tl__tool-head">
        <span className="bf-tl__tool-status" aria-hidden>
          {node.isError ? '✗' : '✓'}
        </span>
        <span className="bf-tl__tool-name">{node.label}</span>
        {node.durationMs != null && <span className="bf-tl__tool-dur">{formatDuration(node.durationMs)}</span>}
        <span className="bf-tl__tool-caret" aria-hidden>
          ▸
        </span>
      </summary>
      <div className="bf-tl__tool-body">
        {preview && (
          <div className="bf-tl__io">
            <div className="bf-tl__io-label">
              <span>{labels.preview}{preview.path ? ` · ${preview.path}` : ''}</span>
              <CopyButton
                text={preview.kind === 'edit' ? preview.newText : preview.content}
                labels={labels}
              />
            </div>
            {preview.kind === 'edit' ? (
              <div className="bf-tl__diff">
                <DiffLines text={preview.oldText} sign="-" />
                <DiffLines text={preview.newText} sign="+" />
              </div>
            ) : (
              <pre className="bf-tl__io-pre">
                <code>{preview.content}</code>
              </pre>
            )}
          </div>
        )}
        {argsText && (
          <div className="bf-tl__io">
            <div className="bf-tl__io-label">
              <span>{labels.input}</span>
              <CopyButton text={argsText} labels={labels} />
            </div>
            <pre className="bf-tl__io-pre">
              <code>{argsText}</code>
            </pre>
          </div>
        )}
        {resultText && (
          <div className="bf-tl__io">
            <div className="bf-tl__io-label">
              <span>{labels.output}</span>
              <CopyButton text={resultText} labels={labels} />
            </div>
            <pre className="bf-tl__io-pre">
              <code>{resultText}</code>
            </pre>
          </div>
        )}
      </div>
    </details>
  );
}

/**
 * The unified Brain chat transcript: a vertical lineage of gutter dots (joined by
 * a connecting line) where each step is one node — a user turn (with image
 * bubbles), a "thinking" marker, an assistant reply, a collapsible tool call with
 * Input/Output, or an error. Presentational and theme-driven (CSS variables), so
 * it renders identically in the web app and a VS Code webview.
 */
function BrainTimelineInner({
  messages,
  trace,
  streamingText,
  isRunning,
  loading,
  labels: labelOverrides,
  assistantName,
  emptyState,
  renderMessage,
  renderStreaming,
  renderAssistantActions,
  onInternalLink,
  onApplyCode,
  onCreateFile,
  onAnswerQuestion,
  autoScroll = true,
}: BrainTimelineProps) {
  // Stable across renders so the memoized <Markdown> children below keep their
  // identity and don't re-parse when only streaming text ticks over.
  const labels = useMemo(() => ({ ...DEFAULT_TIMELINE_LABELS, ...labelOverrides }), [labelOverrides]);
  const assistant = assistantName ?? labels.assistant;
  // The settled nodes (the expensive map + sort) depend only on the durable messages
  // and trace, so they're memoized apart from the streaming text — which ticks on every
  // token and would otherwise re-map + re-sort the whole conversation each time.
  const settled = useMemo(() => buildSettledTimeline(messages, trace), [messages, trace]);
  const nodes = useMemo(() => {
    const streaming = streamingNode(streamingText, isRunning);
    return streaming ? [...settled, streaming] : settled;
  }, [settled, streamingText, isRunning]);

  const scrollRef = useRef<HTMLDivElement>(null);
  const contentRef = useRef<HTMLOListElement>(null);
  const pinnedRef = useRef(true);
  // Track whether the user is pinned to the bottom so streaming doesn't yank them.
  const onScroll = () => {
    const el = scrollRef.current;
    if (!el) return;
    pinnedRef.current = el.scrollHeight - el.scrollTop - el.clientHeight < 80;
  };
  // Stay pinned to the newest node through EVERY height change — not just when the
  // node list changes, but as late-loading images, code blocks, and streaming markdown
  // reflow after render (the reason a plain `nodes`-keyed effect lands short of bottom).
  useEffect(() => {
    if (!autoScroll) return;
    const scroller = scrollRef.current;
    const content = contentRef.current;
    if (!scroller || !content) return;
    const stick = () => {
      if (pinnedRef.current) scroller.scrollTop = scroller.scrollHeight;
    };
    stick();
    const ro = new ResizeObserver(stick);
    ro.observe(content);
    return () => ro.disconnect();
  }, [autoScroll]);

  const renderMsg = (msg: BrainMessage, role: 'user' | 'assistant', text: string) =>
    renderMessage ? (
      renderMessage(msg, { role, text })
    ) : (
      <Markdown
        content={text}
        onInternalLink={onInternalLink}
        onApplyCode={role === 'assistant' ? onApplyCode : undefined}
        onCreateFile={role === 'assistant' ? onCreateFile : undefined}
        labels={labels}
      />
    );

  const isEmpty = nodes.length === 0 && !loading;

  return (
    <div className="bf-tl-scroll" ref={scrollRef} onScroll={onScroll}>
      {loading && <div className="bf-tl-status">{labels.loading}</div>}
      {isEmpty &&
        (emptyState ?? <div className="bf-tl-empty">{labels.empty}</div>)}
      <ol className="bf-tl" ref={contentRef}>
        {nodes.map((node) => {
          if (node.kind === 'user') {
            // A message addressed to a participant (not the BRAIN) shows a "→ Name"
            // badge so the transcript makes clear who it was spoken to.
            const to = parseDirectedRecipient(node.message);
            return (
              <li key={node.key} className="bf-tl__item bf-tl__item--user">
                <span className="bf-tl__gutter">
                  <span className="bf-tl__dot">{dotIcon('user')}</span>
                </span>
                <div className="bf-tl__body">
                  <div className="bf-tl__role" style={to ? { display: 'flex', alignItems: 'center', gap: 5, flexWrap: 'wrap' } : undefined}>
                    <span>{labels.you}</span>
                    {to && (
                      <span style={{ display: 'inline-flex', alignItems: 'center', gap: 4, opacity: 0.9 }}>
                        <span aria-hidden style={{ opacity: 0.6 }}>→</span>
                        <Avatar name={to.name} kind={to.kind} size={15} />
                        <span>{to.name}</span>
                      </span>
                    )}
                  </div>
                  {node.images.length > 0 && (
                    <div className="bf-tl__images">
                      {node.images.map((im, i) => (
                        <img key={i} src={im.url} alt={im.name ?? ''} className="bf-tl__image" />
                      ))}
                    </div>
                  )}
                  {node.text && <div className="bf-tl__bubble bf-tl__bubble--user">{renderMsg(node.message, 'user', node.text)}</div>}
                </div>
              </li>
            );
          }
          if (node.kind === 'assistant') {
            // An assistant turn produced by an invited agent (not the BRAIN) is
            // attributed to it — show the agent's avatar + name in place of the
            // default assistant label so multi-party replies read clearly.
            const author = parseMessageAuthor(node.message);
            // An `ask_user` question rides in the assistant text as a fenced ask-user
            // block. Lift it out to a clickable <QuestionCard> (whichever body renderer
            // the host uses) and render only the surrounding prose through renderMsg, so
            // the model's options are answerable in one click instead of by free-typing.
            const card = onAnswerQuestion ? parseAskUser(node.text) : null;
            const bodyText = card ? stripAskUser(node.text) : node.text;
            // Which model + account produced this turn (persisted on the message by
            // both the streaming Brain path and an agent's addressed reply). Shown as
            // a small chip so the user can always see whether their own connected
            // account ran it — not only when a turn comes back empty.
            const prov = parseMessageProvenance(node.message);
            return (
              <li key={node.key} className="bf-tl__item bf-tl__item--assistant">
                <span className="bf-tl__gutter">
                  <span className="bf-tl__dot">{author ? <Avatar name={author.name} kind={author.kind} size={16} /> : dotIcon('assistant')}</span>
                </span>
                <div className="bf-tl__body">
                  <div className="bf-tl__role">{author ? author.name : assistant}</div>
                  {bodyText && <div className="bf-tl__bubble">{renderMsg(node.message, 'assistant', bodyText)}</div>}
                  {card && onAnswerQuestion && (
                    <QuestionCard
                      payload={card}
                      labels={{ askSubmit: labels.askSubmit, askAnswered: labels.askAnswered }}
                      onAnswer={onAnswerQuestion}
                    />
                  )}
                  {renderAssistantActions && <div className="bf-tl__actions">{renderAssistantActions(node.message)}</div>}
                  {prov && <ProvenanceChip prov={prov} labels={labels} />}
                </div>
              </li>
            );
          }
          if (node.kind === 'thinking') {
            const label = labels.thoughtFor.replace('{duration}', formatDuration(node.durationMs));
            return (
              <li key={node.key} className="bf-tl__item bf-tl__item--thinking">
                <span className="bf-tl__gutter">
                  <span className="bf-tl__dot bf-tl__dot--muted">{dotIcon('thinking')}</span>
                </span>
                <div className="bf-tl__body">
                  <span className="bf-tl__thinking">{label}</span>
                </div>
              </li>
            );
          }
          if (node.kind === 'tool') {
            return (
              <li key={node.key} className="bf-tl__item bf-tl__item--tool">
                <span className="bf-tl__gutter">
                  <span className={`bf-tl__dot${node.isError ? ' bf-tl__dot--error' : ''}`}>{dotIcon('tool', node.isError)}</span>
                </span>
                <div className="bf-tl__body">
                  <ToolStep node={node} labels={labels} />
                </div>
              </li>
            );
          }
          if (node.kind === 'error') {
            return (
              <li key={node.key} className="bf-tl__item bf-tl__item--error">
                <span className="bf-tl__gutter">
                  <span className="bf-tl__dot bf-tl__dot--error">{dotIcon('error')}</span>
                </span>
                <div className="bf-tl__body">
                  <div className="bf-tl__role bf-tl__role--error">{labels.error}</div>
                  <div className="bf-tl__bubble bf-tl__bubble--error">{node.message}</div>
                </div>
              </li>
            );
          }
          if (node.kind === 'recall') {
            const title = labels.recallTitle
              .replace('{count}', String(node.count))
              .replace('{version}', String(node.version));
            return (
              <li key={node.key} className="bf-tl__item bf-tl__item--memory">
                <span className="bf-tl__gutter">
                  <span className="bf-tl__dot bf-tl__dot--muted">{dotIcon('recall')}</span>
                </span>
                <div className="bf-tl__body">
                  <details className="bf-tl__tool bf-tl__memory">
                    <summary className="bf-tl__tool-head" title={labels.recallHint}>
                      <span className="bf-tl__tool-name">{title}</span>
                      <span className="bf-tl__tool-caret" aria-hidden>▸</span>
                    </summary>
                    <div className="bf-tl__tool-body">
                      <ol className="bf-tl__memory-list">
                        {node.items.map((it) => (
                          <li key={it.id} className="bf-tl__memory-item">
                            <span className="bf-tl__memory-score" aria-hidden>{Math.round(it.score * 100)}%</span>
                            <span className="bf-tl__memory-text">{it.text}</span>
                          </li>
                        ))}
                      </ol>
                    </div>
                  </details>
                </div>
              </li>
            );
          }
          if (node.kind === 'learn') {
            // Skipped: the turn did NOT feed the Evermind for a project-level reason —
            // render an explained muted line so the absence is never a silent mystery.
            const title = node.skipped
              ? labels.learnSkippedTitle.replace('{reason}', labels.learnSkipReason[node.skipped])
              : labels.learnTitle.replace('{version}', String(node.version));
            const hint = node.skipped ? labels.learnSkippedHint : labels.learnHint;
            return (
              <li key={node.key} className="bf-tl__item bf-tl__item--memory">
                <span className="bf-tl__gutter">
                  <span className="bf-tl__dot bf-tl__dot--muted">{dotIcon('learn')}</span>
                </span>
                <div className="bf-tl__body">
                  <span className="bf-tl__memory-line" title={hint}>{title}</span>
                </div>
              </li>
            );
          }
          if (node.kind === 'reconcile') {
            const title = labels.reconcileTitle
              .replace('{count}', String(node.count))
              .replace('{version}', String(node.version));
            return (
              <li key={node.key} className="bf-tl__item bf-tl__item--memory">
                <span className="bf-tl__gutter">
                  <span className="bf-tl__dot bf-tl__dot--muted">{dotIcon('reconcile')}</span>
                </span>
                <div className="bf-tl__body">
                  <span className="bf-tl__memory-line" title={labels.reconcileHint}>{title}</span>
                </div>
              </li>
            );
          }
          // streaming
          return (
            <li key={node.key} className="bf-tl__item bf-tl__item--assistant bf-tl__item--streaming">
              <span className="bf-tl__gutter">
                <span className="bf-tl__dot bf-tl__dot--pulse">{dotIcon('assistant')}</span>
              </span>
              <div className="bf-tl__body">
                <div className="bf-tl__role">{assistant}</div>
                <div className="bf-tl__bubble">
                  {renderStreaming ? renderStreaming(node.text) : <Markdown content={node.text} onInternalLink={onInternalLink} labels={labels} />}
                </div>
              </div>
            </li>
          );
        })}
        {isRunning && !streamingText.trim() && (
          <li className="bf-tl__item bf-tl__item--thinking" aria-live="polite">
            <span className="bf-tl__gutter">
              <span className="bf-tl__dot bf-tl__dot--pulse">{dotIcon('thinking')}</span>
            </span>
            <div className="bf-tl__body">
              <span className="bf-tl__thinking bf-tl__thinking--live">{labels.thinking}</span>
            </div>
          </li>
        )}
      </ol>
    </div>
  );
}

/**
 * Memoized so an unrelated re-render of the host (e.g. every keystroke in the
 * composer, which lives in the same component tree) does not re-render the whole
 * transcript and re-parse every message's markdown. Callers must pass referentially
 * stable props (memoize `labels` and any `on*` callbacks) for this to take effect.
 */
export const BrainTimeline = React.memo(BrainTimelineInner);
