/**
 * Chat-related type definitions for group-by-topic functionality
 */

export interface ChatMessage {
  id: string;
  text: string;
  sender: string;
  timestamp: number;
  metadata?: Record<string, unknown>;
}

export interface Chat {
  id: string;
  title: string;
  messages: ChatMessage[];
  participants: string[];
  metadata?: {
    externalId?: string;
    channelType?: string;
    platform?: string;
    lastMessageAt?: number;
  };
}

/**
 * Represents a topic group for chat organization
 */
export interface ChatTopicGroup {
  id: string;
  name: string;
  description?: string;
  chatIds: string[];
  autoGenerated: boolean;
  color?: string;
}

/**
 * Groups response: categorized insights from the top-level grouping
 */
export interface GroupedChatsAnalysis {
  groups: ChatTopicGroup[];
  topTopicsByChatCount: { topic: string; count: number }[];
  customTopicNames: Record<string, string>;
  messageCountPerGroup: Record<string, number>;
  totalMsgs: number;
}

/**
 * Topic detection result
 */
export interface TopicDetectionResult {
  topic: string;
  confidence: number;
  keywords: string[];
}

export type TopicCategory =
  | 'prd'
  | 'agent-creation'
  | 'pwa'
  | 'general'
  | 'dev'
  | 'design'
  | 'docs'
  | 'bug'
  | 'feature'
  | 'meeting'
  | 'ops'
  | 'qa'
  | 'infrastructure'
  | 'security'
  | 'analytics'
  | 'migration'
  | 'deployment'
  | 'other';

export type AutoGeneratedGroup = {
  id: string;
  name: string;
  category: TopicCategory;
  description?: string;
  color?: string;
  emoji?: string;
};