/**
 * Integration audit and health dashboard types.
 *
 * Defines the data models for integration status checks, data completeness scoring,
 * gap detection, and recommendations generated by the audit system.
 */

/**
 * Integration status classification
 */
export type IntegrationStatus = 'CONNECTED' | 'PARTIAL' | 'MISSING';

/**
 * Integration types supported by the audit system
 */
export type IntegrationType =
  | 'source-control'
  | 'issue-tracker'
  | 'communication'
  | 'cicd'
  | 'monitoring'
  | 'calendar';

/**
 * Source control providers
 */
export type SourceControlProvider = 'GITHUB' | 'GITLAB' | 'BITBUCKET';

/**
 * Issue tracker providers
 */
export type IssueTrackerProvider = 'JIRA' | 'LINEAR';

/**
 * Communication platform providers
 */
export type CommunicationProvider = 'SLACK' | 'MICROSOFT_TEAMS';

/**
 * CI/CD platform providers
 */
export type CDNProvider = 'GITHUB_ACTIONS' | 'JENKINS' | 'CIRCLECI';

/**
 * Monitoring platform providers
 */
export type MonitoringProvider = 'DATADOG' | 'PAGERDUTY';

/**
 * Calendar/Project management providers
 */
export type CalendarProvider = 'GOOGLE_CALENDAR' | 'OUTLOOK' | 'ASANA';

/**
 * Represents a single integration connection
 */
export interface IntegrationConnection {
  id: string;
  tenantId: string;
  segmentId: string;
  type: IntegrationType;
  provider: string; // e.g., 'GITHUB', 'SLACK', 'DATADOG'
  externalId: string; // provider-specific identifier
  name: string;
  connectedAt?: string;
  lastSync?: string;
  enabled: boolean;
  configuration: Record<string, unknown>; // additional config like repo URLs, channel IDs, webhook URLs, etc.
}

/**
 * Represents a specific check performed on an integration
 */
export interface IntegrationCheck {
  id: string;
  integrationId: string;
  tenantId: string;
  segmentId: string;
  checkType: string; // e.g., 'webhook_trigger', 'data_flow', 'recent_activity', 'field_mapping'
  name: string;
  passed: boolean;
  details?: Record<string, unknown>;
  occurredAt: string;
}

/**
 * Represents any gap or exception detected with an integration
 */
export interface IntegrationGap {
  id: string;
  integrationId: string;
  tenantId: string;
  segmentId: string;
  severity: 'LOW' | 'MEDIUM' | 'HIGH' | 'CRITICAL';
  category: 'WEBHOOK' | 'DATA_COMPLETENESS' | 'RATE_LIMIT' | 'CONFIGURATION' | 'STALE_DATA' | 'MISCONFIGURATION';
  description: string;
  recommendation: string;
  detectedAt: string;
  resolvedAt?: string;
}

/**
 * Data completeness score for an integration including weighted components
 */
export interface CompletenessScore {
  integrationId: string;
  tenantId: string;
  segmentId: string;
  totalWeightedScore: number; // 0-100
  maxPossibleScore: number;
  breakdown: {
    expectedObjectsWeight: number; // number of expected objects (repos, issues, etc.)
    expectedObjectsMatched: number; // number of objects actually present
    recencyWeight: number; // recency of data relative to threshold
    recencyScore: number; // 0-1 based on recency
    criticalityWeight: number; // weight based on integration type criticality
    criticalityScore: number; // 0-1 based on criticality
  };
  lastCalculated: string;
}

/**
 * Integrated health record summarizing an integration's audit result
 */
export interface IntegrationHealth {
  id: string;
  integrationId: string;
  connection?: IntegrationConnection;
  lastSync?: string;
  status: IntegrationStatus;
  completenessScore: number; // 0-100
  gaps: IntegrationGap[];
  recommendations: string[];
  lastAuditAt: string;
}

/**
 * Service tier determining integration criticality weights
 */
export interface ServiceTier {
  tenantId: string;
  tier: 'FREE' | 'PRO' | 'ENTERPRISE';
  weights: {
    sourceControl: number; // 0.0-1.0
    issueTracker: number;
    communication: number;
    cicd: number;
    monitoring: number;
    calendar: number;
  };
}

/**
 * Pagination response
 */
export interface PaginatedResponse<T> {
  items: T[];
  total: number;
  page: number;
  pageSize: number;
  hasMore: boolean;
}

/**
 * Audit request query options
 */
export interface AuditQueryOptions {
  tenantId: string;
  segmentId: string;
  integrationType?: IntegrationType;
  status?: IntegrationStatus;
  minScore?: number;
  maxScore?: number;
  includeGaps: boolean;
  includeRecommendations: boolean;
  sortBy?: 'lastSync' | 'completenessScore' | 'status';
  sortOrder?: 'asc' | 'desc';
}