/**
 * API functions for topic grouping feature
 *
 * Handles communication with backend endpoints for topic detection and grouping
 */

import type { Chat, GroupedChatsAnalysis, ChatTopicGroup } from '../types/chat';
import type { CustomTopicGroup, CustomGroupingState } from '../types/group';

/**
 * Convert detected chat groups to API-friendly format
 */
function toChatGroup(group: { chatIds: string[]; name: string; description?: string; category: string }): ChatTopicGroup {
  return {
    id: `group-${Date.now()}-${Math.random().toString(36).substr(2, 9)}`,
    name: group.name,
    description: group.description,
    chatIds: group.chatIds,
    autoGenerated: true,
  };
}

/**
 * Detect topics in a set of chats via API
 */
export async function detectTopics(chats: Chat[]): Promise<GroupedChatsAnalysis> {
  try {
    const response = await fetch('/api/topics/detect', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({ chats }),
    });

    if (!response.ok) {
      throw new Error(`API error: ${response.statusText}`);
    }

    const data = await response.json();
    return data;
  } catch (error) {
    console.error('Topic detection failed:', error);

    // Fallback to client-side detection
    return generateLocalAnalysis(chats);
  }
}

/**
 * Analyze chats and generate grouping analysis
 */
export async function analyzeChatTopics(
  chats: Chat[],
  options?: { minGroupSize?: number; defaultCategory?: string }
): Promise<GroupedChatsAnalysis> {
  return detectTopics(chats);
}

/**
 * Create a custom topic group via API
 */
export async function createCustomTopicGroup(
  group: Omit<CustomTopicGroup, 'createdAt' | 'lastModifiedAt'>
): Promise<CustomTopicGroup> {
  const sanitized = {
    ...group,
    createdAt: Date.now(),
    lastModifiedAt: Date.now(),
  };

  try {
    const response = await fetch('/api/groups', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify(sanitized),
    });

    if (!response.ok) {
      throw new Error(`Failed to create group: ${response.statusText}`);
    }

    return await response.json();
  } catch (error) {
    console.error('Creating custom group failed:', error);
    // Return client-side fallback
    return sanitized;
  }
}

/**
 * Update a custom topic group via API
 */
export async function updateCustomTopicGroup(
  groupId: string,
  updates: Partial<CustomTopicGroup>
): Promise<CustomTopicGroup> {
  const updated = {
    ...updates,
    lastModifiedAt: Date.now(),
  };

  try {
    const response = await fetch(`/api/groups/${groupId}`, {
      method: 'PATCH',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify(updated),
    });

    if (!response.ok) {
      throw new Error(`Failed to update group: ${response.statusText}`);
    }

    return await response.json();
  } catch (error) {
    console.error('Updating custom group failed:', error);
    return updated;
  }
}

/**
 * Delete a custom topic group via API
 */
export async function deleteCustomTopicGroup(groupId: string): Promise<boolean> {
  try {
    const response = await fetch(`/api/groups/${groupId}`, {
      method: 'DELETE',
    });

    if (!response.ok) {
      throw new Error(`Failed to delete group: ${response.statusText}`);
    }

    return true;
  } catch (error) {
    console.error('Deleting custom group failed:', error);
    return false;
  }
}

/**
 * Move a chat between groups via API
 */
export async function moveChatBetweenGroups(
  chatId: string,
  targetGroupId: string
): Promise<boolean> {
  try {
    const response = await fetch('/api/chats/move', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({ chatId, targetGroupId }),
    });

    if (!response.ok) {
      throw new Error(`Failed to move chat: ${response.statusText}`);
    }

    return true;
  } catch (error) {
    console.error('Moving chat failed:', error);
    return false;
  }
}

/**
 * Ungroup a chat via API
 */
export async function ungroupChat(chatId: string): Promise<boolean> {
  try {
    const response = await fetch('/api/chats/ungroup', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({ chatId }),
    });

    if (!response.ok) {
      throw new Error(`Failed to ungroup chat: ${response.statusText}`);
    }

    return true;
  } catch (error) {
    console.error('Ungrouping chat failed:', error);
    return false;
  }
}

/**
 * Persist custom grouping state via API
 */
export async function saveCustomGroupingState(
  state: CustomGroupingState
): Promise<boolean> {
  try {
    const response = await fetch('/api/group-state', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify(state),
    });

    if (!response.ok) {
      throw new Error(`Failed to save grouping state: ${response.statusText}`);
    }

    return true;
  } catch (error) {
    console.error('Saving custom grouping state failed:', error);
    return false;
  }
}

/**
 * Retrieve persisted custom grouping state via API
 */
export async function loadCustomGroupingState(): Promise<CustomGroupingState | null> {
  try {
    const response = await fetch('/api/group-state');

    if (!response.ok) {
      throw new Error(`Failed to load grouping state: ${response.statusText}`);
    }

    const data = await response.json();
    return data;
  } catch (error) {
    console.error('Loading custom grouping state failed:', error);
    return null;
  }
}

/**
 * Fallback: Generate local analysis when API is unavailable
 */
function generateLocalAnalysis(chats: Chat[]): GroupedChatsAnalysis {
  // Simple grouping: group chats by their highest-confidence detected topic
  const categoryCounts: Record<string, Chat[]> = {};

  for (const chat of chats) {
    // Use the frontend utility to detect topics
    const detection = detectTopic(chat);

    if (!categoryCounts[detection.topic]) {
      categoryCounts[detection.topic] = [];
    }

    categoryCounts[detection.topic].push(chat);
  }

  const groups: ChatTopicGroup[] = Object.entries(categoryCounts).map(
    ([topic, chats]) => {
      return toChatGroup({
        chatIds: chats.map((c) => c.id),
        name: topic.toUpperCase(),
        description: `${chats.length} chats`,
        category: topic,
      });
    }
  );

  const topTopicsByChatCount = Object.entries(categoryCounts)
    .map(([topic, chats]) => ({ topic: topic, count: chats.length }))
    .sort((a, b) => b.count - a.count);

  const messageCountPerGroup: Record<string, number> = {};
  const totalMsgs = chats.reduce((acc, chat) => acc + chat.messages.length, 0);

  for (const group of groups) {
    const firstChat = chats.find((c) => c.id === group.chatIds[0]);
    if (firstChat) {
      messageCountPerGroup[group.id] = firstChat.messages.length;
    }
  }

  const customTopicNames: Record<string, string> = {};

  return {
    groups,
    topTopicsByChatCount,
    customTopicNames,
    messageCountPerGroup,
    totalMsgs,
  };
}

/**
 * Re-evaluate topics for a chat after new messages arrive
 */
export async function reevaluateChatTopic(
  chatId: string,
  newMessages: Array<{ text: string; sender: string }>
): Promise<string | null> {
  try {
    const response = await fetch('/api/topics/reevaluate', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({ chatId, newMessages }),
    });

    if (!response.ok) {
      throw new Error(`Failed to reevaluate topic: ${response.statusText}`);
    }

    const data = await response.json();
    return data.topic || null;
  } catch (error) {
    console.error('Reevaluating chat topic failed:', error);
    return null;
  }
}