/**
 * Blueprint: generic — the fallback when no specific blueprint fits the brief.
 *
 * This is what makes the pipeline answer "any pasted contest" rather than "the
 * contests we anticipated". It contributes the SKELETON — a runnable static
 * front end, a health endpoint that proves the ingress is live, a runbook — and
 * leaves the system's actual design to the planner, which asks a model to author
 * handlers against the same {@link HandlerSpec} contract a hand-written blueprint
 * uses.
 *
 * Keeping a skeleton at all (rather than starting from nothing) matters for one
 * specific reason: the very first thing a customer needs is evidence that the
 * thing they just created is REACHABLE. `/health` answers that before any
 * generated handler exists, so a model producing a poor design degrades to "the
 * system is up but does little", not to "nothing responds and I cannot tell why".
 */

import type { Blueprint } from '../blueprint';

const HEALTH_HANDLER = {
  name: 'health',
  route: '/health',
  method: 'GET',
  // Public on purpose: its whole job is to be callable by someone holding only
  // the URL, and it discloses nothing but liveness.
  verify: 'none',
  description: 'Liveness probe — proves this project’s ingress is reachable.',
  steps: [],
  respond: {
    kind: 'json',
    body: { ok: true, project: '{{project.name}}', ingress: '{{project.ingressUrl}}' },
  },
};

const INDEX_HTML = `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<title>Challenge workspace</title>
<style>
  :root {
    color-scheme: light dark;
    --bg: #f6f7f9; --surface: #fff; --text: #14161a; --muted: #5c6470;
    --border: #dfe3e8; --accent: #2f6fed;
  }
  @media (prefers-color-scheme: dark) {
    :root { --bg: #0e1116; --surface: #161a21; --text: #e8eaed; --muted: #9aa3ae;
            --border: #262c36; --accent: #6f9bff; }
  }
  * { box-sizing: border-box; }
  body { margin: 0; background: var(--bg); color: var(--text);
         font: 15px/1.6 system-ui, -apple-system, "Segoe UI", sans-serif; }
  .wrap { max-width: 820px; margin: 0 auto; padding: clamp(16px, 5vw, 56px); }
  h1 { font-size: clamp(22px, 5vw, 32px); margin: 0 0 8px; }
  p.sub { color: var(--muted); margin: 0 0 28px; }
  .card { background: var(--surface); border: 1px solid var(--border);
          border-radius: 12px; padding: 20px; margin-bottom: 16px; }
  code { background: var(--bg); border: 1px solid var(--border); border-radius: 5px;
         padding: 2px 6px; font-size: 13px; word-break: break-all; }
  ol { margin: 0; padding-left: 20px; }
  li { margin: 6px 0; }
</style>
</head>
<body>
<div class="wrap">
  <h1>Challenge workspace</h1>
  <p class="sub">Generated by Builderforce from your brief. Edit everything.</p>
  <div class="card">
    <strong>Backend is live.</strong>
    <p>Your handlers are executed at this project's ingress URL. Check it with
       <code>GET &lt;ingress&gt;/health</code> — see <code>handlers/README.md</code>
       for the exact address.</p>
  </div>
  <div class="card">
    <strong>Next</strong>
    <ol>
      <li>Read <code>RUNBOOK.md</code> for what was planned and why.</li>
      <li>Connect the integrations listed on the challenge page.</li>
      <li>Store the required secrets in the project vault.</li>
      <li>Work the seeded tickets on the board.</li>
    </ol>
  </div>
</div>
</body>
</html>
`;

export const genericBlueprint: Blueprint = {
  key: 'generic',
  name: 'Generic challenge workspace',
  summary:
    'A runnable workspace with a live backend ingress and a health endpoint. The system design — handlers, integrations and tickets — is generated from your brief.',
  // No signals: `generic` is never SELECTED by matching, it is what is used when
  // nothing else clears the threshold.
  signals: [],
  capabilities: ['inbound-webhook', 'dashboard', 'ai-agent'],
  requiredConnectors: [],
  requiredSecrets: [],
  strategy: 'declarative',
  files: { 'index.html': INDEX_HTML },
  handlers: { health: HEALTH_HANDLER },
  tasks: [
    {
      order: 1,
      title: 'Review the generated plan',
      description:
        'The plan on the challenge page was derived from your brief by a model. Confirm the capabilities, integrations and acceptance criteria before building on top of it — a wrong reading of the brief is far cheaper to fix here than after the tickets are worked.',
    },
    {
      order: 2,
      title: 'Connect the required integrations',
      description:
        'Create a connection for each integration the plan lists. Handlers that call a connector fail closed until the connection exists.',
    },
    {
      order: 3,
      title: 'Prove the ingress is reachable',
      description: 'GET <ingress>/health and confirm a 200. This is the fastest check that the backend is live before any provider is wired to it.',
    },
  ],
  successCriteria: [
    'The ingress answers a health check.',
    'Every integration the plan requires has a live connection.',
    'Each acceptance criterion extracted from the brief is demonstrable.',
  ],
};
