/**
 * Growth & marketing entities — owned by the **CMO** (PRD 20 §3.2, migration 0432).
 *
 * The largest domain in the roster, and the one PRD 19 §2 assembled from all
 * three products: hired.video's feed, boosts and creator content; BurnRateOS's
 * ad manager and journeys; Builderforce's campaigns and landing pages.
 *
 * `email_campaigns` carries the `kind` column §3.3 adjudicated — a nurture send,
 * a newsletter and a recruiter sequence blast are one shape with three kinds —
 * which is why one campaign entity appears here instead of three.
 */
import {
  abTestSegments,
  abTestVariants,
  abTests,
  activityFeed,
  adCampaigns,
  adSets,
  ads,
  affiliateReferrals,
  announcementBanners,
  blogPosts,
  boostCheckouts,
  boosts,
  brandKits,
  contentAudiences,
  contentLocations,
  creatorYoutubeIngests,
  customerJourneys,
  embedWidgetLayout,
  emailCampaigns,
  employerBrandingPages,
  eventCategories,
  eventMatchmaking,
  eventRemindersSent,
  eventWaitlist,
  experiments,
  feedFeatures,
  feedPosts,
  followUpEnrollments,
  journeyTouchpoints,
  landingPageBlocks,
  landingPages,
  learnVideos,
  marketingContentItems,
  marketingEmails,
  marketingHeatmapPages,
  marketingHeatmapScreenshots,
  marketingLeads,
  marketingSessionPrompts,
  marketingSeoPages,
  nurtureFlows,
  pageEmbedVideos,
  podcastOutreach,
  promoProjects,
  referralEntries,
  videos,
  waitlistEntries,
  websitePages,
} from '../../../infrastructure/database/schema/growth';
import { defineDomainEntities, entity } from '../entityDefinition';

export const GROWTH_ENTITIES = defineDomainEntities('growth', [
  entity(emailCampaigns, { kind: 'campaign', registers: true }),
  entity(landingPages, { kind: 'landing_page', registers: true }),
  entity(blogPosts, { kind: 'blog_post', registers: true }),
  entity(marketingLeads, { kind: 'lead', registers: true }),
  entity(experiments, { kind: 'experiment', registers: true }),
  marketingEmails,
  nurtureFlows,
  followUpEnrollments,
  customerJourneys,
  journeyTouchpoints,
  waitlistEntries,
  referralEntries,
  podcastOutreach,
  adCampaigns,
  adSets,
  ads,
  boosts,
  abTests,
  abTestVariants,
  abTestSegments,
  landingPageBlocks,
  websitePages,
  marketingSeoPages,
  employerBrandingPages,
  announcementBanners,
  embedWidgetLayout,
  marketingHeatmapPages,
  brandKits,
  marketingContentItems,
  videos,
  learnVideos,
  pageEmbedVideos,
  creatorYoutubeIngests,
  contentAudiences,
  contentLocations,
  feedPosts,
  feedFeatures,
  eventCategories,
  eventWaitlist,
  eventMatchmaking,
  promoProjects,
  /** Settled money — a boost is paid for before it runs (§5 step 3 narrowed both
   *  checkout tables to order satellites). */
  entity(boostCheckouts, { readOnly: true }),
  /** An affiliate referral is what the ledger pays a commission against. */
  entity(affiliateReferrals, { readOnly: true }),
  /** Observations and sends: captured by a sweep, not authored. */
  entity(activityFeed, { readOnly: true }),
  entity(marketingSessionPrompts, { readOnly: true }),
  entity(marketingHeatmapScreenshots, { readOnly: true }),
  entity(eventRemindersSent, { readOnly: true }),
]);
