/**
 * Topic Grouping Feature - Main Export
 *
 * This module provides automatic chat topic detection and grouping functionality
 * to reduce visual clutter and improve information retrieval.
 *
 * Main features:
 * - Automatic topic identification based on chat content analysis
 * - Grouping chats by detected topics (PRD, Agent Creation, PWA, and more)
 * - User-initiated group operations (rename, merge, move, ungroup)
 * - Dynamic re-evaluation when new messages arrive
 */

// Types
export * from '../types/chat';
export * from '../types/group';

// Topic Detection Utilities
export {
  categorizeChat,
  detectTopic,
  identifyPrimaryTopic,
  groupChatsByTopic,
  analyzeChats,
  isLowActivityChat,
  generateGroupedAnalysis,
  createAutoGeneratedGroup,
  TYPE_TOPICS_KEYWORDS,
  CATEGORY_DISPLAY_MAP,
  CATEGORY_EMOJI_MAP,
  CATEGORY_COLOR_MAP,
} from './topicDetection';

// Group Management Utilities
export {
  createCustomGroup,
  renameGroup,
  mergeGroups,
  moveChat,
  ungroupChat,
  getAllChatIds,
  getChatGroups,
  sortGroupsByCount,
  getTopGroups,
  isGroupNameUnique,
} from './groupManagement';

// API Client
export * from './topicGroupApi';