/**
 * Topic detection utilities for chat grouping
 *
 * Analyzes chat titles and messages to identify dominant topics and
 * categorize chats into meaningful groups.
 */

import type {
  Chat,
  ChatMessage,
  TopicDetectionResult,
  TopicCategory,
  AutoGeneratedGroup,
} from '../types/chat';

/**
 * Keyword patterns for different topic categories
 */
const TOPIC_KEYWORDS: Record<TopicCategory, RegExp[]> = {
  prd: [
    /requirements?/i,
    /specifications?/i,
    /user stories?/i,
    /product requirements?/i,
    /prd/i,
    /user journey/i,
    /backlog/i,
    /epic/i,
    /story/i,
    /story point/i,
    /acceptance criteria/i,
  ],
  'agent-creation': [
    /new agent/i,
    /auto agent/i,
    /create agent/i,
    /agent persona/i,
    /agent configuration/i,
    /agent integration/i,
    /tool integration/i,
    /plugin/i,
    /agent deployment/i,
  ],
  pwa: [
    /progressive web app/i,
    /pwa/i,
    /install.*home/i,
    /offline/i,
    /progressive/i,
    /app manifest/i,
    /service worker/i,
    /add to homescreen/i,
  ],
  general: [/^[\s\n\t]+$/, /^attachment$/i, /^file$/i, /^system/i],
  dev: [
    /developer/i,
    /pull request/i,
    /merge/i,
    /commit/i,
    /feature/i,
    /engineer/i,
    /implementation/i,
    /refactor/i,
    /migration/i,
    /architect/i,
    /review/i,
    /code review/i,
  ],
  design: [
    /design/i,
    /mock up/i,
    /prototype/i,
    /ux/i,
    /ui/i,
    /wireframe/i,
    /low fidelity/i,
    /high fidelity/i,
    /color palette/i,
    /typography/i,
    /design system/i,
  ],
  docs: [
    /documentation/i,
    /doc/i,
    /wiki/i,
    /how to/i,
    /tutorial/i,
    /onboarding/i,
    /kb/,
    /knowledge base/i,
  ],
  bug: [
    /bug/i,
    /issue/i,
    /report/i,
    /todo/i,
    /fix/i,
    /crash/i,
    /error/i,
    /broken/i,
    /defect/i,
    /won't fix/,
    /duplicate/i,
  ],
  feature: [
    /feature/i,
    /add/i,
    /enhance/i,
    /improve/i,
    /new capability/i,
    /new functionality/i,
    /upgrade/i,
  ],
  meeting: [
    /meeting/i,
    /standup/i,
    /daily/i,
    /planning/i,
    /retrospective/i,
    /qbr/i,
    /qpr/i,
    /sync/i,
    /debrief/i,
  ],
  ops: [
    /ops/i,
    /infra/i,
    /deployment/i,
    /deploy/i,
    /ci\/cd/i,
    /pipeline/i,
    /scheduler/i,
    /cron/i,
    /backup/i,
    /devops/i,
  ],
  qa: [
    /qa/i,
    /test/i,
    /testing/i,
    /e2e/i,
    /integration test/i,
    /unit test/i,
    /coverage/i,
    /acceptance test/i,
  ],
  infrastructure: [
    /server/i,
    /database/i,
    /postgres/i,
    /mysql/i,
    /redis/i,
    /aws/i,
    /azure/i,
    /gcp/i,
    /kubernetes/i,
    /container/i,
    /docker/i,
    /compose/i,
    /infrastructure as code/i,
  ],
  security: [
    /security/i,
    /auth/i,
    /oauth/i,
    /jwt/i,
    /token/i,
    /permission/i,
    /role-based/i,
    /authorization/i,
    /login/i,
    /signin/i,
  ],
  analytics: [
    /analytics/i,
    /metric/i,
    /dashboard/i,
    /reporting/i,
    /data/i,
    /visualization/i,
    /stats/i,
    /telemetry/i,
  ],
  migration: [
    /migration/i,
    /upgrade/i,
    /v2/i,
    /transition/i,
    /transition to v2/i,
    /breaking change/i,
  ],
  deployment: [
    /deploy/i,
    /release/i,
    /production/i,
    /staging/i,
    /promote/i,
    /release notes/i,
  ],
  other: [/^[\s\n\t]+$/, /^[\W\d]$/i],
};

/**
 * Category to display mapping
 */
const CATEGORY_DISPLAY_MAP: Record<TopicCategory, string> = {
  prd: 'PRD Work',
  'agent-creation': 'Agent Creation',
  pwa: 'PWA',
  general: 'General',
  dev: 'Development',
  design: 'Design',
  docs: 'Documentation',
  bug: 'Bug Reports',
  feature: 'Features',
  meeting: 'Meetings',
  ops: 'Operations',
  qa: 'Quality Assurance',
  infrastructure: 'Infrastructure',
  security: 'Security',
  analytics: 'Analytics',
  migration: 'Migration',
  deployment: 'Deployments',
  other: 'Other',
};

/**
 * Category to emoji mapping for visual grouping
 */
const CATEGORY_EMOJI_MAP: Record<TopicCategory, string> = {
  prd: '📋',
  'agent-creation': '🤖',
  pwa: '📱',
  general: '💬',
  dev: '💻',
  design: '🎨',
  docs: '📚',
  bug: '🐛',
  feature: '✨',
  meeting: '👥',
  ops: '⚙️',
  qa: '✅',
  infrastructure: '🏗️',
  security: '🔒',
  analytics: '📊',
  migration: '🔄',
  deployment: '🚀',
  other: '📎',
};

/**
 * Category to color mapping
 */
const CATEGORY_COLOR_MAP: Record<TopicCategory, string> = {
  prd: '#6366f1',
  'agent-creation': '#8b5cf6',
  pwa: '#0ea5e9',
  general: '#94a3b8',
  dev: '#3b82f6',
  design: '#ec4899',
  docs: '#f59e0b',
  bug: '#ef4444',
  feature: '#10b981',
  meeting: '#a855f7',
  ops: '#14b8a6',
  qa: '#06b6d4',
  infrastructure: '#64748b',
  security: '#dc2626',
  analytics: '#8b5cf6',
  migration: '#f97316',
  deployment: '#14b8a6',
  other: '#64748b',
};

/**
 * Determine the category of a chat based on its content
 */
export function categorizeChat(
  chat: Chat,
  threshold: number = 0.5
): TopicCategory {
  const messages = chat.messages;
  const textContent = [
    chat.title,
    ...messages.map((m) => m.text),
  ].join(' ').toLowerCase();

  let bestCategory: TopicCategory = 'other';
  let maxScore = 0;

  for (const [category, patterns] of Object.entries(TOPIC_KEYWORDS)) {
    let score = 0;
    const matchedKeywords: string[] = [];

    for (const pattern of patterns) {
      const match = textContent.match(pattern);
      if (match) {
        score += 1;
        matchedKeywords.push(match[0]);
      }
    }

    // Boost score for exact matches
    if (chat.title.toLowerCase().includes(category)) {
      score += 2;
    }

    // Boost score for high message count in category
    if (category === 'bug' && messages.length > 3) {
      score += 0.5;
    }

    if (score > maxScore && score / patterns.length >= threshold) {
      maxScore = score;
      bestCategory = category as TopicCategory;
    }
  }

  // Special case: if no strong match but chat is very long, could be dev/general
  if (bestCategory === 'other' && messages.length > 20) {
    bestCategory = 'dev';
  }

  return bestCategory;
}

/**
 * Detect the dominant topic for a chat and calculate confidence
 */
export function detectTopic(
  chat: Chat,
  threshold: number = 0.5
): TopicDetectionResult {
  const messages = chat.messages;
  const textContent = [
    chat.title,
    ...messages.map((m) => m.text),
  ].join(' ').toLowerCase();

  const detections: [TopicCategory, number][] = [];

  for (const [category, patterns] of Object.entries(TOPIC_KEYWORDS)) {
    let hits = 0;
    for (const pattern of patterns) {
      if (pattern.test(textContent)) {
        hits++;
      }
    }

    if (hits > 0) {
      detections.push([category as TopicCategory, hits]);
    }
  }

  if (detections.length === 0) {
    return {
      topic: 'general',
      confidence: 0.3,
      keywords: [],
    };
  }

  // Find best matching category
  detections.sort((a, b) => b[1] - a[1]);
  const [bestCategory, bestHits] = detections[0];
  const confidence = Math.min(bestHits / TOPIC_KEYWORDS[bestCategory].length, 1);

  // Collect matched keywords
  const matchedKeywords: string[] = [];
  for (const pattern of TOPIC_KEYWORDS[bestCategory]) {
    const match = textContent.match(pattern);
    if (match) {
      // Clean up the matched text
      const cleanMatch = match[0].replace(/[/_]/g, ' ').toLowerCase();
      if (!matchedKeywords.includes(cleanMatch)) {
        matchedKeywords.push(cleanMatch);
      }
    }
  }

  return {
    topic: bestCategory,
    confidence,
    keywords: [...new Set(matchedKeywords)],
  };
}

/**
 * Create an auto-generated group from a category
 */
export function createAutoGeneratedGroup(category: TopicCategory): AutoGeneratedGroup {
  return {
    id: `auto-${category}`,
    name: CATEGORY_DISPLAY_MAP[category],
    category,
    description: `${CATEGORY_DISPLAY_MAP[category]} discussions`,
    emoji: CATEGORY_EMOJI_MAP[category],
    color: CATEGORY_COLOR_MAP[category],
  };
}

/**
 * Identify the primary topic category for a chat
 */
export function identifyPrimaryTopic(chat: Chat): string {
  const result = detectTopic(chat, 0.4);
  return result.topic === 'general' ? 'other' : result.topic;
}

/**
 * Analyze multiple chats and generate groups
 */
export function groupChatsByTopic(
  chats: Chat[],
  options: {
    minGroupSize?: number;
    defaultCategory?: TopicCategory;
  } = {}
): Map<string, Chat[]> {
  const { minGroupSize = 2, defaultCategory = 'other' } = options;

  const categoryChats = new Map<TopicCategory, Chat[]>();

  // Categorize each chat
  for (const chat of chats) {
    const category = categorizeChat(chat, 0.3);
    if (!categoryChats.has(category)) {
      categoryChats.set(category, []);
    }
    categoryChats.get(category)!.push(chat);
  }

  // Filter groups below minimum size
  for (const [category, chats] of categoryChats.entries()) {
    if (chats.length < minGroupSize) {
      const otherChats = categoryChats.get(defaultCategory) || [];
      categoryChats.set(defaultCategory, [...otherChats, ...chats]);
      categoryChats.delete(category);
    }
  }

  return categoryChats;
}

/**
 * Convert grouped chats map to an analysis result
 */
export function analyzeChats(chats: Chat[]): {
  groups: Map<string, Chat[]>;
  topTopicsByChatCount: { topic: string; count: number }[];
  topicOccurrences: Record<string, number>;
} {
  const groups = groupChatsByTopic(chats);
  const categoryCounts: Record<string, number> = {};

  for (const [, chatList] of groups.entries()) {
    categoryCounts[chatList[0].id] = chatList.length;
  }

  const sortedTopics = Object.entries(categoryCounts)
    .sort((a, b) => b[1] - a[1])
    .map(([topic, count]) => ({ topic, count }));

  return {
    groups,
    topTopicsByChatCount: sortedTopics,
    topicOccurrences: categoryCounts,
  };
}

/**
 * Check if a chat is "empty" or low-activity
 */
export function isLowActivityChat(chat: Chat, threshold: number = 10): boolean {
  return chat.messages.length < threshold;
}

/**
 * Generate a grouped analysis for the PRD acceptance criteria
 */
export function generateGroupedAnalysis(
  chats: Chat[]
): {
  prdChats: Chat[];
  agentCreationChats: Chat[];
  pwaChats: Chat[];
  generalChats: Chat[];
  otherGroups: Map<string, Chat[]>;
  groupedCount: number;
  ungroupedCount: number;
} {
  const categories = ['prd', 'agent-creation', 'pwa', 'general'];
  const groups = new Map<string, Chat[]>();

  // Separate high-confidence PWA chats
  const pwaChats = chats.filter((chat) => identifyPrimaryTopic(chat) === 'pwa');

  // Separate PRD chats
  const prdChats = chats.filter((chat) => identifyPrimaryTopic(chat) === 'prd');

  // Separate agent creation chats
  const agentCreationChats = chats.filter(
    (chat) => identifyPrimaryTopic(chat) === 'agent-creation'
  );

  // Determine general or other chats
  const coreChats = chats.filter(
    (chat) =>
      identifyPrimaryTopic(chat) !== 'pwa' &&
      identifyPrimaryTopic(chat) !== 'prd' &&
      identifyPrimaryTopic(chat) !== 'agent-creation'
  );

  for (const category of coreChats) {
    const topic = identifyPrimaryTopic(category);
    if (categories.includes(topic as any)) {
      if (!groups.has(topic as any)) {
        groups.set(topic as any, []);
      }
      groups.get(topic as any)!.push(category);
    } else {
      if (!groups.has('other')) {
        groups.set('other', []);
      }
      groups.get('other')!.push(category);
    }
  }

  const groupedCount = groups.size;
  const ungroupedCount = chats.length - Object.values(groups).flat().length;

  return {
    prdChats,
    agentCreationChats,
    pwaChats,
    generalChats: groups.get('general') || [],
    otherGroups: groups,
    groupedCount,
    ungroupedCount,
  };
}