/**
 * The brand's FACTS — names, URLs, dates, image dimensions — and the ids the
 * brand's copy is filed under.
 *
 * Every sentence the brand says lives in the five message catalogs under
 * `marketing.content.*`, so a locale translates the brand rather than inheriting
 * an English one. What stays here is what does not translate: the product name
 * (a brand token), the site origin, the founder's profile route, and the
 * `dateModified` every JSON-LD graph stamps.
 */

const SITE_URL = 'https://builderforce.ai';

/**
 * The founder's public profile lives on THIS platform, not on hired.video.
 *
 * `/talent/<slug>` is the published for-hire listing (`freelancer_profiles`) and it
 * renders the résumé projection the API serves at `GET /api/freelancers/:id` — the
 * route comment there calls it, in as many words, "the replacement for the hired.video
 * iframe". Linking out to the old host sent every visitor and every crawler that reads
 * our `Person` JSON-LD to a different domain to see a document we already publish.
 *
 * Kept as a path + a derived absolute URL because both audiences need it: the footer
 * and prose links want an in-app route, structured data wants an absolute `Person.url`.
 */
const FOUNDER_PROFILE_PATH = '/talent/seanhogg';

export const BRAND = {
  name: 'Builderforce.ai',
  legalName: 'Builderforce',
  url: SITE_URL,
  founder: { name: 'Sean Hogg', path: FOUNDER_PROFILE_PATH, url: `${SITE_URL}${FOUNDER_PROFILE_PATH}` },
  year: 2026,
  ogImage: '/og-image.png',
  ogImageWidth: 1200,
  ogImageHeight: 630,
  /** ISO 8601 — update on each content deploy */
  dateModified: '2026-08-04T00:00:00Z',
} as const;

/**
 * Quotable one-liners for AI citability — each resolves
 * `marketing.content.quotable.<id>`. `creativeCanvas` is the site summary (the
 * footer, and the `description` of every SoftwareApplication node); the full set
 * is the homepage graph's `featureList`.
 */
export const QUOTABLE_IDS = [
  'creativeCanvas',
  'evermind',
  'systemOfRecord',
  'defineANeed',
  'enterpriseInnovation',
  'roleBasedInsight',
  'humanInLoopAgentic',
  'trainAndUseLoop',
  'neverLeaveVsCode',
  'aiExecutiveTeam',
  'freeForever',
  'agenticTester',
  'collaboration',
  'teamChat',
  'meetings',
  'vsCodeCommandCenter',
  'zeroGpuBills',
  'browserNative',
  'datasetSpeed',
  'privacy',
] as const;

export type QuotableId = (typeof QUOTABLE_IDS)[number];

/**
 * Evermind — Builderforce's self-updating model and the "brain" of the platform.
 *
 * `name` is a brand token and never translated. Everything Evermind SAYS — its
 * SEO copy, pillars, edges and FAQ — is the `evermind` catalog namespace, which
 * `/evermind` renders and `evermindSchema()` emits. The pillar ICONS pair with
 * `evermind.architecture.pillars` by index, so the two stay the same length.
 */
export const EVERMIND = {
  name: 'Evermind',
  pillarIcons: ['🧠', '⚡', '🔁', '❤️'],
} as const;

/* ════════════════════ MEDIA KIT ════════════════════ */

export interface MediaAsset {
  /** Stable key — localized name/description live at `media.assets.<key>.*`. */
  key: 'pdf' | 'pptx' | 'slides';
  href: string;
  /** Non-translatable format token shown on the download card. */
  format: string;
  /** Approximate download size, shown verbatim. */
  size: string;
}

/**
 * Downloadable marketing media (the sales deck + per-slide PNGs), served from
 * `public/media/`. Regenerated by `Builderforce.ai/marketing/pitch-deck/`
 * (see its README) — copy new builds into `public/media/` to update the site.
 */
export const MEDIA_KIT: { cover: string; coverWidth: number; coverHeight: number; assets: MediaAsset[] } = {
  cover: '/media/deck-cover.png',
  coverWidth: 1280,
  coverHeight: 720,
  assets: [
    { key: 'pdf', href: '/media/Builderforce-Pitch-Deck.pdf', format: 'PDF', size: '5 MB' },
    { key: 'pptx', href: '/media/Builderforce-Pitch-Deck.pptx', format: 'PPTX', size: '11 MB' },
    { key: 'slides', href: '/media/Builderforce-Deck-Slides.zip', format: 'ZIP · 26 PNG', size: '11 MB' },
  ],
};
