/**
 * BPMN 2.0 reader and writer.
 *
 * BPMN is the one notation here that is not really a drawing — it is a PROCESS
 * DEFINITION that happens to have a picture attached. The XML says which step
 * follows which, which branch is exclusive, where the process starts and where
 * it ends, and every process engine (Camunda, Flowable, Zeebe, jBPM) reads the
 * same file. That is why it earns a reader AND a writer: a process drawn on
 * this canvas can leave as something a workflow engine executes, and a process
 * that already runs somewhere can arrive as something a person can redraw.
 *
 * ── THE TWO HALVES OF A BPMN FILE ────────────────────────────────────────────
 * `<process>` holds the SEMANTICS — the tasks, gateways, events and sequence
 * flows. `<BPMNDiagram>` holds the DIAGRAM INTERCHANGE: a `<BPMNShape>` per
 * element with real coordinates, and a `<BPMNEdge>` per flow with waypoints.
 *
 * A file generated by code frequently has the first and not the second. Rather
 * than refusing those, the geometry is laid out from the sequence flows — a
 * process with no drawing is still a process, and it is exactly the case where
 * a person most wants to SEE it.
 */

import {
  DIAGRAM_DEFAULT_FONT_SIZE, MAX_DIAGRAM_CELLS, diagramGraph, layoutDiagramGraph,
  type DiagramEdge, type DiagramGraph, type DiagramShape, type DiagramVertex, type LayoutLink, type LayoutNode,
} from './diagramGraph';

const BPMN_MARKER = /<(?:\w+:)?definitions[\s>][\s\S]{0,4000}?BPMN\/20100524|<(?:\w+:)?(?:process|collaboration)\b[\s\S]{0,2000}?<(?:\w+:)?(?:task|startEvent|sequenceFlow)\b/i;

export function isBpmnSource(source: string): boolean {
  return BPMN_MARKER.test(source.slice(0, 8_000));
}

/** How each BPMN element type draws. Matched on the local name, so the file's
 * namespace prefix (`bpmn:`, `bpmn2:`, `semantic:`, or none) is irrelevant. */
function shapeForElement(localName: string): DiagramShape {
  const name = localName.toLowerCase();
  if (name.endsWith('gateway')) return 'rhombus';
  if (name.endsWith('event')) return 'ellipse';
  if (name === 'datastorereference' || name === 'datastore') return 'cylinder';
  if (name === 'dataobjectreference' || name === 'dataobject') return 'note';
  if (name === 'textannotation') return 'note';
  if (name === 'subprocess' || name === 'transaction' || name === 'callactivity') return 'rect';
  return 'rounded';
}

/** Elements that are steps in a process, as opposed to flows, lanes or DI. */
const FLOW_NODE = /(?:task|event|gateway|subprocess|transaction|callactivity|dataobjectreference|datastorereference|textannotation)$/i;

function localName(element: Element): string {
  return element.localName || element.tagName.replace(/^.*:/, '');
}

function numeric(value: string | null, fallback = 0): number {
  const parsed = Number(value);
  return Number.isFinite(parsed) ? parsed : fallback;
}

function parseXml(source: string): Document | null {
  if (typeof DOMParser === 'undefined') return null;
  try {
    const document = new DOMParser().parseFromString(source, 'application/xml');
    return document.getElementsByTagName('parsererror').length ? null : document;
  } catch {
    return null;
  }
}

export function readBpmn(source: string): DiagramGraph | null {
  const document = parseXml(source);
  if (!document) return null;
  const all = Array.from(document.getElementsByTagName('*'));
  if (!all.some((element) => localName(element).toLowerCase() === 'definitions' || FLOW_NODE.test(localName(element)))) return null;

  const steps = new Map<string, { label: string; shape: DiagramShape }>();
  const flows: Array<{ id: string; source: string; target: string; label: string; dashed: boolean }> = [];

  for (const element of all) {
    const name = localName(element);
    const id = element.getAttribute('id');
    if (!id) continue;
    if (FLOW_NODE.test(name) && steps.size < MAX_DIAGRAM_CELLS) {
      const text = element.getAttribute('name')
        ?? Array.from(element.children).find((child) => localName(child).toLowerCase() === 'text')?.textContent
        ?? '';
      steps.set(id, { label: text.replace(/\s+/g, ' ').trim(), shape: shapeForElement(name) });
      continue;
    }
    const lower = name.toLowerCase();
    if (lower === 'sequenceflow' || lower === 'messageflow' || lower === 'association' || lower === 'dataassociation') {
      const from = element.getAttribute('sourceRef');
      const to = element.getAttribute('targetRef');
      if (from && to) flows.push({ id, source: from, target: to, label: element.getAttribute('name') ?? '', dashed: lower !== 'sequenceflow' });
    }
  }
  if (!steps.size) return null;

  /* --- geometry, when the file carries diagram interchange --------------- */
  const boundsByElement = new Map<string, { x: number; y: number; width: number; height: number }>();
  const waypointsByElement = new Map<string, Array<{ x: number; y: number }>>();
  for (const element of all) {
    const name = localName(element).toLowerCase();
    const target = element.getAttribute('bpmnElement');
    if (!target) continue;
    if (name === 'bpmnshape') {
      const bounds = Array.from(element.children).find((child) => localName(child).toLowerCase() === 'bounds');
      if (bounds) {
        boundsByElement.set(target, {
          x: numeric(bounds.getAttribute('x')),
          y: numeric(bounds.getAttribute('y')),
          width: Math.max(numeric(bounds.getAttribute('width'), 100), 1),
          height: Math.max(numeric(bounds.getAttribute('height'), 60), 1),
        });
      }
      continue;
    }
    if (name === 'bpmnedge') {
      const points = Array.from(element.children)
        .filter((child) => localName(child).toLowerCase() === 'waypoint')
        .map((point) => ({ x: numeric(point.getAttribute('x')), y: numeric(point.getAttribute('y')) }));
      if (points.length >= 2) waypointsByElement.set(target, points);
    }
  }

  const positioned = [...steps.keys()].filter((id) => boundsByElement.has(id));
  if (!positioned.length) {
    // No diagram interchange: the process is real, the drawing is not. Lay it
    // out from the flows rather than refusing a file that has everything that
    // matters in it.
    const nodes: LayoutNode[] = [...steps.entries()].map(([id, step]) => ({ id, label: step.label || id, shape: step.shape }));
    const links: LayoutLink[] = flows.map((flow) => ({ source: flow.source, target: flow.target, label: flow.label, dashed: flow.dashed, arrow: true }));
    return layoutDiagramGraph(nodes, links);
  }

  const vertices: DiagramVertex[] = positioned.map((id) => {
    const bounds = boundsByElement.get(id)!;
    const step = steps.get(id)!;
    return { id, label: step.label || '', ...bounds, shape: step.shape, fontSize: DIAGRAM_DEFAULT_FONT_SIZE, dashed: false };
  });
  const known = new Set(positioned);
  const edges: DiagramEdge[] = flows.flatMap((flow) => {
    const points = waypointsByElement.get(flow.id);
    if (!points) return [];
    return [{
      id: flow.id,
      label: flow.label,
      points,
      dashed: flow.dashed,
      arrow: true,
      ...(known.has(flow.source) ? { source: flow.source } : {}),
      ...(known.has(flow.target) ? { target: flow.target } : {}),
    }];
  });
  return diagramGraph(vertices, edges);
}

/* ------------------------------------------------------------- writer --- */

/** BPMN ids are XML NCNames: they may not start with a digit and may not carry
 * spaces or punctuation an XML parser would reject. */
function ncName(value: string, prefix: string): string {
  const cleaned = value.replace(/[^A-Za-z0-9_-]/g, '_').replace(/^[^A-Za-z_]+/, '');
  return `${prefix}_${cleaned || 'x'}`.slice(0, 60);
}

function xmlAttribute(value: string): string {
  return value.replaceAll('&', '&amp;').replaceAll('"', '&quot;').replaceAll('<', '&lt;').replaceAll('>', '&gt;').replaceAll('\n', ' ');
}

/**
 * The BPMN element a shape becomes.
 *
 * An ellipse is an EVENT, and which event it is depends on where it sits in the
 * flow: nothing coming in makes it a start, nothing going out makes it an end.
 * Getting that wrong produces a file that opens and then fails validation in
 * every engine, so it is derived rather than guessed.
 */
function bpmnElementFor(vertex: DiagramVertex, incoming: number, outgoing: number): string {
  if (vertex.shape === 'rhombus') return 'exclusiveGateway';
  if (vertex.shape === 'note') return 'textAnnotation';
  if (vertex.shape === 'cylinder') return 'dataStoreReference';
  if (vertex.shape === 'ellipse') {
    // An event joined at both ends is an intermediate one. An ISOLATED ellipse
    // (neither in nor out) is a start event: a process must have one, and a
    // drawing that has not been wired up yet is far more likely to be missing
    // its flows than to be a lone terminator.
    if (!incoming) return 'startEvent';
    if (!outgoing) return 'endEvent';
    return 'intermediateThrowEvent';
  }
  return 'task';
}

export function writeBpmn(graph: DiagramGraph): string {
  const ids = new Map(graph.vertices.map((vertex) => [vertex.id, ncName(vertex.id, 'Node')] as const));
  const incoming = new Map<string, number>();
  const outgoing = new Map<string, number>();
  const usable = graph.edges.filter((edge) => edge.source && edge.target && ids.has(edge.source) && ids.has(edge.target));
  for (const edge of usable) {
    outgoing.set(edge.source!, (outgoing.get(edge.source!) ?? 0) + 1);
    incoming.set(edge.target!, (incoming.get(edge.target!) ?? 0) + 1);
  }

  const kinds = new Map(graph.vertices.map((vertex) =>
    [vertex.id, bpmnElementFor(vertex, incoming.get(vertex.id) ?? 0, outgoing.get(vertex.id) ?? 0)] as const));
  const flowIds = new Map(usable.map((edge, index) => [edge.id, `Flow_${index + 1}`] as const));

  const elements = graph.vertices.map((vertex) => {
    const kind = kinds.get(vertex.id)!;
    const id = ids.get(vertex.id)!;
    const label = xmlAttribute(vertex.label);
    // A text annotation carries its content as a child, not as `name`.
    if (kind === 'textAnnotation') return `    <bpmn:textAnnotation id="${id}"><bpmn:text>${label}</bpmn:text></bpmn:textAnnotation>`;
    return `    <bpmn:${kind} id="${id}"${label ? ` name="${label}"` : ''} />`;
  });

  const flows = usable.map((edge) => {
    // An arrow touching an annotation is an association in BPMN; a sequence
    // flow to one is invalid and every engine rejects the file.
    const annotation = kinds.get(edge.source!) === 'textAnnotation' || kinds.get(edge.target!) === 'textAnnotation';
    const tag = annotation ? 'association' : 'sequenceFlow';
    const label = !annotation && edge.label ? ` name="${xmlAttribute(edge.label)}"` : '';
    return `    <bpmn:${tag} id="${flowIds.get(edge.id)}" sourceRef="${ids.get(edge.source!)}" targetRef="${ids.get(edge.target!)}"${label} />`;
  });

  const shapes = graph.vertices.map((vertex) =>
    `      <bpmndi:BPMNShape id="${ids.get(vertex.id)}_di" bpmnElement="${ids.get(vertex.id)}"><dc:Bounds x="${Math.round(vertex.x)}" y="${Math.round(vertex.y)}" width="${Math.round(vertex.width)}" height="${Math.round(vertex.height)}" /></bpmndi:BPMNShape>`);

  const diEdges = usable.map((edge) => {
    const points = edge.points.length >= 2 ? edge.points : [{ x: 0, y: 0 }, { x: 0, y: 0 }];
    const waypoints = points.map((point) => `<di:waypoint x="${Math.round(point.x)}" y="${Math.round(point.y)}" />`).join('');
    return `      <bpmndi:BPMNEdge id="${flowIds.get(edge.id)}_di" bpmnElement="${flowIds.get(edge.id)}">${waypoints}</bpmndi:BPMNEdge>`;
  });

  return [
    '<?xml version="1.0" encoding="UTF-8"?>',
    '<bpmn:definitions xmlns:bpmn="http://www.omg.org/spec/BPMN/20100524/MODEL" xmlns:bpmndi="http://www.omg.org/spec/BPMN/20100524/DI" xmlns:dc="http://www.omg.org/spec/DD/20100524/DC" xmlns:di="http://www.omg.org/spec/DD/20100524/DI" id="Definitions_1" targetNamespace="http://bpmn.io/schema/bpmn" exporter="Builderforce Creation Canvas">',
    '  <bpmn:process id="Process_1" isExecutable="false">',
    ...elements,
    ...flows,
    '  </bpmn:process>',
    '  <bpmndi:BPMNDiagram id="BPMNDiagram_1">',
    '    <bpmndi:BPMNPlane id="BPMNPlane_1" bpmnElement="Process_1">',
    ...shapes,
    ...diEdges,
    '    </bpmndi:BPMNPlane>',
    '  </bpmndi:BPMNDiagram>',
    '</bpmn:definitions>',
    '',
  ].join('\n');
}
