import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest';
import {
  MambaModelProvider,
  ExternalLLMProvider,
  registerProvider,
  unregisterProvider,
  getProvider,
  listProviders,
  createExternalLLMProvider,
} from './model-provider';

// ---------------------------------------------------------------------------
// Mock sendAIMessage so ExternalLLMProvider tests don't hit the network
// ---------------------------------------------------------------------------

vi.mock('./api', () => ({
  sendAIMessage: vi.fn(),
  downloadDataset: vi.fn().mockResolvedValue(''),
  uploadArtifact: vi.fn().mockResolvedValue({ r2Key: 'adapters/test.bin' }),
  updateTrainingJob: vi.fn().mockResolvedValue(undefined),
  streamTrainingLogs: vi.fn().mockResolvedValue(undefined),
}));

import { sendAIMessage } from './api';
const mockSendAIMessage = sendAIMessage as ReturnType<typeof vi.fn>;

import { WebGPUTrainer, type TrainingStep, type WebGPUTrainerOptions } from './webgpu-trainer';

// ---------------------------------------------------------------------------
// MambaModelProvider
// ---------------------------------------------------------------------------

describe('MambaModelProvider', () => {
  it('has correct identity properties', () => {
    const provider = new MambaModelProvider();
    expect(provider.id).toBe('mamba');
    expect(provider.name).toBe('Mamba (On-Device WebGPU)');
    expect(provider.isLocal).toBe(true);
  });

  it('is not ready before init()', () => {
    const provider = new MambaModelProvider();
    expect(provider.isReady()).toBe(false);
  });

  it('gracefully handles missing @seanhogg/builderforce-memory-engine at init()', async () => {
    // In jsdom there is no navigator.gpu so @seanhogg/builderforce-memory-engine will throw
    const provider = new MambaModelProvider();
    // Should not throw even if the dynamic import fails
    await expect(provider.init()).resolves.toBeUndefined();
    expect(provider.isReady()).toBe(false);
  });

  it('returns a fallback message when not ready', async () => {
    const provider = new MambaModelProvider();
    const result = await provider.generate('hello');
    expect(result).toContain('not ready');
  });

  it('stream() falls back gracefully when not ready', async () => {
    const tokens: string[] = [];
    const provider = new MambaModelProvider();
    const result = await provider.stream('hello', undefined, (t) => tokens.push(t));
    expect(result).toContain('not ready');
    // The fallback message is word-streamed so at least one token is emitted
    expect(tokens.length).toBeGreaterThan(0);
    expect(tokens.join('').trim()).toContain('not ready');
  });

  it('train() throws when not ready', async () => {
    const provider = new MambaModelProvider();
    await expect(provider.train('some code')).rejects.toThrow('Provider not ready');
  });

  it('exportTrainedWeights() throws when not ready (no placeholder bytes)', async () => {
    const provider = new MambaModelProvider();
    await expect(provider.exportTrainedWeights()).rejects.toThrow('Provider not ready');
  });

  it('train() delegates to the REAL MambaTrainer.train (no synthetic loss)', async () => {
    const provider = new MambaModelProvider();
    // White-box: simulate a ready provider with a stub trainer that records the call.
    const realLosses = [2.31, 1.74, 1.12];
    const trainSpy = vi.fn().mockResolvedValue(realLosses);
    (provider as any)._ready = true;
    (provider as any).trainer = { train: trainSpy };

    const epochCb = vi.fn();
    const losses = await provider.train('print("hi")', {
      learningRate: 5e-4,
      epochs: 3,
      onEpochEnd: epochCb,
    });

    // The returned losses are exactly what the real trainer produced — not
    // generated by Math.exp / Math.random in this layer.
    expect(losses).toBe(realLosses);
    expect(trainSpy).toHaveBeenCalledOnce();
    const [text, opts] = trainSpy.mock.calls[0] as [string, Record<string, unknown>];
    expect(text).toBe('print("hi")');
    expect(opts.learningRate).toBe(5e-4);
    expect(opts.epochs).toBe(3);
    expect(opts.onEpochEnd).toBe(epochCb);
  });

  it('exportTrainedWeights() returns REAL serialised weights from the model', async () => {
    const provider = new MambaModelProvider();
    const realBuffer = new ArrayBuffer(128);
    const exportSpy = vi.fn().mockResolvedValue(realBuffer);
    (provider as any)._ready = true;
    (provider as any).model = { exportWeights: exportSpy };

    const out = await provider.exportTrainedWeights({ fp16: true });
    expect(out).toBe(realBuffer);
    expect(exportSpy).toHaveBeenCalledWith({ fp16: true });
  });

  it('dispose() marks the provider as not ready', () => {
    const provider = new MambaModelProvider();
    // Simulate readiness by forcing the internal flag (white-box test)
    (provider as any)._ready = true;
    expect(provider.isReady()).toBe(true);
    provider.dispose();
    expect(provider.isReady()).toBe(false);
  });

  it('accepts custom config', () => {
    const provider = new MambaModelProvider({ dModel: 256, numLayers: 4, wsla: true });
    const cfg = (provider as any).config;
    expect(cfg.dModel).toBe(256);
    expect(cfg.numLayers).toBe(4);
    expect(cfg.wsla).toBe(true);
  });
});

// ---------------------------------------------------------------------------
// ExternalLLMProvider
// ---------------------------------------------------------------------------

describe('ExternalLLMProvider', () => {
  beforeEach(() => {
    mockSendAIMessage.mockReset();
  });

  afterEach(() => {
    vi.restoreAllMocks();
  });

  it('has correct identity properties', () => {
    const provider = new ExternalLLMProvider({ projectId: 'proj-1', label: 'Workers AI' });
    expect(provider.id).toBe('external-llm');
    expect(provider.name).toBe('Workers AI');
    expect(provider.isLocal).toBe(false);
  });

  it('is always ready', () => {
    const provider = new ExternalLLMProvider({ projectId: 'proj-1' });
    expect(provider.isReady()).toBe(true);
  });

  it('generate() calls sendAIMessage and accumulates response', async () => {
    mockSendAIMessage.mockImplementation(
      async (_id: unknown, _msgs: unknown, onChunk: (c: string) => void) => {
        onChunk('Hello');
        onChunk(', world!');
      }
    );
    const provider = new ExternalLLMProvider({ projectId: 'proj-1' });
    const result = await provider.generate('say hello');
    expect(result).toBe('Hello, world!');
    expect(mockSendAIMessage).toHaveBeenCalledOnce();
  });

  it('generate() includes systemPrompt and memoryContext in messages', async () => {
    mockSendAIMessage.mockResolvedValue(undefined);
    const provider = new ExternalLLMProvider({ projectId: 'proj-1' });
    await provider.generate('prompt', {
      systemPrompt: 'Be concise.',
      memoryContext: '[step=3 signal=0.12]',
    });
    const [, messages] = mockSendAIMessage.mock.calls[0] as [
      unknown,
      Array<{ role: string; content: string }>,
    ];
    const sysMsg = messages.find((m) => m.role === 'system');
    expect(sysMsg?.content).toContain('Be concise.');
    expect(sysMsg?.content).toContain('[step=3 signal=0.12]');
  });

  it('stream() calls onToken for each chunk', async () => {
    mockSendAIMessage.mockImplementation(
      async (_id: unknown, _msgs: unknown, onChunk: (c: string) => void) => {
        onChunk('token1');
        onChunk('token2');
      }
    );
    const tokens: string[] = [];
    const provider = new ExternalLLMProvider({ projectId: 'proj-1' });
    const result = await provider.stream('go', undefined, (t) => tokens.push(t));
    expect(tokens).toEqual(['token1', 'token2']);
    expect(result).toBe('token1token2');
  });

  it('generate() uses context.messages when provided', async () => {
    mockSendAIMessage.mockResolvedValue(undefined);
    const provider = new ExternalLLMProvider({ projectId: 'proj-1' });
    await provider.generate('ignored', {
      messages: [
        { role: 'user', content: 'from context' },
      ],
    });
    const [, messages] = mockSendAIMessage.mock.calls[0] as [
      unknown,
      Array<{ role: string; content: string }>,
    ];
    const userMsgs = messages.filter((m) => m.role === 'user');
    expect(userMsgs[0].content).toBe('from context');
  });

  it('uses factory helper createExternalLLMProvider', () => {
    const provider = createExternalLLMProvider({ projectId: 42, label: 'Test' });
    expect(provider).toBeInstanceOf(ExternalLLMProvider);
    expect(provider.name).toBe('Test');
  });
});

// ---------------------------------------------------------------------------
// Provider registry
// ---------------------------------------------------------------------------

describe('provider registry', () => {
  afterEach(() => {
    unregisterProvider('mamba');
    unregisterProvider('external-llm');
    unregisterProvider('test-provider');
  });

  it('registers and retrieves a provider by id', () => {
    const provider = new ExternalLLMProvider({ projectId: 'p', label: 'Test' });
    registerProvider(provider);
    expect(getProvider('external-llm')).toBe(provider);
  });

  it('listProviders() returns all registered providers', () => {
    const p1 = new ExternalLLMProvider({ projectId: 'p', label: 'External' });
    const p2 = new MambaModelProvider();
    registerProvider(p1);
    registerProvider(p2);
    const all = listProviders();
    expect(all).toContain(p1);
    expect(all).toContain(p2);
  });

  it('unregisterProvider() removes a provider', () => {
    const provider = new ExternalLLMProvider({ projectId: 'p', label: 'Temp' });
    registerProvider(provider);
    expect(getProvider('external-llm')).toBe(provider);
    unregisterProvider('external-llm');
    expect(getProvider('external-llm')).toBeUndefined();
  });

  it('getProvider() returns undefined for unknown ids', () => {
    expect(getProvider('does-not-exist')).toBeUndefined();
  });
});

// ---------------------------------------------------------------------------
// WebGPUTrainer — real engine wiring (no synthetic loss / no fake fallback)
// ---------------------------------------------------------------------------

describe('WebGPUTrainer (real engine wiring)', () => {
  function makeTrainer(overrides: Partial<WebGPUTrainerOptions> = {}) {
    const logs: string[] = [];
    const trainer = new WebGPUTrainer({
      modelId: 'gpt-neox-20m',
      workerUrl: 'http://localhost',
      projectId: 'proj-1',
      onLog: (m) => logs.push(m),
      onStep: () => {},
      onEpochEnd: () => {},
      onComplete: () => {},
      onError: () => {},
      ...overrides,
    });
    return { trainer, logs };
  }

  it('init() surfaces a REAL error when WebGPU/engine is unavailable (no fake fallback)', async () => {
    // jsdom has no navigator.gpu, so the underlying MambaModelProvider never
    // becomes ready — init must throw rather than silently simulate.
    const { trainer } = makeTrainer();
    await expect(trainer.init()).rejects.toThrow(/WebGPU training engine unavailable/i);
  });

  it('train() refuses to run before a successful init() (no synthetic loop)', async () => {
    const { trainer } = makeTrainer();
    await expect(
      trainer.train(
        {
          epochs: 2,
          batchSize: 4,
          learningRate: 1e-4,
          gradientAccumulationSteps: 1,
          precision: 'float16',
          loraConfig: { rank: 8, alpha: 16, targetModules: ['q_proj'] },
        },
        ['example'],
      ),
    ).rejects.toThrow(/not initialised/i);
  });

  it('drives the REAL MambaModelProvider.train + exportTrainedWeights (real loss + real weights)', async () => {
    const { trainer, logs } = makeTrainer({ jobId: 'job-1' });

    const realLosses = [2.2, 1.5];
    const realWeights = new ArrayBuffer(256);
    const fakeProvider = {
      isReady: () => true,
      train: vi.fn().mockImplementation(
        async (_corpus: string, opts: { onEpochEnd?: (e: number, l: number) => void }) => {
          realLosses.forEach((l, i) => opts.onEpochEnd?.(i + 1, l));
          return realLosses;
        },
      ),
      exportTrainedWeights: vi.fn().mockResolvedValue(realWeights),
      dispose: vi.fn(),
    };

    const steps: TrainingStep[] = [];
    (trainer as any).options.onStep = (s: TrainingStep) => steps.push(s);

    // Inject a ready provider (simulating a successful init on a real GPU).
    (trainer as any).provider = fakeProvider;

    const { uploadArtifact } = await import('./api');
    (uploadArtifact as ReturnType<typeof vi.fn>).mockResolvedValue({ r2Key: 'adapters/real.bin' });

    let completedKey = '';
    (trainer as any).options.onComplete = (k: string) => { completedKey = k; };

    await trainer.train(
      {
        epochs: 2,
        batchSize: 4,
        learningRate: 3e-4,
        gradientAccumulationSteps: 1,
        precision: 'float16',
        loraConfig: { rank: 8, alpha: 16, targetModules: ['q_proj'] },
      },
      ['real training text'],
    );

    // Real trainer was driven, real losses surfaced as steps.
    expect(fakeProvider.train).toHaveBeenCalledOnce();
    expect(steps.map((s) => s.loss)).toEqual(realLosses);
    // Real serialised weights were uploaded (not placeholder bytes).
    expect(fakeProvider.exportTrainedWeights).toHaveBeenCalledOnce();
    expect(uploadArtifact).toHaveBeenCalledWith('job-1', realWeights);
    expect(completedKey).toBe('adapters/real.bin');
  });

  it('source contains no synthetic Math.exp / Math.random loss generation', async () => {
    // Guard against regressions reintroducing the fake loss curve.
    const fs = await import('node:fs');
    const url = await import('node:url');
    const path = await import('node:path');
    const here = path.dirname(url.fileURLToPath(import.meta.url));
    const src = fs.readFileSync(path.join(here, 'webgpu-trainer.ts'), 'utf8');
    expect(src).not.toMatch(/Math\.exp/);
    expect(src).not.toMatch(/Math\.random/);
    // The old "prove GPU writing works" buffer hack must be gone.
    expect(src).not.toMatch(/prove GPU/i);
  });
});
