import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest';
import {
  MambaModelProvider,
  ExternalLLMProvider,
  PromptApiModelProvider,
  CascadingModelProvider,
  createInferenceProvider,
  hasPromptApi,
  type ModelProvider,
} from './model-provider';

// ---------------------------------------------------------------------------
// Mock sendAIMessage so ExternalLLMProvider tests don't hit the network
// ---------------------------------------------------------------------------

vi.mock('./api', () => ({
  sendAIMessage: vi.fn(),
  downloadDataset: vi.fn().mockResolvedValue(''),
  uploadArtifact: vi.fn().mockResolvedValue({ r2Key: 'adapters/test.bin' }),
  updateTrainingJob: vi.fn().mockResolvedValue(undefined),
  streamTrainingLogs: vi.fn().mockResolvedValue(undefined),
}));

import { sendAIMessage } from './api';
const mockSendAIMessage = sendAIMessage as ReturnType<typeof vi.fn>;

import { WebGPUTrainer, type TrainingStep, type WebGPUTrainerOptions } from './webgpu-trainer';

// ---------------------------------------------------------------------------
// MambaModelProvider
// ---------------------------------------------------------------------------

describe('MambaModelProvider', () => {
  it('has correct identity properties', () => {
    const provider = new MambaModelProvider();
    expect(provider.id).toBe('mamba');
    expect(provider.name).toBe('Mamba (On-Device WebGPU)');
    expect(provider.isLocal).toBe(true);
  });

  it('is not ready before init()', () => {
    const provider = new MambaModelProvider();
    expect(provider.isReady()).toBe(false);
  });

  it('gracefully handles missing @seanhogg/builderforce-memory-engine at init()', async () => {
    // In jsdom there is no navigator.gpu so @seanhogg/builderforce-memory-engine will throw
    const provider = new MambaModelProvider();
    // Should not throw even if the dynamic import fails
    await expect(provider.init()).resolves.toBeUndefined();
    expect(provider.isReady()).toBe(false);
  });

  it('returns a fallback message when not ready', async () => {
    const provider = new MambaModelProvider();
    const result = await provider.generate('hello');
    expect(result).toContain('not ready');
  });

  it('stream() falls back gracefully when not ready', async () => {
    const tokens: string[] = [];
    const provider = new MambaModelProvider();
    const result = await provider.stream('hello', undefined, (t) => tokens.push(t));
    expect(result).toContain('not ready');
    // The fallback message is word-streamed so at least one token is emitted
    expect(tokens.length).toBeGreaterThan(0);
    expect(tokens.join('').trim()).toContain('not ready');
  });

  it('train() throws when not ready', async () => {
    const provider = new MambaModelProvider();
    await expect(provider.train('some code')).rejects.toThrow('Provider not ready');
  });

  it('exportTrainedWeights() throws when not ready (no placeholder bytes)', async () => {
    const provider = new MambaModelProvider();
    await expect(provider.exportTrainedWeights()).rejects.toThrow('Provider not ready');
  });

  it('train() delegates to the REAL MambaTrainer.train (no synthetic loss)', async () => {
    const provider = new MambaModelProvider();
    // White-box: simulate a ready provider with a stub trainer that records the call.
    const realLosses = [2.31, 1.74, 1.12];
    const trainSpy = vi.fn().mockResolvedValue(realLosses);
    (provider as any)._ready = true;
    // A ready provider holds the full tokenizer + model + trainer triad. Stub all
    // three: `ensureModelForCorpus` only short-circuits when every one is present,
    // and otherwise falls through to building a real engine model (which throws
    // in jsdom, where there is no WebGPU).
    (provider as any).tokenizer = { vocabSize: 256 };
    (provider as any).model = {};
    (provider as any).trainer = { train: trainSpy };

    const epochCb = vi.fn();
    const losses = await provider.train('print("hi")', {
      learningRate: 5e-4,
      epochs: 3,
      onEpochEnd: epochCb,
    });

    // The returned losses are exactly what the real trainer produced — not
    // generated by Math.exp / Math.random in this layer.
    expect(losses).toBe(realLosses);
    expect(trainSpy).toHaveBeenCalledOnce();
    const [text, opts] = trainSpy.mock.calls[0] as [string, Record<string, unknown>];
    expect(text).toBe('print("hi")');
    expect(opts.learningRate).toBe(5e-4);
    expect(opts.epochs).toBe(3);
    expect(opts.onEpochEnd).toBe(epochCb);
  });

  it('exportTrainedWeights() returns REAL serialised weights from the model', async () => {
    const provider = new MambaModelProvider();
    const realBuffer = new ArrayBuffer(128);
    const exportSpy = vi.fn().mockResolvedValue(realBuffer);
    (provider as any)._ready = true;
    (provider as any).model = { exportWeights: exportSpy };

    const out = await provider.exportTrainedWeights({ fp16: true });
    expect(out).toBe(realBuffer);
    expect(exportSpy).toHaveBeenCalledWith({ fp16: true });
  });

  it('dispose() marks the provider as not ready', () => {
    const provider = new MambaModelProvider();
    // Simulate readiness by forcing the internal flag (white-box test)
    (provider as any)._ready = true;
    expect(provider.isReady()).toBe(true);
    provider.dispose();
    expect(provider.isReady()).toBe(false);
  });

  it('accepts custom config', () => {
    const provider = new MambaModelProvider({ dModel: 256, numLayers: 4, wsla: true });
    const cfg = (provider as any).config;
    expect(cfg.dModel).toBe(256);
    expect(cfg.numLayers).toBe(4);
    expect(cfg.wsla).toBe(true);
  });
});

// ---------------------------------------------------------------------------
// ExternalLLMProvider
// ---------------------------------------------------------------------------

describe('ExternalLLMProvider', () => {
  beforeEach(() => {
    mockSendAIMessage.mockReset();
  });

  afterEach(() => {
    vi.restoreAllMocks();
  });

  it('has correct identity properties', () => {
    const provider = new ExternalLLMProvider({ projectId: 'proj-1', label: 'Workers AI' });
    expect(provider.id).toBe('external-llm');
    expect(provider.name).toBe('Workers AI');
    expect(provider.isLocal).toBe(false);
  });

  it('is always ready', () => {
    const provider = new ExternalLLMProvider({ projectId: 'proj-1' });
    expect(provider.isReady()).toBe(true);
  });

  it('generate() calls sendAIMessage and accumulates response', async () => {
    mockSendAIMessage.mockImplementation(
      async (_id: unknown, _msgs: unknown, onChunk: (c: string) => void) => {
        onChunk('Hello');
        onChunk(', world!');
      }
    );
    const provider = new ExternalLLMProvider({ projectId: 'proj-1' });
    const result = await provider.generate('say hello');
    expect(result).toBe('Hello, world!');
    expect(mockSendAIMessage).toHaveBeenCalledOnce();
  });

  it('generate() includes systemPrompt and memoryContext in messages', async () => {
    mockSendAIMessage.mockResolvedValue(undefined);
    const provider = new ExternalLLMProvider({ projectId: 'proj-1' });
    await provider.generate('prompt', {
      systemPrompt: 'Be concise.',
      memoryContext: '[step=3 signal=0.12]',
    });
    const [, messages] = mockSendAIMessage.mock.calls[0] as [
      unknown,
      Array<{ role: string; content: string }>,
    ];
    const sysMsg = messages.find((m) => m.role === 'system');
    expect(sysMsg?.content).toContain('Be concise.');
    expect(sysMsg?.content).toContain('[step=3 signal=0.12]');
  });

  it('stream() calls onToken for each chunk', async () => {
    mockSendAIMessage.mockImplementation(
      async (_id: unknown, _msgs: unknown, onChunk: (c: string) => void) => {
        onChunk('token1');
        onChunk('token2');
      }
    );
    const tokens: string[] = [];
    const provider = new ExternalLLMProvider({ projectId: 'proj-1' });
    const result = await provider.stream('go', undefined, (t) => tokens.push(t));
    expect(tokens).toEqual(['token1', 'token2']);
    expect(result).toBe('token1token2');
  });

  it('generate() uses context.messages when provided', async () => {
    mockSendAIMessage.mockResolvedValue(undefined);
    const provider = new ExternalLLMProvider({ projectId: 'proj-1' });
    await provider.generate('ignored', {
      messages: [
        { role: 'user', content: 'from context' },
      ],
    });
    const [, messages] = mockSendAIMessage.mock.calls[0] as [
      unknown,
      Array<{ role: string; content: string }>,
    ];
    const userMsgs = messages.filter((m) => m.role === 'user');
    expect(userMsgs[0].content).toBe('from context');
  });
});

// ---------------------------------------------------------------------------
// PromptApiModelProvider — Chrome built-in (Gemini Nano)
// ---------------------------------------------------------------------------

function readableOf(chunks: string[]): ReadableStream<string> {
  return new ReadableStream<string>({
    start(controller) {
      for (const c of chunks) controller.enqueue(c);
      controller.close();
    },
  });
}

function installFakePromptApi(overrides: Record<string, unknown> = {}) {
  const session = {
    prompt: vi.fn().mockResolvedValue('full answer'),
    promptStreaming: vi.fn(() => readableOf(['Hel', 'lo', ' world'])),
    clone: vi.fn(),
    destroy: vi.fn(),
    inputUsage: 5,
    inputQuota: 100,
    ...overrides,
  };
  const factory = {
    availability: vi.fn().mockResolvedValue('available'),
    create: vi.fn().mockResolvedValue(session),
  };
  (globalThis as unknown as { LanguageModel?: unknown }).LanguageModel = factory;
  return { session, factory };
}

function removeFakePromptApi() {
  delete (globalThis as unknown as { LanguageModel?: unknown }).LanguageModel;
}

describe('PromptApiModelProvider', () => {
  afterEach(() => {
    removeFakePromptApi();
    vi.restoreAllMocks();
  });

  it('has correct identity properties', () => {
    const p = new PromptApiModelProvider();
    expect(p.id).toBe('prompt-api');
    expect(p.isLocal).toBe(true);
  });

  it('hasPromptApi() reflects the global surface', () => {
    expect(hasPromptApi()).toBe(false);
    installFakePromptApi();
    expect(hasPromptApi()).toBe(true);
  });

  it('is not ready and records a reason when the Prompt API is absent', async () => {
    const p = new PromptApiModelProvider();
    await p.init();
    expect(p.isReady()).toBe(false);
    expect(p.failureReason()).toMatch(/not available/i);
  });

  it('becomes ready and passes the system prompt to create()', async () => {
    const { factory } = installFakePromptApi();
    const p = new PromptApiModelProvider({ systemPrompt: 'Be concise.' });
    await p.init();
    expect(p.isReady()).toBe(true);
    const createArg = factory.create.mock.calls[0][0];
    expect(createArg.initialPrompts).toEqual([{ role: 'system', content: 'Be concise.' }]);
  });

  it('is not ready when the model is unavailable on-device', async () => {
    const { factory } = installFakePromptApi();
    factory.availability.mockResolvedValue('unavailable');
    const p = new PromptApiModelProvider();
    await p.init();
    expect(p.isReady()).toBe(false);
  });

  it('stream() emits real per-token deltas and returns the full text', async () => {
    installFakePromptApi();
    const p = new PromptApiModelProvider();
    await p.init();
    const tokens: string[] = [];
    const full = await p.stream('hi', undefined, (t) => tokens.push(t));
    expect(tokens).toEqual(['Hel', 'lo', ' world']);
    expect(full).toBe('Hello world');
  });

  it('stream() normalises cumulative-style chunks to deltas', async () => {
    installFakePromptApi({
      promptStreaming: vi.fn(() => readableOf(['Hel', 'Hello', 'Hello world'])),
    });
    const p = new PromptApiModelProvider();
    await p.init();
    const tokens: string[] = [];
    const full = await p.stream('hi', undefined, (t) => tokens.push(t));
    expect(tokens).toEqual(['Hel', 'lo', ' world']);
    expect(full).toBe('Hello world');
  });

  it('tokenBudget() surfaces the session usage/quota', async () => {
    installFakePromptApi();
    const p = new PromptApiModelProvider();
    await p.init();
    expect(p.tokenBudget()).toEqual({ used: 5, quota: 100 });
  });

  it('dispose() destroys the session', async () => {
    const { session } = installFakePromptApi();
    const p = new PromptApiModelProvider();
    await p.init();
    p.dispose();
    expect(session.destroy).toHaveBeenCalledOnce();
    expect(p.isReady()).toBe(false);
  });
});

// ---------------------------------------------------------------------------
// CascadingModelProvider — progressive-enhancement chain
// ---------------------------------------------------------------------------

function stubProvider(id: string, ready: boolean, opts: Partial<ModelProvider> & { answer?: string; throws?: boolean } = {}): ModelProvider {
  return {
    id,
    name: id,
    isLocal: opts.isLocal ?? true,
    isReady: () => ready,
    init: vi.fn().mockResolvedValue(undefined),
    generate: vi.fn(async () => {
      if (opts.throws) throw new Error(`${id} failed`);
      return opts.answer ?? `${id}:answer`;
    }),
    stream: vi.fn(async (_i, _c, onToken?: (t: string) => void) => {
      if (opts.throws) throw new Error(`${id} failed`);
      onToken?.(opts.answer ?? `${id}:answer`);
      return opts.answer ?? `${id}:answer`;
    }),
    dispose: vi.fn(),
  };
}

describe('CascadingModelProvider', () => {
  it('routes to the highest-priority ready tier', async () => {
    const t1 = stubProvider('tier1', true, { answer: 'from-1' });
    const t2 = stubProvider('tier2', true, { answer: 'from-2' });
    const cascade = new CascadingModelProvider([t1, t2]);
    await cascade.init();
    expect(await cascade.generate('x')).toBe('from-1');
    expect(cascade.active().id).toBe('tier1');
  });

  it('skips not-ready tiers and picks the first ready one', async () => {
    const t1 = stubProvider('tier1', false);
    const t2 = stubProvider('tier2', true, { answer: 'from-2' });
    const cascade = new CascadingModelProvider([t1, t2]);
    await cascade.init();
    expect(await cascade.generate('x')).toBe('from-2');
    expect(t1.generate).not.toHaveBeenCalled();
  });

  it('falls through to the next ready tier when the active one throws', async () => {
    const t1 = stubProvider('tier1', true, { throws: true });
    const t2 = stubProvider('tier2', true, { answer: 'rescued' });
    const cascade = new CascadingModelProvider([t1, t2]);
    await cascade.init();
    expect(await cascade.generate('x')).toBe('rescued');
  });

  it('init() tolerates a tier whose init() rejects', async () => {
    const bad = stubProvider('bad', false);
    (bad.init as ReturnType<typeof vi.fn>).mockRejectedValue(new Error('boom'));
    const good = stubProvider('good', true, { answer: 'ok' });
    const cascade = new CascadingModelProvider([bad, good]);
    await expect(cascade.init()).resolves.toBeUndefined();
    expect(await cascade.generate('x')).toBe('ok');
  });

  it('isLocal reflects the active backend', async () => {
    const local = stubProvider('local', false, { isLocal: true });
    const cloud = stubProvider('cloud', true, { isLocal: false });
    const cascade = new CascadingModelProvider([local, cloud]);
    await cascade.init();
    expect(cascade.isLocal).toBe(false);
  });
});

describe('createInferenceProvider', () => {
  afterEach(removeFakePromptApi);

  it('always includes a cloud fallback tier', async () => {
    const cascade = createInferenceProvider({ projectId: 'p1' });
    await cascade.init();
    // With no Prompt API and no local model, the only (and active) tier is cloud.
    expect(cascade.active().id).toBe('external-llm');
    expect(cascade.isReady()).toBe(true);
  });

  it('prepends the Prompt API tier when the browser exposes it', async () => {
    installFakePromptApi();
    const cascade = createInferenceProvider({ projectId: 'p1', systemPrompt: 'Hi' });
    await cascade.init();
    expect(cascade.active().id).toBe('prompt-api');
  });
});

// ---------------------------------------------------------------------------
// WebGPUTrainer — real engine wiring (no synthetic loss / no fake fallback)
// ---------------------------------------------------------------------------

describe('WebGPUTrainer (real engine wiring)', () => {
  function makeTrainer(overrides: Partial<WebGPUTrainerOptions> = {}) {
    const logs: string[] = [];
    const trainer = new WebGPUTrainer({
      modelId: 'gpt-neox-20m',
      workerUrl: 'http://localhost',
      projectId: 'proj-1',
      onLog: (m) => logs.push(m),
      onStep: () => {},
      onEpochEnd: () => {},
      onComplete: () => {},
      onError: () => {},
      ...overrides,
    });
    return { trainer, logs };
  }

  it('init() surfaces a REAL error when WebGPU/engine is unavailable (no fake fallback)', async () => {
    // jsdom has no navigator.gpu, so the underlying MambaModelProvider never
    // becomes ready — init must throw rather than silently simulate.
    const { trainer } = makeTrainer();
    await expect(trainer.init()).rejects.toThrow(/WebGPU training engine unavailable/i);
  });

  it('train() refuses to run before a successful init() (no synthetic loop)', async () => {
    const { trainer } = makeTrainer();
    await expect(
      trainer.train(
        {
          epochs: 2,
          batchSize: 4,
          learningRate: 1e-4,
          gradientAccumulationSteps: 1,
          precision: 'float16',
          loraConfig: { rank: 8, alpha: 16, targetModules: ['q_proj'] },
        },
        ['example'],
      ),
    ).rejects.toThrow(/not initialised/i);
  });

  it('drives the REAL MambaModelProvider.train + exportTrainedWeights (real loss + real weights)', async () => {
    const { trainer, logs } = makeTrainer({ jobId: 'job-1' });

    const realLosses = [2.2, 1.5];
    const realWeights = new ArrayBuffer(256);
    const fakeProvider = {
      isReady: () => true,
      train: vi.fn().mockImplementation(
        async (_corpus: string, opts: { onEpochEnd?: (e: number, l: number) => void }) => {
          realLosses.forEach((l, i) => opts.onEpochEnd?.(i + 1, l));
          return realLosses;
        },
      ),
      exportTrainedWeights: vi.fn().mockResolvedValue(realWeights),
      dispose: vi.fn(),
    };

    const steps: TrainingStep[] = [];
    (trainer as any).options.onStep = (s: TrainingStep) => steps.push(s);

    // Inject a ready provider (simulating a successful init on a real GPU).
    (trainer as any).provider = fakeProvider;

    const { uploadArtifact } = await import('./api');
    (uploadArtifact as ReturnType<typeof vi.fn>).mockResolvedValue({ r2Key: 'adapters/real.bin' });

    let completedKey = '';
    (trainer as any).options.onComplete = (k: string) => { completedKey = k; };

    await trainer.train(
      {
        epochs: 2,
        batchSize: 4,
        learningRate: 3e-4,
        gradientAccumulationSteps: 1,
        precision: 'float16',
        loraConfig: { rank: 8, alpha: 16, targetModules: ['q_proj'] },
      },
      ['real training text'],
    );

    // Real trainer was driven, real losses surfaced as steps.
    expect(fakeProvider.train).toHaveBeenCalledOnce();
    expect(steps.map((s) => s.loss)).toEqual(realLosses);
    // Real serialised weights were uploaded (not placeholder bytes).
    expect(fakeProvider.exportTrainedWeights).toHaveBeenCalledOnce();
    expect(uploadArtifact).toHaveBeenCalledWith('job-1', realWeights);
    expect(completedKey).toBe('adapters/real.bin');
  });

  it('source contains no synthetic Math.exp / Math.random loss generation', async () => {
    // Guard against regressions reintroducing the fake loss curve.
    const fs = await import('node:fs');
    const url = await import('node:url');
    const path = await import('node:path');
    const here = path.dirname(url.fileURLToPath(import.meta.url));
    const src = fs.readFileSync(path.join(here, 'webgpu-trainer.ts'), 'utf8');
    expect(src).not.toMatch(/Math\.exp/);
    expect(src).not.toMatch(/Math\.random/);
    // The old "prove GPU writing works" buffer hack must be gone.
    expect(src).not.toMatch(/prove GPU/i);
  });
});
