export type VideoResumeScene = { id: string; duration: number; title: string; subtitle?: string; items?: string[]; transition?: 'cut' | 'fade' | 'slide' | 'zoom' };
export type VideoResumeTemplate = { id: string; label: string; profession: string; duration: number; colors: [string, string, string, string]; scenes: VideoResumeScene[] };

const standardScenes = (open: string, credentials: string, recent: string, bring: string, ask: string): VideoResumeScene[] => [
  { id: 'open', duration: 5, title: open }, { id: 'credentials', duration: 13, title: credentials }, { id: 'recent', duration: 13, title: recent }, { id: 'bring', duration: 13, title: bring }, { id: 'ask', duration: 16, title: ask },
];

/** Hired Studio's complete first-party video-résumé starter catalog. */
export const VIDEO_RESUME_TEMPLATES: readonly VideoResumeTemplate[] = [
  { id: 'video-resume-professional', label: 'Professional', profession: 'General', duration: 28, colors: ['#7c3aed','#2563eb','#e2e8f0','#c4b5fd'], scenes: [{id:'intro',duration:7,title:'Your Name',subtitle:'Your Title · Company'},{id:'achievement',duration:7,title:'Key Achievements'},{id:'skills',duration:7,title:'Core Skills'},{id:'closing',duration:7,title:"Let's Connect"}] },
  { id: 'video-resume-minimal', label: 'Minimal', profession: 'General', duration: 20, colors: ['#18181b','#3f3f46','#ffffff','#a1a1aa'], scenes: [{id:'intro',duration:5,title:'Your Name'},{id:'achievement',duration:5,title:'Highlights'},{id:'skills',duration:5,title:'Skills'},{id:'closing',duration:5,title:'Open to opportunities'}] },
  { id: 'video-resume-hook-led', label: 'Hook-led', profession: 'Product / design', duration: 60, colors: ['#0f172a','#1e293b','#f8fafc','#38bdf8'], scenes: [{id:'hook',duration:5,title:'Lead with your strongest measurable result.'},{id:'context',duration:12,title:'The Problem'},{id:'approach',duration:15,title:'What I Did'},{id:'result',duration:10,title:'The Result'},{id:'pivot',duration:12,title:"What I'm Looking For"},{id:'close',duration:6,title:"Let's talk."}] },
  { id: 'video-resume-story-led', label: 'Story-led', profession: 'Engineering / operations', duration: 75, colors: ['#0c0a09','#292524','#fafaf9','#f59e0b'], scenes: [{id:'open',duration:6,title:'Open with one memorable project.'},{id:'stakes',duration:12,title:'The Stakes'},{id:'decision',duration:14,title:'The Hard Decision'},{id:'execution',duration:14,title:'How We Pulled It Off'},{id:'outcome',duration:10,title:'The Outcome'},{id:'lesson',duration:12,title:'What This Says About How I Work'},{id:'close',duration:7,title:"Let's talk."}] },
  { id: 'video-resume-pivot-led', label: 'Pivot-led', profession: 'Career transition', duration: 60, colors: ['#064e3b','#022c22','#ecfdf5','#34d399'], scenes: [{id:'open',duration:5,title:'Name the career pivot.'},{id:'background',duration:12,title:"Where I'm Coming From"},{id:'trigger',duration:12,title:'Why I Switched'},{id:'bridge',duration:12,title:"What I've Done Since"},{id:'value',duration:10,title:'What My Background Adds'},{id:'ask',duration:9,title:'Name the role you want.'}] },
  { id: 'video-resume-beauty-portfolio', label: 'Beauty portfolio', profession: 'Beauty', duration: 60, colors: ['#831843','#f472b6','#500724','#fce7f3'], scenes: standardScenes('Master stylist. 6 years behind the chair. Building my book.','License & training','Recent work','What I bring','Open to chair rental in [city].') },
  { id: 'video-resume-campaign-staff', label: 'Campaign staff', profession: 'Politics', duration: 60, colors: ['#7f1d1d','#fca5a5','#450a0a','#fee2e2'], scenes: standardScenes('Field organizer. 3 cycles. Built turf from scratch in 2 states.','Cycles worked','What I built','What I bring','Open to state director / regional roles.') },
  { id: 'video-resume-candidate-intro', label: 'Candidate introduction', profession: 'Politics', duration: 60, colors: ['#365314','#fbbf24','#1a2e05','#fef3c7'], scenes: standardScenes('Running for school board, District 4.','Why I am running','What I would do in office','What I bring','Election: [date].') },
  { id: 'video-resume-gig-rapid-deploy', label: 'Rapid deploy', profession: 'Gig / logistics', duration: 60, colors: ['#365314','#a3e635','#1a2e05','#f7fee7'], scenes: standardScenes('Multi-app driver. 4 years, 12,000 rides, 4.97★.','Platforms & status','Recent stretch','What I bring','Open to courier, last-mile, and fleet roles.') },
  { id: 'video-resume-government-clearance', label: 'Government clearance', profession: 'Government', duration: 60, colors: ['#1e3a8a','#93c5fd','#172554','#eff6ff'], scenes: standardScenes('Cleared cyber analyst — TS/SCI.','Clearance & credentials','Mission work','What I bring','Open to cleared cyber / SOC roles.') },
  { id: 'video-resume-security-cleared', label: 'Security cleared', profession: 'Security', duration: 60, colors: ['#111827','#ef4444','#1f2937','#fee2e2'], scenes: standardScenes('Armed security. EP-trained.','Licensure & training','Recent engagements','What I bring','Open to EP / GSOC / corporate-security roles.') },
  { id: 'video-resume-law-enforcement', label: 'Law enforcement', profession: 'Law enforcement', duration: 60, colors: ['#1e293b','#facc15','#0f172a','#fef9c3'], scenes: standardScenes('POST-certified officer. 6 years patrol.','Certification & training','Assignments','What I bring','Open to specialty unit roles.') },
  { id: 'video-resume-legal-bar', label: 'Legal / bar', profession: 'Legal', duration: 60, colors: ['#1e1b4b','#a5b4fc','#312e81','#f5f3ff'], scenes: standardScenes('Litigator. 7 years civil practice.','Admission & credentials','Cases & specializations','What I bring','Open to associate / counsel roles.') },
  { id: 'video-resume-medical-credentialed', label: 'Medical credentialed', profession: 'Healthcare', duration: 60, colors: ['#0e7490','#67e8f9','#083344','#ecfeff'], scenes: standardScenes('Licensed nurse. 5 years bedside.','Licensure & credentials','Bedside experience','What I bring','Open to step-down ICU / CVICU roles.') },
  { id: 'video-resume-trade-licensed', label: 'Licensed trade', profession: 'Skilled trades', duration: 60, colors: ['#7c2d12','#fbbf24','#451a03','#fef3c7'], scenes: standardScenes('Journeyman electrician. 9 years on the tools.','License & affiliation','Recent jobs','What I bring','Open to journeyman / foreman roles.') },
] as const;

export function videoResumeTemplatePatch(template: VideoResumeTemplate) {
  return { videoResumeTemplateId: template.id, videoStoryboard: template.scenes, accent: template.colors[0], duration: template.duration, status: 'Storyboard ready' };
}
