#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
IMAGE_NAME="${BUILDERFORCE_AGENTS_INSTALL_E2E_IMAGE:-${BUILDERFORCE_AGENTS_INSTALL_E2E_IMAGE:-builderforce-install-e2e:local}}"
INSTALL_URL="${BUILDERFORCE_AGENTS_INSTALL_URL:-${BUILDERFORCE_AGENTS_INSTALL_URL:-https://builderforce.ai/install.sh}}"

OPENAI_API_KEY="${OPENAI_API_KEY:-}"
ANTHROPIC_API_KEY="${ANTHROPIC_API_KEY:-}"
ANTHROPIC_API_TOKEN="${ANTHROPIC_API_TOKEN:-}"
BUILDERFORCE_AGENTS_E2E_MODELS="${BUILDERFORCE_AGENTS_E2E_MODELS:-${BUILDERFORCE_AGENTS_E2E_MODELS:-}}"

echo "==> Build image: $IMAGE_NAME"
docker build \
  -t "$IMAGE_NAME" \
  -f "$ROOT_DIR/scripts/docker/install-sh-e2e/Dockerfile" \
  "$ROOT_DIR/scripts/docker/install-sh-e2e"

echo "==> Run E2E installer test"
docker run --rm \
  -e BUILDERFORCE_AGENTS_INSTALL_URL="$INSTALL_URL" \
  -e BUILDERFORCE_AGENTS_INSTALL_TAG="${BUILDERFORCE_AGENTS_INSTALL_TAG:-${BUILDERFORCE_AGENTS_INSTALL_TAG:-latest}}" \
  -e BUILDERFORCE_AGENTS_E2E_MODELS="$BUILDERFORCE_AGENTS_E2E_MODELS" \
  -e BUILDERFORCE_AGENTS_INSTALL_E2E_PREVIOUS="${BUILDERFORCE_AGENTS_INSTALL_E2E_PREVIOUS:-${BUILDERFORCE_AGENTS_INSTALL_E2E_PREVIOUS:-}}" \
  -e BUILDERFORCE_AGENTS_INSTALL_E2E_SKIP_PREVIOUS="${BUILDERFORCE_AGENTS_INSTALL_E2E_SKIP_PREVIOUS:-${BUILDERFORCE_AGENTS_INSTALL_E2E_SKIP_PREVIOUS:-0}}" \
  -e OPENAI_API_KEY="$OPENAI_API_KEY" \
  -e ANTHROPIC_API_KEY="$ANTHROPIC_API_KEY" \
  -e ANTHROPIC_API_TOKEN="$ANTHROPIC_API_TOKEN" \
  "$IMAGE_NAME"
